### ISSUE TITLE
Encoding Problems

### ISSUE THREAD

**Issue by proin** [ONLYOFFICE/Docker-DocumentServer#1]
when I was editing some document, not-english characters (korean) are not visible and do not typing characters.
I think that invisible characters problem is caused by fonts..
but did you restricted typing in document editor?

**Comment by proin** [comment]
I think it is very useful if you should make some api about adding fonts to document editor for support multi languages.
I try to install font (nanum-gothic) and change javascript file at /var/www/onlyoffice/documentserver/DocService/OfficeWeb/sdk/Common, 
I can visible korean characters.

Is any other solution to add font at document editor?

**Comment by AnaMih** [comment]
There are probably no necessary fonts on the server. 
Please follow the instructions in order to resolve the issue:
add the fonts to your os and reinstall Оnlyoffice Document Server package.The necessary files will be changed according to a new font list.

**Comment by proin** [comment]
if i change parent is font, is there changed the docker container's font too?
or document server has other isntall packages not docker?

**Comment by AnaMih** [comment]
To mount folder with fonts follow the instructions: : 
1. sudo docker run -i -t -d -p 80:80 -v /home/font:/usr/share/fonts/test_font onlyoffice/documentserver
where 
/home/font - the folder with fonts on host os
/usr/share/fonts/test_font - the folder, where the fonts should be put 

2. docker attach your_container_id

3. /var/www/onlyoffice/documentserver/Tools/AllFontsGen" "/usr/share/fonts 
/var/www/onlyoffice/documentserver/DocService/OfficeWeb/sdk/Common/AllFonts.js 
/var/www/onlyoffice/documentserver/DocService/OfficeWeb/sdk/Common/Images 
/var/www/onlyoffice/documentserver/FileConverterService/Bin/font_selection.bin
(rebuilding fonts)

4. supervisorctl restart FileconverteService 
(service restart)

Pay attention, that should be used *.ttf and *.ttc fonts.
