### ISSUE TITLE
Error occurred in the document service: Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by pork94** [ONLYOFFICE/Docker-DocumentServer#101]
I recently installed a docker container which integrates nextcloud and onlyoffice together from the following [link](https://www.linuxbabe.com/docker/onlyoffice-nextcloud-integration-docker).

Everything is working fine even the setting up of HTTPS.

However when I tried to save the settings for onlyoffice, i get this error log:
`CommandRequest on check error: Error occurred in the document service: Error while downloading the document file to be converted.`

**Comment by ibnpetr** [comment]
Please try disabling node.js certificate check in the Docker container following the insctructions
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/96#issuecomment-405180858

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
