### ISSUE TITLE
PostgreSQL DB name not recognized

### ISSUE THREAD

**Issue by temparus** [ONLYOFFICE/Docker-DocumentServer#106]
I've configured the docker container (image `onlyoffice/documentserver:latest`) using the following environment variables for using an external PostgreSQL database server:

```
POSTGRESQL_SERVER_HOST=<some-database-host>
POSTGRESQL_SERVER_PORT=5432
POSTGRESQL_SERVER_DB_NAME=<db-name>
POSTGRESQL_SERVER_USER=<correct-user>
```

Unfortunately, I get an error:
```
psql: FATAL:  no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "<correct-user>", database "postgres", SSL off
```

It looks like the `POSTGRESQL_SERVER_DB_NAME` does not get recognized at all. Interestingly the USER variable is correctly used.
On a previous build of the image, this worked like a charm.

Were there any changes which are not reflected correctly by the README?

**Comment by agolybev** [comment]
Hi @temparus,  What about ` POSTGRESQL_SERVER_PASS` param? And ensure is the db and db user exist. The ones should be created before documentserver is started.

**Comment by temparus** [comment]
Ah sure, I also use `POSTGRESQL_SERVER_PASS` to specify the password. The server runs on another server and has been started long before OnlyOffice.

Do I see the user `postgres` because that is the last possibility the pgsql client tries out?
This is weird as the server is accessible using `psql` with the given data.

**Comment by temparus** [comment]
Hm, it seems that this was not the problem. Now it works somehow but the error is still logged. I have no idea why this is. Nevermind, the problem seems to be solved.
