### ISSUE TITLE
The document could not be saved. Please check connection settings or contact your administrator.

### ISSUE THREAD

**Issue by gravin** [ONLYOFFICE/Docker-DocumentServer#109]
doesnt work, it always pops up with dialog
The document could not be saved. Please check connection settings or contact your administrator.

cant view,create,save etc.

and it doesnt support UTF-8 files;

**Comment by ShockwaveNN** [comment]
This already fixed in https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/98

**Comment by ShockwaveNN** [comment]
Please fill issue template accordingly and add details about your network infrastructure

**Comment by ShockwaveNN** [comment]
This issue is being closed due to no response
