### ISSUE TITLE
Updating DocumentServer

### ISSUE THREAD

**Issue by nickian** [ONLYOFFICE/Docker-DocumentServer#110]
I can't seem to find any documentation about this. How can I update the DocumentServer Docker container to the latest version? I'm running 5.0.7, just wondering if I can update to 5.1 and how to keep the installation up to date.

Thanks

**Comment by ShockwaveNN** [comment]
If you store all you data in volumes you should stop old container and start a newest one. There may be some minor troubles with config files, but everything else should be fine.

**Comment by nickian** [comment]
I didn't do that. I just ended up running this and it seemed to work. Coincidentally my Let's Encrypt certificate expired last night and it did not automatically renew. Would that have something to do with the update?

```
wget http://download.onlyoffice.com/install/opensource-install.sh
sudo bash opensource-install.sh -ims false -cc onlyoffice-community-server -dc onlyoffice-document-server -u true
```

**Comment by Carazyda** [comment]
If you installed using opensource-install.sh, then there are no problems with the update. But if you started containers used "docker run" command, you should follow ShockwaveNN instructions.

**Comment by nickian** [comment]
Ok, good to know. Thanks!
