### ISSUE TITLE
Data Container on Docker Swarm with Traefik

### ISSUE THREAD

**Issue by temparus** [ONLYOFFICE/Docker-DocumentServer#116]
When not using the data container (everything in one container), it works as expected.

Now we want to scale it up so that we can run multiple instances in parallel. First we tried is without a data container. Then we experienced data losses, so entered data in an excel sheet were partly missing from one moment to another.

Then we tried it again with using a data container. We run the services on a Docker Swarm Cluster with Traefik as reverse proxy. Using the configuration from the example file `docker-compose.yml` of this repository we have configured two services:  `documentserver` and `documentserver-data`

When calling the welcome page, we get an error «502 Bad Gateway». 

The log of `documentserver`:
```
2018/07/17 23:03:18 [error] 1675#1675: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.6, server: , request: "GET /welcome/img/favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/img/favicon.ico", host: "<onlyoffice-domain>"
```

The log of `documentserver-data`:
```
2018/07/17 23:03:18 [error] 1675#1675: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.6, server: , request: "GET /welcome/img/favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/img/favicon.ico", host: "<onlyoffice-domain>"
```

1) What is the data container exactly used for?
2) Any idea what causes this problem?

**Comment by agolybev** [comment]
Hi @temparus.
1. The data container is used to share settings, cache, and fonts between nodes of the document server. Each node of the document server can handle editing session so they should have the equal settings and common cache.
2. The common mistake while proxying traffic to document server is missing `X-Forwarded-` headers. See [here](https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx) about it. Also, you could use our [proxy example](https://github.com/ONLYOFFICE/document-server-proxy/tree/master/traefik) as a reference. For more advice, you could send me your `docker-compose.yml` file.

**Comment by temparus** [comment]
Thanks for your reply.

For the documentserver traefik frontend, the option `passHostHeader` is set to `true`. 

We do not use docker-compose files as we manage the cluster using Portainer.
You can find our service configuration below:

## Service configurations

### onlyoffice-documentserver

**Shared volumes using SAMBA**

| Volume Name        | Mountpoint in container |
| ------------------------- |:-------------------------------:|
| Log-Volume            | /var/log/onlyoffice          |
| Data-Volume          | /var/www/onlyoffice/Data |
| Font-Volume          | /usr/share/fonts              |
| Cache-Volume       | /var/lib/onlyoffice/documentserver/App_Data/cache/files |

**Environment Variables**

| Name                     | Value                              |
| ------------------------- |:-------------------------------:|
| ONLYOFFICE_DATA_CONTAINER_HOST | onlyoffice-documentserver-data |
| POSTGRESQL_SERVER_HOST                | *\<some-external-db-server\>* |
| POSTGRESQL_SERVER_PORT                | 5432 |
| POSTGRESQL_SERVER_DB_NAME        | *\<db-name\>* |
| POSTGRESQL_SERVER_USER                | *\<db-user\>* |
| POSTGRESQL_SERVER_PASS                | *\<db-password\>* |
| RABBITMQ_SERVER_URL                        | amqp://guest:guest@onlyoffice-rabbitmq |
| REDIS_SERVER_HOST                             | onlyoffice-redis |
| REDIS_SERVER_PORT                             | 6379 |

**Traefik configuration** (as Service Labels)

| Name                     | Value                              |
| ------------------------- |:-------------------------------:|
| traefik.docker.network | frontend |
| traefik.frontend.passHostHeader | true |
| traefik.frontend.rule | *\<onlyoffice-domain\>* |
| traefik.port | 80 |

### onlyoffice-documentserver-data

**Shared volumes using SAMBA**

| Volume Name        | Mountpoint in container |
| ------------------------- |:-------------------------------:|
| Log-Volume            | /var/log/onlyoffice          |
| Data-Volume          | /var/www/onlyoffice/Data |
| Font-Volume          | /usr/share/fonts              |
| Cache-Volume       | /var/lib/onlyoffice/documentserver/App_Data/cache/files |

**Environment Variables**

| Name                     | Value                              |
| ------------------------- |:-------------------------------:|
| ONLYOFFICE_DATA_CONTAINER             | true |
| POSTGRESQL_SERVER_HOST                | *\<some-external-db-server\>* |
| POSTGRESQL_SERVER_PORT                | 5432 |
| POSTGRESQL_SERVER_DB_NAME        | *\<db-name\>* |
| POSTGRESQL_SERVER_USER                | *\<db-user\>* |
| POSTGRESQL_SERVER_PASS                | *\<db-password\>* |
| RABBITMQ_SERVER_URL                        | amqp://guest:guest@onlyoffice-rabbitmq |
| REDIS_SERVER_HOST                             | onlyoffice-redis |
| REDIS_SERVER_PORT                             | 6379 |

### onlyoffice-redis

No additional configuration.

### onlyoffice-rabbitmq

No additional configuration.

**Comment by agolybev** [comment]
@temparus, I'm not familiar with Portainer, could you send me the name of the used Traefik docker image?

**Comment by temparus** [comment]
The used traefik docker image is `traefik:1.6-alpine`.

**Comment by agolybev** [comment]
@temparus, I'll add cluster config for `traefik` and others proxy servers.

**Comment by temparus** [comment]
Are there any updates?

**Comment by igwyd** [comment]
Hello @temparus, sorry for the late reply, examples were added long ago https://github.com/ONLYOFFICE/document-server-proxy/tree/master/traefik I think we need to close this.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
