### ISSUE TITLE
sdk-all.js:6549 Uncaught TypeError: this.va.fc.OUa is not a function

### ISSUE THREAD

**Issue by lingks** [ONLYOFFICE/Docker-DocumentServer#117]
sdk-all.js:6549 Uncaught TypeError: this.va.fc.OUa is not a function

**Comment by ShockwaveNN** [comment]
@lingks please fill all template fields, in current state it's completely useless

**Comment by lingks** [comment]
When opening history, there will be jssdk errors in individual editions.
![qq 20180719152606](https://user-images.githubusercontent.com/32865119/43030880-9f7cc880-8cc9-11e8-80c1-4c433bc7a4b3.png)

**Comment by ShockwaveNN** [comment]
Duplicated at https://github.com/ONLYOFFICE/DocumentServer/issues/351
