### ISSUE TITLE
Docker Compose upgrade issues

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Docker-DocumentServer#120]
1. cd to directory with [docker-compose.yml](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml)
2. Replace all `image: onlyoffice/documentserver:latest` to `image: onlyoffice/documentserver:5.1.4.22` to simulate upgrade
3. `docker-compose up -d`
4. go to `localhost` and check that everything fine
5. replace `image: onlyoffice/documentserver:5.1.4.22` to `image: onlyoffice/documentserver:latest` in compose file
6. `docker-compose stop onlyoffice-documentserver-data onlyoffice-documentserver`
7. `docker-compose up -d`

Result:
On localhost
```
503 Service Unavailable
No server is available to handle this request.
```

Maybe this is not right way to upgrade compose, so question is what is the right way to upgrade it

**DocumentServer Docker tag:** 5.1.4.22 Upgrade 5.1.5.59

**Host Operating System:** ubuntu 18.04

**Comment by possybility** [comment]
I'm having the same issue, but from a clean install; also using docker-compose.
**Host operating system: **Ubuntu 18.04.01
**Docker version: **18.06.1-ce
**DocumontServer version: **latest

If I can help by providing output...

**Comment by ShockwaveNN** [comment]
@possybility created seprated issue https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/133

**Comment by igwyd** [comment]
The issue is no longer relevant. The compose file doesn't specify the version, the documentserver is built from the current repository.
