### ISSUE TITLE
Can`t connect ONLYOFFICE from Nextcloud in docker.

### ISSUE THREAD

**Issue by mervynsword** [ONLYOFFICE/Docker-DocumentServer#123]
Hi,
I am tring to connect OnlyOffice from Nextcloud.Both OnlyOffice and Nextcloud are running in docker.

I am using portainer and running OnlyOffice with selecting interactive mode and TTY (-i -t) and using HTTPS.Now everything is running well.But I just can`t connect OnlyOffice from the nextcloud.The note said 

> Error when trying to connect (Bad Request or timeout error)

I am 100% sure both the containers are in one docker network.And in the OnlyOffice container,the nginx is running well.

The OnlyOffice container log is here.

>  * Starting PostgreSQL 9.5 database server        
[ OK ]
, * Starting RabbitMQ Messaging Server rabbitmq-server        
[ OK ]
,Starting redis-server: redis-server.
,Starting supervisor: supervisord.
, * Starting nginx nginx        
[ OK ]
,Generating AllFonts.js, please wait...Done
,onlyoffice-documentserver:docservice: stopped
,onlyoffice-documentserver:docservice: started
,onlyoffice-documentserver:converter: stopped
,onlyoffice-documentserver:converter: started
, * Reloading nginx configuration nginx        
[ OK ]
,

I have mounted these volumes.

> /var/www/onlyoffice/Data/certs
/var/lib/onlyoffice
/etc/onlyoffice
/var/log/onlyoffice
/var/www/onlyoffice/Data
/usr/share/fonts/truetype/custom
/var/lib/postgresql

And the OnlyOffice container ENV details are here.

> 

Name | Value
-- | --
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG | en_US.UTF-8
LANGUAGE | en_US:en
LC_ALL | en_US.UTF-8
DEBIAN_FRONTEND | noninteractive
ONLYOFFICE_HTTPS_HSTS_ENABLED | true
SSL_CERTIFICATE_PATH | /var/www/onlyoffice/Data/certs/onlyoffice.crt
SSL_KEY_PATH | /var/www/onlyoffice/Data/certs/onlyoffice.key
SSL_DHPARAM_PATH | /var/www/onlyoffice/Data/certs/dhparam.pem

Nothing else were changed in the container.

**Comment by DrRSatzteil** [comment]
Occasionally I get the same problems. In my case the container looses its ability to perform DNS lookups every now and then. When I attach to the container and try to wget the URL of the Nextcloud instance wget won’t be able to resolve the host name. Unfortunately the only solution for this I found so far is restarting the docker host machine. Neither restarting the container nor the docker service solves this problem. Maybe you can check if you encounter the same issue. I don’t have any other containers running with similar problems.

**Comment by changchichung** [comment]
I have the same problem. and I try to reboot docker host didn`t work.
any suggestions ???

**Comment by DrRSatzteil** [comment]
No, so far only rebooting the server “fixed” the problem for me. If this does not work for you I don’t know any other way to “fix” the dns issue.

**Comment by DrRSatzteil** [comment]
I finally got this „fixed“ I guess: don’t use the default bridge network for the documentserver but a custom network. I haven’t had any problems after I’ve tried this.

**Comment by ShockwaveNN** [comment]
The problems seems to be fixed, I'm closing it. If not - please create new issue
