### ISSUE TITLE
html documents

### ISSUE THREAD

**Issue by xgnusr** [ONLYOFFICE/Docker-DocumentServer#124]
**Do you want to request a *feature* or report a *bug*?** = not sure

Occasionally, html documents are stored on owncloud or other storage platforms. When an html document is opened that is possibly linked to others available in the same location ... but can not be viewed correctly. As an example, in the scientific world, it is very common to use Krona representations (html archives).
Could this be corrected in order to visualize them correctly?
I await an answer,
Very thanks in advance

**Comment by ShockwaveNN** [comment]
Viewing HTML documents is not main feature of our app, so I don't think we implement this in feature.
For support of link to external documents in OOXML format you can monitor issue https://github.com/ONLYOFFICE/DocumentServer/issues/363

**Comment by xgnusr** [comment]
I believe that in this case, we should officially remove the html support that appears as an available option.
Thanks for your reply
