### ISSUE TITLE
All Icons are the "Align Center" Icon

### ISSUE THREAD

**Issue by iamdoubz** [ONLYOFFICE/Docker-DocumentServer#125]
**Do you want to request a *feature* or report a *bug*?**
*bug* but not really, just visually annoying
**What is the current behavior?**
I open a document from Nextcloud (Document only, not Spreadsheet nor Presentation) and all the icons are the "Align Center" icon.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just installed the docker container. Created my first document and opened it. Everything looked great! I added some text then hit "Go to Documents" then opened the same document again. (Full disclosure, got a weird, this isn't the latest revision, taking you there sounding notification. Document opened but no text.) I went back to the Files app in Nextcloud. Then navigated back to the document. Text shows up, but all the icons are the "Align Center" icon.
**What is the expected behavior?**
So appropriate icons for their individual functions.
**Did this work in previous versions of DocumentServer?**
Not a clue, first time use.
**DocumentServer Docker tag:**
idk
**Host Operating System:**
Ubuntu 16.04
**Supporting Documentation:**
![2018-09-13_14-04-14](https://user-images.githubusercontent.com/4871781/45510522-1614b780-b760-11e8-9207-6f56fe28dad4.png)
![2018-09-13_14-19-28](https://user-images.githubusercontent.com/4871781/45510538-22007980-b760-11e8-80db-1dbf8883c124.png)

**Comment by ShockwaveNN** [comment]
@iamdoubz Hi, could you check that problem is reproducable on another PC and/or another browser.
I'm first time see this kind problem and only idea I have - it's somehow related with browser cache

**Comment by iamdoubz** [comment]
That was the first thing I did. Tried with Chrome and Firefox. Then switched computers and tried again with Chrome and Firefox. Same result.

I’m going to try and just docker stop&&docker rm to see if that does the trick.

**Comment by ShockwaveNN** [comment]
@iamdoubz you also cal lookup at nginx logs or onlyoffice logs inside container for any clues

**Comment by iamdoubz** [comment]
So, I did quite a few things today. I completely removed all docker containers and images that referenced onlyoffice/*. Then purged all the data from the docker volumes (docker volumes prune). After I did this, when I do docker ps OR docker image ls, nothing shows... clean slate.

So I install from scratch using: 
`docker pull onlyoffice/documentserver`
Then I start using:
```
sudo docker run -i -t -d --restart=always -p 127.0.0.1:9981:80 -p 127.0.0.1:9982:443 \
-v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
-v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
-v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver
```

I go into Nextcloud, everything is still the "Align-Center" icon.

THEREFORE, it is not docker side that has the problem. Would you agree @ShockwaveNN ?

***********************************

So, the next thing I did was completely remove the onlyoffice Nextcloud app. When I reinstalled it, it already knew my onlyoffice URL.

**Question:**

How do I remove the data that Nextcloud thinks it knows about the onlyoffice app? Where is this data stored so I can remove it!?

Thanks for all your help.

**Comment by iamdoubz** [comment]
GOT IT...

And I should have known better, but it was being caused by ModPagespeed being set to on. Just added to the <IfModule mod_ssl.c> section of my apache2 configuration file:
`ModPagespeed off`

And now everything works!! Hooray beer.

**Comment by ShockwaveNN** [comment]
@iamdoubz I'm not familural with `ModPagespeed` at all, could something in our code cause this issue or it just ModPagespeed  problem?

**Comment by iamdoubz** [comment]
So, ModPagespeed caches all images, fonts, css, scripts, etc to help improve loading times. Having it on generally is okay for basic sites and really is faster, but you sometimes run into problems. I know Matamo (formerly known as Piwik) has problems if you do not disable it.

I would say that if anything it is a bug in ModPagespeed not ONLYOFFICE.

**Comment by ShockwaveNN** [comment]
@iamdoubz ok, thanks for explanation. Our source codes already minimized by `google-closure-compiler`, maybe there is some conflict with `ModPagespeed` because of this.
I close issue, feel free to comment if you find something worth mentioning
