### ISSUE TITLE
the entrypoint script had an error

### ISSUE THREAD

**Issue by zhangguanzhang** [ONLYOFFICE/Docker-DocumentServer#134]
in file` Docker-DocumentServer/run-document-server.sh`
the line 197 should be
```bash
CREATEDB="$PSQL createdb $CONNECTION_PARAMS"
```

**Comment by ShockwaveNN** [comment]
@zhangguanzhang Hi, thank for second problem with `DB_NAME`, we agree it is not right and fixed it and it will be released as 5.2.4
But with `createdb` we don't quite understand. `createdb` is a separate linux command and provided by `postgresql-client-common` package and is present in Docker image

**Comment by zhangguanzhang** [comment]
I will try the `createdb` command  aftersoon. but I think you are right

**Comment by zhangguanzhang** [comment]
I tried this,you are right.

**Comment by ShockwaveNN** [comment]
I leave this issue opened until we release 5.2.4
