### ISSUE TITLE
Why all in one？

### ISSUE THREAD

**Issue by zhangguanzhang** [ONLYOFFICE/Docker-DocumentServer#136]
I think all server `(pgsql redis rabitmq nginx)` and the onlyoffice all in one is unfriendly

**Comment by ShockwaveNN** [comment]
We got docker-compose if you want separate containers
https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
