### ISSUE TITLE
Unary operator expected

### ISSUE THREAD

**Issue by zingmars** [ONLYOFFICE/Docker-DocumentServer#137]
When starting the docker image (onlyoffice/documentserver:latest) I get 
```
onlyoffice_1  | /app/onlyoffice/run-document-server.sh: line 284: [: !=: unary operator expected
onlyoffice_1  | /app/onlyoffice/run-document-server.sh: line 301: [: !=: unary operator expected
onlyoffice_1  | /app/onlyoffice/run-document-server.sh: line 309: [: !=: unary operator expected
<snip>
onlyoffice_1  | Starting redis-server: redis-server.
onlyoffice_1  | invalid port
onlyoffice_1  | Waiting for connection to the 5432 host on port
```

Looking at the script it would appear it has to do with environment variables (except for some reason the variable isn't quoted and it's using single brackets to do the check?), so I tried to set them in docker-compose -

```
environment:
      - POSTGRESQL_SERVER_HOST=localhost
      - RABBITMQ_SERVER_HOST="localhost"
      - REDIS_SERVER_HOST="localhost"
```

which causes this to happen - 
```
onlyoffice_1  | "localhost": forward host lookup failed: Unknown host
onlyoffice_1  | Waiting for connection to the "localhost" host on port 5432
```

This started happening when I upgraded from 5.1.5.59 (which still works) to the latest version. Any version after this doesn't seem to work.

**Comment by ShockwaveNN** [comment]
@zingmars Hi, currently we got some troubles running docker-compose (see #133), not sure this is related to your issue.

>When starting the docker image (onlyoffice/documentserver:latest) I get

Couly you show exact your command to run? I can't get same error as you

**Comment by zingmars** [comment]
Ok, so what happened was something broke (still not quite sure what), and I got the following output when starting the container - 
```
onlyoffice_1  | json: error: undefined
onlyoffice_1  | json: error: undefined
onlyoffice_1  | json: error: undefined
onlyoffice_1  | json: error: undefined
onlyoffice_1  | json: error: undefined
onlyoffice_1  | json: error: undefined
onlyoffice_1  | json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/local.json'
onlyoffice_1  | json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/local.json'
onlyoffice_1  | json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/local.json'
onlyoffice_1  | json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/local.json'
onlyoffice_1  | json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/local.json'
```
I added a blank local.json file to appease it, but apparent;y that broke the script with the error seen in the first message.

But when I did manage to get it to run, I got the following error
```
Error: Configuration property "spawnOptions" is not defined
    at Object.Config.get (/var/www/onlyoffice/documentserver/server/FileConverter/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/FileConverter/sources/converter.js:41:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js:68:21)
```
Easily fixable, but this is not the first time I've had issues with the container not starting because you've updated the configuration file with a new option. Are these changes actually documented anywhere (other than the git log)? I would prefer if I don't have to scour the example config file every time I update the service.

**Comment by ShockwaveNN** [comment]
> I've had issues with the container not starting because you've updated the configuration file with a new option

We change approach how to store configs in 5.2 and hope upgrades from 5.2 to newer versions will be more streamlined, but not guaranteed it will work flawless in all cases. 

> Are these changes actually documented anywhere
No, I don't think so

We understand this is a problem but we have no perfect solution to fix this problem for all cases

**Comment by zingmars** [comment]
Well, having some sort of update advisories or blogs would be a good place to start. At the very least, add some easily accessible file (like README) for this.

Thank you for your time.
