### ISSUE TITLE
Error when trying to connect (Bad Request or timeout error)

### ISSUE THREAD

**Issue by Ammar7347** [ONLYOFFICE/Docker-DocumentServer#140]
Hi,

I've recently installed the document server on a fresh server running Ubuntu 16.04. I want to use the onlyoffice for my nextcloud instance which is hosted on a different server. I have followed all the steps and I can access the confirmation page that the document page is running when I go to my IP 51.38.105.3. It works with both HTTP and https but unfortunately, even after installing the SSL certificate, it shows the red triangle (Not secured) sign in my browser. The thing is I don't even want to use HTTPS but it won't let me use HTTP as it says "Error when trying to connect (Mixed Active Content is not allowed. HTTPS address for Document Server is required.)". So, basically there is no option other than to use HTTPS but then I get "Error when trying to connect (Bad Request or timeout error)" even though it says document server is running even with HTTPS. Any help regarding this would be highly appreciated.

Regards,
Ammar

**Comment by ShockwaveNN** [comment]
Hi, how did you install certs and there is any nginx error inside docker in `/var/log/nginx`

**Comment by ShockwaveNN** [comment]
> It works with both HTTP and https but unfortunately, even after installing the SSL certificate, it shows the red triangle (Not secured) sign in my browser.

If DocumentServer show red triangle by itself - nextcloud have nothing to-do with https error

**Comment by Ammar7347** [comment]
So, how should I fix it? I mean I followed the official guide on github for setting it up.

**Comment by ShockwaveNN** [comment]
@Ammar7347 attach logs of DocumentServer

**Comment by Ammar7347** [comment]
`/var/log/onlyoffice` doesn't exist. This is weird

**Comment by ShockwaveNN** [comment]
@Ammar7347 are you sure DocumentServer working at all? This folder should not be empty in any cases

**Comment by Ammar7347** [comment]
@ShockwaveNN Yes it's working but the folder doesn't exist at all. I have wiped all the data on my server now and I'll do a clean install again on fresh OS. Can you please link me to a guide or an automated script for document server which I can use it to integrate with my nextcloud instance?

**Comment by ShockwaveNN** [comment]
@Ammar7347 sorry, we do not have a complete guide how to run Nextcloud and DocumentServer with https on Docker

**Comment by Ammar7347** [comment]
@ShockwaveNN I followed [this](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx) now and the same issue again. I get `Error when trying to connect (Bad Request or timeout error)` . Moreover, `/var/log/onlyoffice/documentserver/nginx.error.log` is empty. And yes the document server is running just fine as you can see for your self at https://51.38.105.3/welcome/

**Comment by ShockwaveNN** [comment]
I'll close this issue, since it's pretty old 
If issue still actual please create new issue at https://github.com/ONLYOFFICE/onlyoffice-nextcloud
