### ISSUE TITLE
changing port

### ISSUE THREAD

**Issue by maltehol** [ONLYOFFICE/Docker-DocumentServer#15]
I ran following commands:
`docker run -i -t -d -p 9000:80 onlyoffice/documentserver`
`sudo docker exec $(sudo docker ps -q) sudo supervisorctl start onlyoffice-documentserver:example`

With these I expect to have a running onlyoffice on port 9000.

when I now try to access 127.0.0.1:9000, I got redirected to  127.0.0.1/welcome, which returns of course a 404.

When I manually add the port again, I get the running welcome page.

Now accessing the example data with 127.0.0.1:9000/example and creating a new document, it creates a document, but I got redirected to port 80 again (127.0.0.1/example/editor?fileName=new.docx)

adding the correct port by hand I get a 302 temporarily moved and it redirects me to port 80 again (127.0.0.1/2016-07-12-16-21/web-apps/apps/documenteditor/main/index.html?_dc=2016-07-12-16-21&lang=en&customer=ONLYOFFICE)

Following the README.md, changing the port for the docker container when running the docker image should be enough, but it seems it isnt't?

**Comment by Schroedingers-Cat** [comment]
Same here.

**Comment by maltehol** [comment]
I add the port to the url again and request: 127.0.0.1:9000/example/editor?fileName=new.docx

**Comment by Dean13** [comment]
Hello,

Unfortunately transferring editors to different port is impossible. We will do our best to add this feature to the next versions, but custom ports forwarding will not work at the moment. 

Sorry for the inconvenience.

**Comment by colszowka** [comment]
@Dean13 I would reccoment to remove the relevant section from the README in this repo, which suggest the exact opposite: https://github.com/ONLYOFFICE/Docker-DocumentServer#running-onlyoffice-document-server-on-different-port

**Comment by ibnpetr** [comment]
@colszowka thanks a lot, removed.

**Comment by bdxing** [comment]
@Dean13 Could you give a solution?

**Comment by bdxing** [comment]
@Dean13 "Location", plus the port.

**Comment by poVoq** [comment]
So if I have another web-service running on port 80 which I can not easily move (main apache website), I can not install the docker image?
I tried something similar as above i.e.:
sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver
And if I then connect to "IP":8080, all I get is a white page with "Cannot GET /" written on it.
Any suggestions? Thanks!

**Comment by ibnpetr** [comment]
Unfortunately we cannot provide you a solution for using a custom port at the moment.
We will do our best to find a workaround.
"Cannot GET /" only means that server is running, but we will add the more adequate welcome page soon.

**Comment by tbrasser** [comment]
Are there any updates on this?

**Comment by ShockwaveNN** [comment]
Custom port will be supported in next release, version 4.3
It will be soon, like in a month.

**Comment by agolybev** [comment]
Fixed in #34
