### ISSUE TITLE
there is question then I need help ,thank you 

### ISSUE THREAD

**Issue by XWolcen** [ONLYOFFICE/Docker-DocumentServer#157]
About the latest image of doc-server

Enter the instance of container ,I found that the Nginx 443 port is not open and the configuration file is only  80 port . However, the Front-software of nextcloud 15 requires me to enter the URL of https://, otherwise I will be prompted with a protocol error.

I tried to refer to a lot of personal configuration cases, but it seems that everyone has not encountered the problem that port 443 does not exist. So, please ask if you can give me a complete onlyoffice-nginx configuration file, or guide me on this issue, how can I improve it?

Thank you, developer

![TIM截图20190412203418](https://user-images.githubusercontent.com/15225568/56037725-96d17b80-5d62-11e9-91a6-315f0edf84e7.png)

**Comment by ShockwaveNN** [comment]
https://github.com/ONLYOFFICE/Docker-DocumentServer#running-onlyoffice-document-server-using-https

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
