### ISSUE TITLE
Waiting for connection on 5672 port

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Docker-DocumentServer#163]
**What is the current behavior?**
`onlyoffice-documentserver_1       | Waiting for connection to the localhost host on port 5672`
in logs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. `git clone https://github.com/ONLYOFFICE/Docker-DocumentServer`
2. `cd Docker-DocumentServer`
3. `docker-compose up`

**DocumentServer Docker tag:** 5.3.0.243

**Host Operating System:** Ubuntu 18.04

**Comment by ShockwaveNN** [comment]
Maybe related to ipv6
`docker network inspect docker-documentserver_onlyoffice`
output 
`"EnableIPv6": false,`

**Comment by ShockwaveNN** [comment]
Can confirm fix on Docker Image onlyoffice/4testing-documentserver-ie:5.3.1.18

**Comment by ShockwaveNN** [comment]
Fixed on onlyoffice/documentserver:5.3.1.26

**Comment by happyliuxq** [comment]
hello,I also encountered this problem，docker inside error:Waitting for connection to the localhost host on port 5672 arm64 system，help！
![image](https://user-images.githubusercontent.com/93078973/177908276-21323ccb-0c34-48d9-9d77-7a12915ebadb.png)

**Comment by maijuzi** [comment]
So is there a solution to this problem

**Comment by maijuzi** [comment]
You are using docker-compose.yml Started？If yes, you can try to use docker command line starting
