### ISSUE TITLE
Onlyoffice Docker-DocumentServer User Limit

### ISSUE THREAD

**Issue by Rick26L** [ONLYOFFICE/Docker-DocumentServer#167]
We are facing the Problem, that the Onlyoffice creates a Message that this version of Onlyoffice has some restrictions for simultaneous connections. 

Do we have to Upgrade the Licence or do we have to change a value which is responsable for this limit. 

Nextcloud: 15.0.4
Onlyoffice: 2.1.10

**Comment by ShockwaveNN** [comment]
You can compare editions at https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions
