### ISSUE TITLE
can not see documents on other computer in local network 

### ISSUE THREAD

**Issue by lw5885799** [ONLYOFFICE/Docker-DocumentServer#168]
Hi, I am running the non docker version documentServer which is following the steps on official website. It works fun on each computer. I can edit documents, update.etc. But I can not see the documents from a different computer in local network. Anything I missed?

**Comment by ShockwaveNN** [comment]
Could you specify what do you mean by "I can not see the documents from a different computer in local network"
Did you use nextcloud-owncloud-onlyoffice comunity or just test example?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
