### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by baztardo** [ONLYOFFICE/Docker-DocumentServer#17]
OS Linux Ubuntu 16.04, Using the docker install method. 
STEP 1: Create the 'onlyoffice' network.
`docker network create --driver bridge onlyoffice`

STEP 1: Install ONLYOFFICE Document Server.

```
sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-document-server \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice \
    onlyoffice/documentserver
```

STEP 2: Install ONLYOFFICE Mail Server.

```
sudo docker run --net onlyoffice --privileged -i -t -d --restart=always --name onlyoffice-mail-server \
    -p 25:25 -p 143:143 -p 587:587 \
    -v /app/onlyoffice/MailServer/data:/var/vmail \
    -v /app/onlyoffice/MailServer/data/certs:/etc/pki/tls/mailserver \
    -v /app/onlyoffice/MailServer/logs:/var/log \
    -v /app/onlyoffice/MailServer/mysql:/var/lib/mysql \
    -h server.mydomain.club \
    onlyoffice/mailserver
```

STEP 3: Install ONLYOFFICE Community Server

```
sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-community-server \
    -p 8880:80 -p 5222:5222 -p 443:443 \
    -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
    -v /app/onlyoffice/CommunityServer/mysql:/var/lib/mysql \
    -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServerData \
    -e DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server \
    -e MAIL_SERVER_DB_HOST=onlyoffice-mail-server \
    onlyoffice/communityserver
```

I have installed Onlyoffice, I created virtual host for apache

`sudo nano /etc/apache2/sites-available/onlyoffice.conf`

```
<VirtualHost *:80>

        ServerName server.mydomain.club
        ServerAdmin admin@mydomain.club
#        DocumentRoot /var/www/

        ProxyPass / http://127.0.0.1:8880/
        ProxyPassReverse / http://127.0.0.1:8880/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

```
sudo a2ensite onlyoffice.conf

sudo a2enmod proxy_http

sudo service apache2 reload
```

I have a purchased CA SSL Certs from GoDaddy
I renamed them with the appropriate names and installed them into each of their directory respected directories 

```
    /app/onlyoffice/DocumentServer/data/certs/onlyoffice.key
    /app/onlyoffice/DocumentServer/data/certs/onlyoffice.crt
    /app/onlyoffice/DocumentServer/data/certs/dhparam.pem
```

And repeated this for the Document server.
The Community and mail server seam to work find but the Document server will not working with HTTPS I get an error. and cant edit the doc. I checked the Setting and I can not set the api.js path just keeps saying API url: service is not define.

I have reinstalled it countless times searched google I cant get SSL to work with the Documentserver. 

After playing around and looking throught the settting I manage to get the API.JS the Document server to be accessed at this address http://server.mydomain.club/2016-08-03-13-33/web-apps/apps/api/documents/api.js
<img width="302" alt="screen shot 2016-08-09 at 1 40 22 am" src="https://cloud.githubusercontent.com/assets/20652017/17505900/7861dd30-5dd2-11e6-8de4-d605eef9fa72.png">

may this is an error bug old code not sure.
The documents server can not be accessed localy http://10.0.1.4:8880

the editors loads but then I get a blank error message.

Any help would be appreciated, Thank you

**Comment by minhuy58** [comment]
I have the same issue. 

"I have reinstalled it countless times searched google I cant get SSL to work with the Documentserver" (me too). I also went into onlyoffice support forum to ask them, but until now, still no help.

**Comment by ibnpetr** [comment]
Hello 
`The documents server can not be accessed localy http://10.0.1.4:8880`
I regret to inform you that there may be an issue with launching DocumentServer on a custom port.
Please try changing a port, it will resolve the issue.

2minhuy58
`(me too)`
Your request has been [answered](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/7). Try changing the env file and let us know.
Best regards

**Comment by minhuy58** [comment]
Thank you, your suggestion make the site work with HTTPS.

**Comment by Libeccio84** [comment]
minhuy58 would you mind to upload your apache conf file?
I am experiencing troubles in using the Document server in https.

Many thanks!

**Comment by Huster-at-github** [comment]
@minhuy58 ???

**Comment by ShockwaveNN** [comment]
I'll close this issue, since it's pretty old
If issue still actual please create new issue
