### ISSUE TITLE
Waiting for connection to the localhost host on port 5432

### ISSUE THREAD

**Issue by pwepwe973** [ONLYOFFICE/Docker-DocumentServer#171]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I installed onlyoffice in docker and impposible to reach via port (ip / port)
I installed 100 times as many times that it worked before

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**my newspaper shows this**

 * Starting PostgreSQL 9.5 database server       [80G  [31m*[39;49m The PostgreSQL server failed to start. Please check the log output:
2019-07-10 22:55:54 UTC [127-1] LOG:  could not translate host name "localhost", service "5432" to address: Temporary failure in name resolution
2019-07-10 22:55:54 UTC [127-2] WARNING:  could not create listen socket for "localhost"
2019-07-10 22:55:54 UTC [127-3] FATAL:  could not create any TCP/IP sockets
[74G[[31mfail[39;49m]
 * Starting RabbitMQ Messaging Server rabbitmq-server       [80G [74G[ OK ]
Starting redis-server: redis-server.
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432
Waiting for connection to the localhost host on port 5432

**Comment by ShockwaveNN** [comment]
Hi, could you show exact command to run it via docker

**Comment by pwepwe973** [comment]
Hello 
la commande sur le site de /hub.docker.com/r/onlyoffice/documentserver

sudo docker run -i -t -d -p 80:80 \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver

**Comment by ShockwaveNN** [comment]
@pwepwe973 I checked you command and everything seems fine for me. Please check content of mounted folders and try to run it without them, maybe some persmissions errors

**Comment by pwepwe973** [comment]
ok i try it

**Comment by pwepwe973** [comment]
in folders onlyffice to create folders but there are no files in it

**Comment by ShockwaveNN** [comment]
@pwepwe973 I think there is some permission problems on your host

**Comment by pwepwe973** [comment]
hello
how to correct this problem? because normally the docker should be able to write in this folder

**Comment by ShockwaveNN** [comment]
Did you try 

> Please check content of mounted folders and try to run it without them, maybe some persmissions errors

I was not able to reproduce your error, sorry

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by ykzk** [comment]
I had the same issue upgrading from an old version. The problem was that I was mounting `/etc/onlyoffice` and it was empty; thus, `read_setting()` could not read the configuration from the `/etc/onlyoffice/documentserver/local.json` file, making the start-up script `run-document-server.sh` fail to run the services.
Hope this helps.

**Comment by muzhix** [comment]
I had the same issue after changed the access policy of my centos server.
The `nc` command was blocked in my server, so the `/app/ds/run-document-server.sh`  was stucked at line 167, `waiting_fro_connection()`. Just skip the connection check.
```
167 waiting_for_connection(){
168   echo "skip connection to the $1 host on port $2"
169   #until nc -z -w 3 "$1" "$2"; do
170   #  >&2 echo "Waiting for connection to the $1 host on port $2"
171   #  sleep 1
172   #done
173 }
```
Hope this helps.

**Comment by PeterMalkin** [comment]
Same issue here. Just trying to run the latest image exhibits the same behavior

docker run -it -p 80:80 -v `pwd`:/var/www/onlyoffice -v `pwd`/data:/var/www/onlyoffice/Data -v `pwd`/documentserver:/var/www/onlyoffice/documentserver onlyoffice/documentserver

**Comment by ShockwaveNN** [comment]
@PeterMalkin original issue is quite old and not figured out

Please try to run image without any volume mounts and see if it run correctly and create a new issue if got troubles with more description of your problem

**Comment by dreua** [comment]
Just in case you are using selinux: [Use bind mounts | Docker Documentation #configure-the-selinux-label](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label)

**Comment by PeterMalkin** [comment]
The latest container runs fine without any volumes mounted. I still cannot connect to the port correctly, but I believe it is a different issue and should not be conflated with this. 

Just for the record, mounting the following volumes from docker-compose file works fine to start the container up:
  onlyoffice:
    image: onlyoffice/documentserver
    restart: unless-stopped
    volumes:
      - "/onlyoffice/logs:/var/log/onlyoffice"
      - "/onlyoffice/data:/var/www/onlyoffice/Data"
      - "/onlyoffice/lib:/var/lib/onlyoffice/"
      - "/onlyoffice/rabbitmq:/var/lib/rabbitmq"
      - "/onlyoffice/redis:/var/lib/redis"
      - "/onlyoffice/postgresql:/var/lib/postgresql"
    ports:
      - "8888:80"

**Comment by ShockwaveNN** [comment]
I think it's permission issue with some mounts, probably `/var/lib/postgresql` - maybe host system got some incorrect permissions on some folder
Disable mounts one by one until you got working DocumentServer and find problem mount and after that take a look at permission of this folder or tempraly make it 777 to be sure (not to forget revert back after)

**Comment by sandav-pablo** [comment]
> I had the same issue after changed the access policy of my centos server. The `nc` command was blocked in my server, so the `/app/ds/run-document-server.sh` was stucked at line 167, `waiting_for_connection()`. Just skip the connection check.
> 
> ```
> 167 waiting_for_connection(){
> 168   echo "skip connection to the $1 host on port $2"
> 169   #until nc -z -w 3 "$1" "$2"; do
> 170   #  >&2 echo "Waiting for connection to the $1 host on port $2"
> 171   #  sleep 1
> 172   #done
> 173 }
> ```
> 
> Hope this helps.

Thanks, this solved the problem in my case. Don't really know what caused nc to stop working or if it was all image update related, but editing the script and mounting read only did the trick!

**Comment by happyliuxq** [comment]
hello,I also encountered this problem，docker inside  error:Waitting for connection to the localhost host on port 5672  arm64 system，help！
![image](https://user-images.githubusercontent.com/93078973/177900575-b92a2d57-4c3a-4a6b-9b79-18ac02a532fe.png)

**Comment by ShockwaveNN** [comment]
@happyliuxq Sorry, but we still not able to reproduce wthis problem, it has something to do with with postgresql start, maybe something unusual on your host system, but I've no idea why this happened

**Comment by russlank** [comment]
Huh! ... it seems that all guys have their machines unusual!!!

**Comment by Midnight1938** [comment]
Facing the same error, but this time with Podman

**Comment by pwepwe973** [comment]
hello

 after 2 years without this problem again back on the same machine

**Comment by pwepwe973** [comment]
hello ?

**Comment by pwepwe973** [comment]
après tout plusieurs années à utiliser onlyoffice  ces 2 ou 3 semaines a essayer de trouver la solution ce soir j'ai décider d’abandonner cette application car découragé la dernière fois il c'est répare tout seul comme ça et là malgré toute mes tentatives rien à faire, il ne fonctionne pas même lançon avec volumes etc.. bon ben merci pour ces bon moment sniff je vais chercher une alternative

**Comment by shuguang101** [comment]
Please reopen this issue.

First run podman-compose up,  wait for hours, then run podman-compose down & up several times, the following folder/file permission will be changed to  root.root, this will cause postgresql failed to start. This is strange because I haven't mounted any volume to persistent these folder/file:

```
/var/log/postgresql
/etc/ssl/private/ssl-cert-snakeoil.key 
```

```
The podman-compose yml file I used is as follows:
  oods:
    image: onlyoffice/documentserver:7.3 or 7.4
    container_name: xxx-oods
    logging:
      options:
        max-size: "15m"
        max-file: "30"
    networks:
      - xxx-net
    environment:
      - JWT_ENABLED=true
```

**Comment by pwepwe973** [comment]
* Starting PostgreSQL 14 database server         * Error: /usr/lib/postgresql/14/bin/pg_ctl /usr/lib/postgresql/14/bin/pg_ctl start -D /var/lib/postgresql/14/main -l /var/log/postgresql/postgresql-14-main.log -s -o  -c config_file="/etc/postgresql/14/main/postgresql.conf"  exited with status 1: 
2024-01-06 00:32:00.694 UTC [315] FATAL:  could not load private key file "/etc/ssl/private/ssl-cert-snakeoil.key": SSL error code 2147483661
2024-01-06 00:32:00.694 UTC [315] LOG:  database system is shut down
pg_ctl: could not start server
Examine the log output.

[fail]
 * Starting RabbitMQ Messaging Server rabbitmq-server        
[ OK ]
Starting redis-server: redis-server.
Waiting for connection to the localhost host on port 5432

**Comment by Feriman22** [comment]
I have noticed that PostgreSQL is not running at the moment, so I have to start it manually. I'm using Docker.

`docker exec "$CONTAINER_NAME" service postgresql start`

It solved the issue for me.

**Comment by nook24** [comment]
Had a similar issue. Delete all the docker volumes and restarting the container resolved the issue for me.

**Comment by 23557544** [comment]
add docker startup parameters
`--ulimit nofile=65536:65536`
