### ISSUE TITLE
Does the community edition support distributed cluster installations?

### ISSUE THREAD

**Issue by githublyx** [ONLYOFFICE/Docker-DocumentServer#176]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**

**Comment by ShockwaveNN** [comment]
Sorry, cluster is supported only in paid version

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
