### ISSUE TITLE
RHEL Install Preqs enable AWS repos

### ISSUE THREAD

**Issue by dmc5179** [ONLYOFFICE/Docker-DocumentServer#178]
The RHEL install script install-preq.sh called by install-RedHat.sh contains the following:

yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional

This attempts to enable repos that exist only in AWS.

Remove this line. The build works without it and it looks confusing.

**Comment by ShockwaveNN** [comment]
Could you point me out that `install-preq.sh` you mean?

**Comment by ShockwaveNN** [comment]
> The Dockerfile contains this line:
ARG REPO_URL="deb http://download.onlyoffice.com/repo/debian squeeze main"

Yes

> so I went here: http://download.onlyoffice.com/

Why

I'm not really sure why you look at redhat install script if you wanna use docker version

**Comment by ShockwaveNN** [comment]
@dmc5179 Oh, sorry, I undesrtand you now.
You shold try to use our centos instruction https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

It should for on RHEL, but never tryed on rhel-based docker image

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
