### ISSUE TITLE
this is an amd64 image,can be an arm64 image to be make?

### ISSUE THREAD

**Issue by xiaobing395845388** [ONLYOFFICE/Docker-DocumentServer#179]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**

**Comment by ShockwaveNN** [comment]
Relate to https://github.com/ONLYOFFICE/DocumentServer/issues/152
(Currently no solution)

**Comment by kosssi** [comment]
With Raspberry Pi 4 a lot off person wait it ;)

**Comment by thamvmk** [comment]
I'm also waiting for a web document server on Odroid HC1 :)

**Comment by SunnyXD233** [comment]
With Raspberry pi 4b, waiting ;)

**Comment by igwyd** [comment]
Hello @xiaobing395845388, sorry for the late reply, we have the docker images for the arm64, here the guide https://helpcenter.onlyoffice.com/installation/docs-community-install-docker-arm64.aspx

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
