### ISSUE TITLE
Unable to locate package onlyoffice-documentserver

### ISSUE THREAD

**Issue by xiaobing395845388** [ONLYOFFICE/Docker-DocumentServer#181]
build image error , 'Unable to locate package onlyoffice-documentserver'
when excute  apt-get -yq install onlyoffice-documentserver

**Comment by xiaobing395845388** [comment]
/etc/apt/sources.list.d/onlyoffice.list is empty

**Comment by ShockwaveNN** [comment]
@xiaobing395845388 Hi, did you use Docker image?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
