### ISSUE TITLE
Add verification for `AMQP_SERVER_URL` param

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Docker-DocumentServer#182]
1. Create AmazonMQ broker via https://us-east-1.console.aws.amazon.com/amazon-mq/
2. Start docker container with params:
```
docker run -i -t -e AMQP_SERVER_URL=b-6bc5a892-c174-4fe2-8e5d-a393392176d6-1.mq.us-east-1.amazonaws.com \
                 -e AMQP_SERVER_TYPE=activemq \
                 -e RABBITMQ_SERVER_USER=admin \
                 -e RABBITMQ_SERVER_PASS=pass \
onlyoffice/documentserver-ie
````
cause
```
/app/onlyoffice/run-document-server.sh: line 350: [: !=: unary operator expected

```
![image](https://user-images.githubusercontent.com/668524/65039135-38847680-d95a-11e9-94dc-3ea350967e6c.png)

Tryed other variants, result the same

**DocumentServer Docker tag:** 5.4.0.21

**Host Operating System:** Ubuntu 18.04

**Comment by agolybev** [comment]
`AMQP_SERVER_URL` has the wrong format. See details [here](https://www.rabbitmq.com/uri-spec.html)
I think we have to add `AMQP_SERVER_URL` parameter validation before use it.

**Comment by igwyd** [comment]
New variables work correct, checked like this:
```
AMQP_URI=amqps://login:password@activemq.amazonaws.com:5671
AMQP_TYPE=activemq
```

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
