### ISSUE TITLE
经测试 不支持中文英文 单词自动转行

### ISSUE THREAD

**Issue by ucicno000** [ONLYOFFICE/Docker-DocumentServer#192]
在平常的word/wps中可以设置英文单词断行。在onlyoffice中预览 却不支持！

**Comment by ShockwaveNN** [comment]
Hi, please fill out issue template correctly and use english

**Comment by ucicno000** [comment]
> Hi, please fill out issue template correctly and use English

Thank you. I want to solve the problem that Chinese and English words can't wrap in onlyoffice! We are looking forward to your reply！

**Comment by ucicno000** [comment]
> Hi, please fill out issue template correctly and use English

If you know how to solve it, please contact us by email or phone! Email: ado@txdy.org Tel. + 86 13007801070

**Comment by ShockwaveNN** [comment]
@ucicno000 You still not filled out issue template and attach some examples. If you want personal help - please conact paid support at support@onlyoffice.com

**Comment by ucicno000** [comment]
> @ucicno000 You still not filled out issue template and attach some examples. If you want personal help - please conact paid support at [support@onlyoffice.com](mailto:support@onlyoffice.com)
this is my question :https://blog.csdn.net/ucicno000/article/details/103184205

**Comment by ShockwaveNN** [comment]
@ucicno000 sorry, If you do not want to help me help you (properly, with full details and in English) - I'm not interested in this also

**Comment by ucicno000** [comment]
> @ucicno000 sorry, If you do not want to help me help you (properly, with full details and in English) - I'm not interested in this also

ok ,i'm not good at english. Can you use translation tools to translate Chinese？

**Comment by ucicno000** [comment]
我在onlyoffice world中 使用中文和英文的时候，英文单词不能换行
