### ISSUE TITLE
Docker doesnt work in Ubuntu 18.04

### ISSUE THREAD

**Issue by ejgutierrez74** [ONLYOFFICE/Docker-DocumentServer#195]
Following instructions from official site:
https://helpcenter.onlyoffice.com/es/server/docker/document/docker-installation.aspx

eduardo@eduardo-VirtualBox:~$ docker --version
Docker version 19.03.5, build 633a0ea838
Ubuntu 18.04

I do:  

```
eduardo@eduardo-VirtualBox:~$ sudo docker run -i -t -d -p 80:80 --restart=always \
>     -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
>     -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
>     -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
>     -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver
Unable to find image 'onlyoffice/documentserver:latest' locally
latest: Pulling from onlyoffice/documentserver
f7277927d38a: Pull complete 
8d3eac894db4: Pull complete 
edf72af6d627: Pull complete 
3e4f86211d23: Pull complete 
6ce29fec018b: Pull complete 
88e1e0a2a5a3: Pull complete 
1e6734c06f11: Pull complete 
8c72ce4617ba: Pull complete 
Digest: sha256:94294e0e54efe7204adcb98cd63dccfeebc3c7c7455039f84dd006cc43ae79a1
Status: Downloaded newer image for onlyoffice/documentserver:latest
5a0c3720d578d419035863a0211e59f40a7180f7a3e2f982dd05acfd41a29318
eduardo@eduardo-VirtualBox:~$ sudo docker run -i -t -d -p 443:443 --restart=always \
> -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver
0717c7f50a1b1b89c036b131181e3e1d4e4c6e53d9fa1008f53d02d8bdb1d3bd
eduardo@eduardo-VirtualBox:~$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
onlyoffice/documentserver   latest              4a6b4b24d6de        8 weeks ago         1.8GB
hello-world                 latest              fce289e99eb9        10 months ago       1.84kB
eduardo@eduardo-VirtualBox:~$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED              STATUS              PORTS                          NAMES
0717c7f50a1b        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   About a minute ago   Up About a minute   80/tcp, 0.0.0.0:443->443/tcp   serene_lumiere
5a0c3720d578        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   2 minutes ago        Up 2 minutes        0.0.0.0:80->80/tcp, 443/tcp    condescending_cray

```

And then go to localhost or https://localhost and both are showing:

![imagen](https://user-images.githubusercontent.com/11474846/69656412-c8405280-1078-11ea-82f2-db8a923328e8.png)

Id bet si something wrong with Document Server, as i also try to connect via Instaling in Ubuntu, and though Document Server seems installed and running i cant connect from nextcloud to it.

**Comment by ShockwaveNN** [comment]
@ejgutierrez74 Hi, almost sure something wrong with permission with mounts. Try to look for errors in logs inside container, or remove volumes one by on in `docker run` command to find which is broken

**Comment by ejgutierrez74** [comment]
@ShockwaveNN what permissions are supposed to have ? Because i have all the folders in /home/eduardo/app/onlyoffice/DocumentServer, so i have full acces to write/read.... perhpas assign permissions to www-data ??

**Comment by ShockwaveNN** [comment]
Can't recall exactly, compare permissions with container run without
mounting volumes

**Comment by ejgutierrez74** [comment]
@ShockwaveNN 

I have made little progress... i have updated (pull) new version and i tried to change permissions to www-data and seems to work...
![imagen](https://user-images.githubusercontent.com/11474846/69900386-f2dd2480-1372-11ea-85ea-92a0964aff6d.png)


in port 80 with http, but it doesnt work still in 443 https..

What ive done:
Deleting containers used till now.
Make a pull onlyoffice/documentserver.
Started two contaniers:

eduardo@eduardo-VirtualBox:~$ sudo docker run -i -t -d -p 80:80 --restart=always     -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice      -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data      -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice     -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver
6035bb87aa424ce27fe356f1ff4b9667db119ed31c1a707a6314a1b07b48d403
eduardo@eduardo-VirtualBox:~$ sudo docker run -i -t -d -p 443:443 \
>     -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver
85ccce17c2c241b707019acbf523eb5732370c02be7eb969e9acb1ce5afe17cc

My https:
![imagen](https://user-images.githubusercontent.com/11474846/69900374-b27da680-1372-11ea-9dac-8b4d355fc7f9.png)

My http:
![imagen](https://user-images.githubusercontent.com/11474846/69900379-c45f4980-1372-11ea-8ee3-72b8941d0cea.png)

My log of 443-container:
```
 * Starting PostgreSQL 9.5 database server                               [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                    [ OK ] 
Starting redis-server: redis-server.
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron                              [ OK ] 
 * Starting nginx nginx                                                  [ OK ] 
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx                                   [ OK ] 
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2019-11-30T11:52:08.749] [WARN] nodeJS - update cluster with 1 workers
[2019-11-30T11:52:09.095] [WARN] nodeJS - worker 635 started.
[2019-11-30T11:52:09.096] [WARN] nodeJS - update cluster with 1 workers
[2019-11-30T11:52:28.061] [WARN] nodeJS - update cluster with 1 workers
[2019-11-30T11:52:28.067] [WARN] nodeJS - worker 714 started.
[2019-11-30T11:52:28.067] [WARN] nodeJS - update cluster with 1 workers

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2019-11-30T11:52:09.093] [WARN] nodeJS - worker 634 started.
[2019-11-30T11:52:09.093] [WARN] nodeJS - update cluster with 1 workers
[2019-11-30T11:52:10.066] [WARN] nodeJS - Express server starting...
[2019-11-30T11:52:11.730] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-11-30T11:52:26.796] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-11-30T11:52:26.803] [WARN] nodeJS - update cluster with 1 workers
[2019-11-30T11:52:26.808] [WARN] nodeJS - worker 693 started.
[2019-11-30T11:52:26.808] [WARN] nodeJS - update cluster with 1 workers
[2019-11-30T11:52:27.061] [WARN] nodeJS - Express server starting...
[2019-11-30T11:52:27.670] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

==> /var/log/onlyoffice/documentserver/gc/err.log <==

==> /var/log/onlyoffice/documentserver/gc/out.log <==

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
30 Nov 11:52:06 - [582] reading config file: ../../config/config.js
30 Nov 11:52:06 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
[2019-11-30T11:52:06.920] [WARN] nodeJS - start cluster with 1 workers
[2019-11-30T11:52:06.994] [WARN] nodeJS - worker 616 started.
[2019-11-30T11:52:08.586] [WARN] nodeJS - Express server starting...
[2019-11-30T11:52:08.960] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
```

**Comment by ShockwaveNN** [comment]
@ejgutierrez74 Show content of `/app/onlyoffice/DocumentServer/data` folder, seems nginx don't like certificates. Also look for nginx log for errors

**Comment by ejgutierrez74** [comment]
Data has only one dir inside, certs, with the self-signed certificates...
```
app/onlyoffice/DocumentServer/data/
└── [www-data www-data]  certs
    ├── [www-data www-data]  dhparam.pem
    ├── [www-data www-data]  onlyoffice.crt
    └── [www-data www-data]  onlyoffice.csr
```
Also tried:

`docker exec -it myContainer /var/www/onlyoffice/documentserver/npm/node_modules/.bin/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false'`
with no luck, both containers with nodejs 8.16

Logs are empty.....is this command correct:

`sudo docker run -i -t -d -p 80:80 --restart=always     -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice      -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data      -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice     -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver`

**Comment by ShockwaveNN** [comment]
They should be `onlyoffice.key` and `onlyoffice.crt` file as mention here

**Comment by ejgutierrez74** [comment]
@ShockwaveNN The problem as i guess is with self-signed certificates:

This is how i generated in nextcloud the key, crt and param files ( in UbuntuNC virtual mahcine....the same way i get them for onlyoffice in UbuntuDS virtual machine.

1 -Create files  nextcloud.crt and nextcloud.key  using:
`openssl req -new -x509 -days 365 -nodes -out nextcloud.crt -keyout nextcloud.key,` 


During the generation of the CSR, you will be prompted for several pieces of information. These are the X.509 attributes of the certificate. One of the prompts will be for "Common Name (e.g., YOUR name)". It is important that this field be filled in with the fully qualified domain name of the server to be protected by SSL. If the website to be protected will be https://public.akadia.com, then enter public.akadia.com at this prompt. The command to generate the CSR is as follows:

We want to protect nextcloud.eduardo.com


Is there any solution ??

**Comment by ShockwaveNN** [comment]
@ejgutierrez74 sorry, I'm not qualified enough with certificates to help you. But as far as I remember - there is a lot of troubles with self-signed certificate and I'm not sure it'll work. You should look at LetsEncrtypt if you have valid public certificate for your domain

**Comment by ejgutierrez74** [comment]
Thanks for your response but as Document Server documentation says, should be fixed, because many people can use for educational purposes, and we dont have access to Hosting or cant pay for Certificates. DocumentServer should provide or an easy enable/disable ssl param, or proporcionate clear instruccions that work to generate self signed certificates as here: https://helpcenter.onlyoffice.com/de/server/docker/community/run-using-https.aspx
( specially how to answer the questions to generate the files)


Dont let me be misunderstood, i apreciated your work and effort

Perhaps another team member or people who reads this could help...

Thanks again

**Comment by ShockwaveNN** [comment]
@ejgutierrez74 I may be wrong about self-signed certificate, maybe @agolybev can help

**Comment by ejgutierrez74** [comment]
Just to assure: you know ( perhaps im wrong) that you can connect from nextcloud to onlyoffice document server, without ssl, giving that both sides are insecure right ??

**Comment by ShockwaveNN** [comment]
@ejgutierrez74 yep, if both sides do not use https, only http - connection should be fine

**Comment by ejgutierrez74** [comment]
Thanks, lets wait for @agolybev if it can help ....

**Comment by agolybev** [comment]
Hi @ejgutierrez74, you don't have to run two DS containers to get SSL connection. Just run one and bind it on 80 and 443 ports.
```
$ sudo docker run -i -t -d -p 80:80 -p 443:443\
>     -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver
```

**Comment by ejgutierrez74** [comment]
Thanks...id try....but documentation as i understand says the way i do it....so id have to add more mount points.....like:/app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql

**Comment by SuperSandro2000** [comment]
> Thanks...id try....but documentation as i understand says the way i do it....so id have to add more mount points.....like:/app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql

You can drop them if you don't care about logs, have a https reverse proxy, I forgot, use an external postgres.

**Comment by ejgutierrez74** [comment]
So at least i should add the -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql right ?¿

**Comment by ejgutierrez74** [comment]
If i try:
```
eduardo@eduardo-VirtualBox:~$ sudo systemctl  stop nginx 
eduardo@eduardo-VirtualBox:~$ sudo docker run -i -t -d -p 80:80 -p 443:443 -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver
```
Now http is working like before, and https says error during installation:
https://imgur.com/tlZkbTd

With this log:

```
eduardo@eduardo-VirtualBox:~$ sudo docker logs crazy_burnell 
 * Starting PostgreSQL 9.5 database server                               [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                    [ OK ] 
Starting redis-server: redis-server.
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron                              [ OK ] 
 * Starting nginx nginx                                                  [ OK ] 
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx                                   [ OK ] 
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2019-12-01T09:45:02.589] [WARN] nodeJS - update cluster with 1 workers
[2019-12-01T09:45:16.703] [WARN] nodeJS - update cluster with 1 workers
[2019-12-01T09:45:16.709] [WARN] nodeJS - worker 734 started.
[2019-12-01T09:45:16.709] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:05.848] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:06.022] [WARN] nodeJS - worker 634 started.
[2019-12-03T16:54:06.023] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:22.723] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:22.730] [WARN] nodeJS - worker 714 started.
[2019-12-03T16:54:22.730] [WARN] nodeJS - update cluster with 1 workers

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2019-12-03T16:54:06.024] [WARN] nodeJS - worker 633 started.
[2019-12-03T16:54:06.024] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:06.386] [WARN] nodeJS - Express server starting...
[2019-12-03T16:54:07.225] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-12-03T16:54:21.564] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-12-03T16:54:21.574] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:21.579] [WARN] nodeJS - worker 693 started.
[2019-12-03T16:54:21.579] [WARN] nodeJS - update cluster with 1 workers
[2019-12-03T16:54:21.838] [WARN] nodeJS - Express server starting...
[2019-12-03T16:54:22.372] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

==> /var/log/onlyoffice/documentserver/gc/err.log <==

==> /var/log/onlyoffice/documentserver/gc/out.log <==

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
  gauges: { 'statsd.timestamp_lag': 0 },
  timer_data: {},
  counter_rates: 
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }
3 Dec 16:54:04 - [529] reading config file: ../../config/config.js
3 Dec 16:54:04 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2019/11/24 18:02:18 [error] 742#742: *1 no live upstreams while connecting to upstream, client: 172.17.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://docservice/favicon.ico", host: "onlyoffice.eduardo.com"
2019/11/26 17:06:32 [error] 613#613: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "localhost", referrer: "http://localhost/welcome/"
2019/11/26 17:06:32 [error] 613#613: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "localhost", referrer: "http://localhost/welcome/"
2019/11/26 17:06:32 [error] 613#613: *4 no live upstreams while connecting to upstream, client: 172.17.0.1, server: , request: "GET /welcome/img/favicon.ico HTTP/1.1", upstream: "http://docservice/welcome/img/favicon.ico", host: "localhost"
2019/11/26 17:06:32 [error] 613#613: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /welcome/img/icon-cross.png HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/img/icon-cross.png", host: "localhost", referrer: "http://localhost/welcome/"
2019/11/26 17:06:32 [error] 613#613: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /welcome/img/icon-cross.png HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/img/icon-cross.png", host: "localhost", referrer: "http://localhost/welcome/"
2019/11/26 17:06:42 [error] 613#613: *1 no live upstreams while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://docservice/healthcheck", host: "localhost", referrer: "http://localhost/welcome/"
2019/12/03 16:54:21 [error] 622#622: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "localhost", referrer: "http://localhost/welcome/"
2019/12/03 16:54:21 [error] 622#622: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "localhost", referrer: "http://localhost/welcome/"
2019/12/03 16:54:21 [error] 622#622: *1 no live upstreams while connecting to upstream, client: 172.17.0.1, server: , request: "GET /welcome/img/icon-cross.png HTTP/1.1", upstream: "http://docservice/welcome/img/icon-cross.png", host: "localhost", referrer: "http://localhost/welcome/"

==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
[2019-12-01T09:38:41.939] [WARN] nodeJS - Express server starting...
[2019-12-01T09:38:42.612] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
[2019-12-01T09:45:02.101] [WARN] nodeJS - start cluster with 1 workers
[2019-12-01T09:45:02.107] [WARN] nodeJS - worker 638 started.
[2019-12-01T09:45:02.826] [WARN] nodeJS - Express server starting...
[2019-12-01T09:45:02.887] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
[2019-12-03T16:54:04.999] [WARN] nodeJS - start cluster with 1 workers
[2019-12-03T16:54:05.012] [WARN] nodeJS - worker 614 started.
[2019-12-03T16:54:05.855] [WARN] nodeJS - Express server starting...
[2019-12-03T16:54:05.950] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
```

Perhpaps i shouldn have all this mounted points... @agolybev  @SuperSandro2000 @ShockwaveNN

**Comment by ShockwaveNN** [comment]
@ejgutierrez74 try to drop mount points one by one and find out what the reason of error

**Comment by ejgutierrez74** [comment]
@ShockwaveNN but the dirs are the same that works in port 80, its strange that are working in one port ( 80) and not in the other (443),,,,

Ive tried deleting one by one the mount points, doesnt matter which one i drop, http works, and https says error during installation went wrong, so is something related i assume again with self signed certificates or sssl....

Even the order of @agolybev  
```
sudo docker run -i -t -d -p 80:80 -p 443:443     -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver
the same happens...
```

Any ideas ??

So id prefer solve the problem with these mount points to save logs and data... 

`eduardo@eduardo-VirtualBox:~$ sudo docker run -i -t -d -p 80:80 -p 443:443 -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver`

**Comment by ShockwaveNN** [comment]
Hi, is this problem actual still? I think we made a lot of changes in certificate handling since 2019 and were out of ideas at end of our conversation, but maybe this problem is not actual any more?

**Comment by igwyd** [comment]
Hello @ejgutierrez74, sorry for the late reply. Ubutntu 18.04 no longer support in docker.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
