### ISSUE TITLE
Editing problem

### ISSUE THREAD

**Issue by X-Ryl669** [ONLYOFFICE/Docker-DocumentServer#2]
As soon as I edit a document, I get a message box with an error.
This is exactly as described here: 
http://dev.onlyoffice.org/viewtopic.php?f=3&t=6041

The doc service seems to crash in FontServiceRoute code

**Comment by AnaMih** [comment]
The issue was answered in forum.

**Comment by X-Ryl669** [comment]
Then I'm waiting for your comment in the forum post.
