### ISSUE TITLE
constant CPU load  with rabbitmq child_setup

### ISSUE THREAD

**Issue by unnilennium** [ONLYOFFICE/Docker-DocumentServer#200]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**
docker container use a constant  20% CPU mean  at idle without call for hours.
Docker container htop shows peak with child_setup (user rabbitmq) toping at 100% every 10 seconds or so and closing. leading to a mean CPU usage of 20%.

here the process I was able to catch using watch -n .1 'ps aux | grep child_setup'
rabbitmq 4810 86.0 0.0 4216 360 ? R 01:34 0:00 /usr/lib/erlang/erts-7.3/bin/child_setup false . exec /bin/sh -s unix:cmd 2>&1 3:1048575 26:1 27:0 -

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
install document server on a  centos 7 machine  as vm in a proxomox 6 and observe the CPU rounding at 20% mean.
htop in container and in vm show a variation of activity in the CPU but without being able to see a process (refresh rate not fast enough)
top set at 0.2s allow to see that, 
 watch -n .1 'ps aux | grep child_setup' too

**What is the expected behavior?**
when the docker container is idle withotu any hit to the domain for hours it should use close to 0 CPU.

**Did this work in previous versions of DocumentServer?**
first install

**DocumentServer Docker tag:**
5.4.2.46
**Host Operating System:**
SME server 10 (Centos 7)

**Comment by ShockwaveNN** [comment]
I think this should be fixed by https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/193 and release as next major release

**Comment by unnilennium** [comment]
when will it be available on docker image ?

**Comment by ShockwaveNN** [comment]
@unnilennium With release of 5.5.0, I think it happen during this month, but cannot guarantee

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.
