### ISSUE TITLE
[bug] Always redirects to HOST IP for practically no reason

### ISSUE THREAD

**Issue by Merith-TK** [ONLYOFFICE/Docker-DocumentServer#202]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When i visit `office.example.com`, where i have a reverse proxy pointing to the LAN ip of the docker server `192.168.0.115:80`, it always attempts a 302 Redirect FROM `office.example.com` to `192.168.0.115:80`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) `docker run -i -t -d -p 80:80 onlyoffice/documentserver`
2) reverse proxy port to a URL (clearnet)
3) go to clearnet URL

**What is the expected behavior?**
to beable to access documentserver on `office.merith.tk

**Did this work in previous versions of DocumentServer?**
unknown

**DocumentServer Docker tag:**
unknown?!
**Host Operating System:**
Archlinux

**Comment by ShockwaveNN** [comment]
@agolybev Please take a look

**Comment by Merith-TK** [comment]
the fix i found was by making the reverse proxy "transperant", But the issue still remains as a possible issue.
