### ISSUE TITLE
DocumentServer installed from the snap docker version in a normal user inside the docker group don't finish the installation due to an apparmor issue.

### ISSUE THREAD

**Issue by EchedeyLR** [ONLYOFFICE/Docker-DocumentServer#204]
**Do you want to request a *feature* or report a *bug*?**

I want to report a possible bug.

**What is the current behavior?**

DocumentServer docker version is not installed giving the following output:

> 335ae702559726e44ab177295ef0134dbccd381ebc625a69d49f3dccd3cd2691
> docker: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/sbin/apparmor_parser apparmor_parser --version` failed with output: Failed to load features from '/usr/share/apparmor-features/features': No such file or directory
> 
> error: exit status 1.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Install Debian 10 on raw
* Create a normal user
* Install snap and docker from snap
* Add the normal user to the docker group
* Log in inside the normal user with the docker group
* Execute docker run -i -t -d -p 80:80 --restart=always onlyoffice/documentserver and wait until it finishes.

**What is the expected behavior?**

Finish the installation without issues.

**Did this work in previous versions of DocumentServer?**

No tested.

**DocumentServer Docker tag:**

Version?: the latest on 18/12/2019 at 21:58 UTC

**Host Operating System:**

Debian 10

**Comment by ShockwaveNN** [comment]
Just checked Ubuntu 18.04 with docker from snap and everything working fine.

Did other containers run normally on your system? 
I think it's more general problem related with AppArmour settings, maybe this helps
https://docs.docker.com/engine/security/apparmor/

**Comment by EchedeyLR** [comment]
Thank you for your help, I will check it but for the next time if I test a raw installation in a specific OS I would wait help on the same and not "similar" or "equivalent" taking in account they could have changes in configurations (and they have them) by default.

**Comment by EchedeyLR** [comment]
Checking the output from the user where it is running: 

Running /sbin/apparmor_parser apparmor_parser --version it throws 

> AppArmor parser version 2.13.2
> Copyright (C) 1999-2008 Novell Inc.
> Copyright 2009-2018 Canonical Ltd.
/usr/share/apparmor-features/features file exists without any issue and I can check it from that user.

**Comment by ShockwaveNN** [comment]
@EchedeyLR If you wanna quick help you can always attach virtualbox or other image with your OS in which problem is reproduces

**Comment by EchedeyLR** [comment]
I don't think it is possible in a ADSL2+ connection.

**Comment by ShockwaveNN** [comment]
@EchedeyLR If you provide instruction which you used to `Install Debian 10 on raw` I'll try to reproduce your problem.

P. S. I'm interested in reproducing your problem, but I don't think it's a good idea to point out to people how to do their job

**Comment by EchedeyLR** [comment]
> I don't think it's a good idea to point out to people how to do their job

I recognize this. Sorry for that.

I used the CD-1 to install Debian and in the part related to install desktop and create a normal user I unchecked them.

**Comment by ShockwaveNN** [comment]
@EchedeyLR Any special setup for AppArmour? I'll not able to use real PC to install Debian, but try on VirtualBox

**Comment by EchedeyLR** [comment]
No, I just installed snap after the installation and docker, I forgot to add the "reboot" step between install snap and install docker from it.

**Comment by ShockwaveNN** [comment]
@EchedeyLR I was able to reproduce on `debian-10.1.0-amd64-netinst.iso` image with all updates to 10.2
```
docker: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/sbin/apparmor_parser apparmor_parser --version` failed with output: Failed to load features from '/usr/share/apparmor-features/features': No such file or directory
```

Now we try to figure something out :)

**Comment by ShockwaveNN** [comment]
> Did other containers run normally on your system?

You didn't answer or I missed, but on my system
`docker run hello-world` cause same error, seems this error not related to ONLYOFFICE

**Comment by EchedeyLR** [comment]
Sorry, I didn't and I recognize my fault reporting this here instead of test other container and report it to docker snap.

**Comment by EchedeyLR** [comment]
Anyways, thank you for your help to reproduce the issue and identify it.

**Comment by ShockwaveNN** [comment]
@EchedeyLR you're welcome, if you want I can report issue at snapcraft forums

**Comment by EchedeyLR** [comment]
The issue affects to OnlyOffice too, so of course. 

I already opened a new topic there and I am waiting to know which should I provide. If I need some help with it or they provide any specific information about the issue I will try to post it here.

**Comment by ShockwaveNN** [comment]
@EchedeyLR could you attach link to topic?

**Comment by EchedeyLR** [comment]
Of course I can: https://forum.snapcraft.io/t/docker-containers-not-working-on-debian-10-because-default-profile-is-not-loaded/14731

I just put an extended name to explain the problem a bit and linked the conversation here. I am not sure if I should provide the information for people without visit this one.
