### ISSUE TITLE
Ipfilter rules settings

### ISSUE THREAD

**Issue by udraz** [ONLYOFFICE/Docker-DocumentServer#210]
Hello How I can set the Ipfilter rules through docker 

I want to set something like this
```

"rules": [
    {"address": "mydomain.com", "allowed": true},
    {"address": "*", "allowed": false}
]

```
Is this possible so I can pass environment variable with docker run command

**Comment by ShockwaveNN** [comment]
@udraz Hi, you cannot pass rules as environment variable to DocumentServer docker image
You can mount configured `local.json` file as volume, but I think it'll be overwritten by startup script

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
