### ISSUE TITLE
documentserver-de is not up to date

### ISSUE THREAD

**Issue by L3o-pold** [ONLYOFFICE/Docker-DocumentServer#217]
Last update on docker hub is 2 month old...

**Comment by ShockwaveNN** [comment]
Sam as `onlyoffice/documentserver` image and `onlyoffice/documentserver-ie`
It's current stable version (5.4.2.46)

**Comment by L3o-pold** [comment]
@ShockwaveNN Do you know when is schedule the next update to have latest feature from https://github.com/ONLYOFFICE/server/releases ?

**Comment by ShockwaveNN** [comment]
@L3o-pold I hope we'll release it very soon, in week or two, but cannot guarantee

**Comment by L3o-pold** [comment]
Ok thanks

**Comment by ShockwaveNN** [comment]
@L3o-pold If you wanna try it  - you can use `4testing` versions, like `onlyoffice/4testing-documentserver-ie`, but there may exist some critical issues
