### ISSUE TITLE
PDF not showing properly

### ISSUE THREAD

**Issue by westz36** [ONLYOFFICE/Docker-DocumentServer#218]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Uploaded pdf file to onlyoffice.
Opened browswer, view document.
PDF file fonts all turned to squares. But if i download the file, displays correctly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
upload a file to onlyoffice, open in onlyoffice web interface, bug

**What is the expected behavior?**
showing squares in pdf viewer instead of text

**Did this work in previous versions of DocumentServer?**
dunno

**DocumentServer Docker tag:**
fresh installed
onlyoffice/communityserver:10.5.1.1028
onlyoffice/documentserver:5.4.2.46
mysql:5.7.26 

**Host Operating System:**
ubuntu 18.04

**Comment by ShockwaveNN** [comment]
@westz36 Hi, could you attach such pdf files?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by westz36** [comment]
sorry didnt reply in time. But the bug magically disappeared.
