### ISSUE TITLE
how to use external mysql server?

### ISSUE THREAD

**Issue by twixi** [ONLYOFFICE/Docker-DocumentServer#220]
really use external mysql instead PostgreSQL?

**Comment by ShockwaveNN** [comment]
https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters
`POSTGRESQL_SERVER_*` parameters
I'm not sure, but I think `mysql` should work fine

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
