### ISSUE TITLE
Dockerfile CMD doesn't match ENTRYPOINT

### ISSUE THREAD

**Issue by NorseGaud** [ONLYOFFICE/Docker-DocumentServer#226]
I'm noticing something weird on https://hub.docker.com/r/onlyoffice/documentserver-de/tags.

The dockerfile for the tag is saying `CMD bash -C '/app/onlyoffice/run-document-server.sh';'bash'`, yet, when I look at the digest, it runs `ENTRYPOINT ["/bin/sh" "-c" "/app/ds/run-document-server.sh"]`

Is this a problem?

**Comment by ShockwaveNN** [comment]
This line was changed to `ENTRYPOINT` at https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/d7833f454bfc3cb5067f4ed337483bf1559d0d10

Maybe on hub.docker.com side is some kind of cache and needed to be refreshed?
@agolybev could you take a look?
