### ISSUE TITLE
create_postgresql_tbl grep doesn't work

### ISSUE THREAD

**Issue by NorseGaud** [ONLYOFFICE/Docker-DocumentServer#227]
https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/8e1a52566f6edcb74ff5d458dd27c46e90139277/run-document-server.sh#L245

This line doesn't work. It throws 
```
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```
I've modified it locally to:
`if $PSQL -lt | cut -d\| -f 1 | grep -qw $POSTGRESQL_SERVER_DB_NAME | grep 0; then`
This seems to work just fine.

**Comment by ShockwaveNN** [comment]
Can confirm this issue with this command:
```
docker run -itd -p 80:80 -e POSTGRESQL_SERVER_HOST='x.x.x.x' -e POSTGRESQL_SERVER_PORT=5432 -e POSTGRESQL_SERVER_DB_NAME='db_name' -e POSTGRESQL_SERVER_USER='user_name' -e POSTGRESQL_SERVER_PASS='server_pass' -v /opt/onlyoffice/Data:/var/www/onlyoffice/Data onlyoffice/documentserver
```

And confirm that even so - everything seems fine

**Comment by chendelin1982** [comment]
docker-compose.yml  need to add POSTGRESQL_SERVER_PASS='server_pass'

**Comment by ShockwaveNN** [comment]
@chendelin1982 Agree, since this is unrelated issue - I created a new one
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/234

**Comment by igwyd** [comment]
The issue doesn't repeat, let's close this.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
