### ISSUE TITLE
HTTPS Access Document Server on Windows

### ISSUE THREAD

**Issue by Tumtum2814** [ONLYOFFICE/Docker-DocumentServer#231]
**What is the current behavior?**
Onlyoffice document server should load on HTTPS

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I created a docker container with the document server, using the instruction on the github page. I have tried it both with leaving 443 as the SSL port and by changing the port. Both load ONLYOFFICE Document sertver under HTTPS but when trying to access HTTPS firefox shows the connection gets reset. I've tried accessing it externally(mydomain.net:1234), on a pc on the same network( 192.168.1.XXX:1234) and locally(127.0.0.1:1234) with the same behavior. 
**What is the expected behavior?**
Seeing the Documentserver window show up and run on HTTPS
**Did this work in previous versions of DocumentServer?**
N/A
**DocumentServer Docker tag:**
? funny_clarke
**Host Operating System:**
Windows 10

**Comment by ShockwaveNN** [comment]
Could you change ssl port from 1234 to 443 and see if everything is fine?

**Comment by Tumtum2814** [comment]
i have tried both a custom port and the default ssl port (443) with the same result unfortunately :(

**Comment by ShockwaveNN** [comment]
@Tumtum2814 could you provide `docker run` command for documentserver you using?

**Comment by Tumtum2814** [comment]
@ShockwaveNN sure! `docker run -i -t -d -p 2266:80 -p 443:443 --restart=always onlyoffice/documentserver`

**Comment by ShockwaveNN** [comment]
@Tumtum2814 you should mount certificates inside container at `/var/www/onlyoffice/Data ` as described in instruction [here](https://github.com/ONLYOFFICE/Docker-DocumentServer#running-onlyoffice-document-server-using-https) 
Without certs https connection will not work

**Comment by Tumtum2814** [comment]
@ShockwaveNN does the -v command work on windows 10? Obviously I don't have a /var directory. Do i basically need to grab those certs and install them on windows web services or a windows apache or nginx install?

**Comment by ShockwaveNN** [comment]
@Tumtum2814 sorry, cant help you with windows stuff, I'm not sure if Docker of DocumentServer will work on Windows 10
Maybe @DenisDeeSign know some info

**Comment by Tumtum2814** [comment]
ok, thanks for trying! I'll wait and see if @DenisDeeSign can help out!

**Comment by igwyd** [comment]
Hello @Tumtum2814 , sorry for the late reply. 
You need to copy your tls.crt and tls.key in mounted volumes, for example:
Start container with volumes
```
docker run -i -t -d -p 443:443 --restart=always `
 -v C:\app\onlyoffice\DocumentServer\data:/var/www/onlyoffice/Data onlyoffice/documentserver
```
Create folder with name "certs" in "C:\app\onlyoffice\DocumentServer\data", copy tls.crt and tls.key here (full path C:\app\onlyoffice\DocumentServer\data\certs). Restart container
```
docker restart <container_id>
```
Open https://<your_ip_or_domain_name>

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
