### ISSUE TITLE
Spreadsheet size limit

### ISSUE THREAD

**Issue by Mbarmem** [ONLYOFFICE/Docker-DocumentServer#236]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
File not opening

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open spreadsheet file > 100 MB

**What is the expected behavior?**
File should open

**Did this work in previous versions of DocumentServer?**
No idea

**DocumentServer Docker tag:**
onlyoffice/documentserver

**Host Operating System:**
Debian 10 Docker with Traefik

**Comment by Mbarmem** [comment]
Error is "The filesize exceeds the limitation of your server".

**Comment by ShockwaveNN** [comment]
By default limit for uncompressed xlsx file is 300MB (you can try to extract your file as zip as see how much space it took)

You can find limits in `/etc/onlyoffice/documentserver/default.json` and overwrite them by redefining in `/etc/onlyoffice/documentserver/local.json` file.

**Comment by RadesGhani** [comment]
Any update on this issue? I had similar problem when opening 200MB++ xlsx file. As suggested by @ShockwaveNN 

> 
> 
> By default limit for uncompressed xlsx file is 300MB (you can try to extract your file as zip as see how much space it took)
> 
> You can find limits in `/etc/onlyoffice/documentserver/default.json` and overwrite them by redefining in `/etc/onlyoffice/documentserver/local.json` file.

I extracted my xlsx file and the final size is just around 208MB : 
![image](https://user-images.githubusercontent.com/23325122/99637296-3397e700-2a77-11eb-888b-21949cd8442a.png)

And then here's my local.json configuration for FileConverter : 
![image](https://user-images.githubusercontent.com/23325122/99637405-62ae5880-2a77-11eb-95f0-f460095cdbbf.png)

As shown above my configuration should suffice to open my xlsx file, however the problem persist after I configure it like that and restart the service using "supervisorctl restart all". I'm using the latest docker image of OnlyOffice Document Server integrated with local Nextcloud14 app.

**Comment by ShockwaveNN** [comment]
@RadesGhani I just have a talk with our dev team

There is some things we notice:
1. Judging by screenshot you got encrypted file, in that case `inputLimits` are ignored
2. For encrypted files `maxDownloadBytes` is used. In your case it set to `404857600` seems this should be enough

We think there is maybe some error in ConvertService for your file, not related to size limits.
Could you look at `/var/log/onlyoffice/documentserver/converter/` and see for errors

Also if there is some error I think it's better to create new issue, since this maybe another problem than original one

**Comment by joelchittum** [comment]
@ShockwaveNN has this issue been fixed at this time?  I am having the same issue and updated my default.json to:
 "FileConverter": {
                "converter": {
                        "maxDownloadBytes": 400000000000000000,
                        "downloadTimeout": {
                                "connectionAndInactivity": "10s",
                                "wholeCycle": "2m"
                        },
                        "downloadAttemptMaxCount": 3,
                        "downloadAttemptDelay": 1000,
                        "maxprocesscount": 1,
                        "fontDir": "null",
                        "presentationThemesDir": "null",
                        "x2tPath": "null",
                        "docbuilderPath": "null",
                        "docbuilderAllFontsPath": "null",
                        "args": "",
                        "spawnOptions": {},
                        "errorfiles": "",
                        "streamWriterBufferSize": 8388608,
                        "maxRedeliveredCount": 2,
                        "inputLimits": [
                                {
                                "type": "docx;dotx;docm;dotm",
                                "zip": {
                                        "uncompressed": "50000MB",
                                        "template": "*.xml"
                                }
                                },
                                {
                                "type": "xlsx;xltx;xlsm;xltm",
                                "zip": {
                                        "uncompressed": "300000MB",
                                        "template": "*.xml"
                                }
                                },
                                {
                                "type": "pptx;ppsx;potx;pptm;ppsm;potm",
                                "zip": {
                                        "uncompressed": "50000MB",
                                        "template": "*.xml"
                                }
                                }
                        ]
                }
        },

**Comment by ShockwaveNN** [comment]
> has this issue been fixed at this time

Judging by previos post there was no issue, but configuration problem and since original author of issue didn't have any comments - I'll close this particular issue

@joelchittum I think it's better to create a new issue with your problem, but add detailed description, your OS, product version and scenario in more details

**Comment by serinemsas** [comment]
Hi,
my problem is the same, the log is different to open the file:


[2022-05-12T16:42:24.004] [ERROR] nodeJS - error downloadFile:url=http://localhost:80/Products/Files/HttpHandlers/filehandler.ashx?action=stream&fileid=sbox-37-%7c%7cRELACION+DOCUMENTOS+2021+%23+2.xlsx&stream_auth=390087735768.UONVFXJRTUPJM22L12KATTKIXRSZJCORJJLOQTKHW&X-REWRITER-URL=https%3a%2f%2f192.168.1.248%3a443;attempt=3;code:null;connect:null;(id=DV7HQB8WMmOCLdRW_SBCF940JIo0pcQGTTGgELo_o1k_)
Error: Error response: statusCode:500; headers:{"server":"nginx","date":"Thu, 12 May 2022 21:42:24 GMT","content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-length":"53","connection":"keep-alive","content-disposition":"attachment; filename=\"RELACION DOCUMENTOS 2021 # 2.xlsx\"","x-aspnet-version":"4.0.30319","cache-control":"private","set-cookie":["ASP.NET_SessionId=D2B3FA4FFC2173C60C30A224; path=/; secure; HttpOnly"],"strict-transport-security":"max-age=63072000; includeSubDomains; preload"}; body:
The remote server returned an error: (404) Not Found.
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I don't know what this error message means, the file size is 14.44MB.

thk

**Comment by ShockwaveNN** [comment]
You've already created a new issue here https://github.com/ONLYOFFICE/CommunityServer/issues/374

Seems this is really a problem on CommunityServer side (or problem with your setup), so It's not directly related to original issue
