### ISSUE TITLE
missing license.lic or how to enable community edition

### ISSUE THREAD

**Issue by patzm** [ONLYOFFICE/Docker-DocumentServer#237]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A dockerized documentserver gets accessed by a dockerized nextcloud to open a file. I get this error message
![image](https://user-images.githubusercontent.com/5219726/77862934-f1d3db00-721e-11ea-8aa6-a725f4422063.png)
The logs show that
```
...
document_1  |     at /snapshot/server/build/server/DocService/sources/server.js:0:0
document_1  |     at Generator.next (<anonymous>)
git push --set-upstream origin onlyoffice
document_1  | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
document_1  |     at exports.readLicense.next (<anonymous>)
document_1  |     at readLicense (/snapshot/server/build/server/FileConverter/sources/convertermaster.js:0:0)
document_1  |     at readLicense.next (<anonymous>)
document_1  |     at /snapshot/server/build/server/FileConverter/sources/convertermaster.js:0:0
document_1  |     at Generator.next (<anonymous>)
document_1  |   errno: -2,
document_1  |   syscall: 'open',
document_1  |   code: 'ENOENT',
document_1  |   path: '/var/www/onlyoffice/documentserver/../Data/license.lic' }
...
```
My interpretation: the document server is looking for a `license.lic` file. I don't have one, I want to run the community edition / at home use.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I pushed all my `docker-compose` files to my [dockerfiles repo](https://github.com/patzm/dockerfiles/tree/onlyoffice/). Specifically, this is my [`docker-compose.yml`](https://github.com/patzm/dockerfiles/blob/onlyoffice/onlyoffice/docker-compose.yml) that I used to bring up the ONLYOFFICE document server.

**What is the expected behavior?**
The server detects that there is no license file and falls back to the free tier and disables all premium features.

**Did this work in previous versions of DocumentServer?**
First time user.

**DocumentServer Docker tag:**
Specified in the [`.env` file](https://github.com/patzm/dockerfiles/blob/onlyoffice/onlyoffice/.env): `5.5.0.165`

**Host Operating System:**
QTS 4.4 QNAP, Linux Kernel 4.14.24-qnap
8GB Ram, 4 CPU cores, x86_64 architecture

**Comment by patzm** [comment]
I also tried creating the `license.lic` file. Then I get a
![image](https://user-images.githubusercontent.com/5219726/77863091-13819200-7220-11ea-86ad-d73ee4bcdec7.png)
warning.

**Comment by ShockwaveNN** [comment]
This error in logs about license is ok, this should not harm any functions. We'll fix it in 5.5.1

But this 
![image](https://user-images.githubusercontent.com/668524/77885593-f96fa000-726f-11ea-9abc-604765f1e9d9.png)
Is not right. Could you try to look out DocumentServer logs and nginx logs for some other errors?

**Comment by patzm** [comment]
To be sure, I ran `docker-compose down -v` and `docker-compose up -d` again, effectively wiping the volumes. I could then reproduce the issue. Hence, the logs you will look at are from a fresh "installation" and a single attempt to open a file. The following link is valid for 14 days.
https://transfer.sh/rDSJz/patzm-documenserver-logs.tar.gz

**Comment by ShockwaveNN** [comment]
> Hence, the logs you will look at are from a fresh "installation" and a single attempt to open a file.

I see not a single errorin those logs (except license problem, which is not critical)

So I think problem may be with some traefik options, in which I'm not there good

I could try to setup your whole ecosystem if you explein for how to do it. Or at least parts releated to DocumentServer

**Comment by patzm** [comment]
> So I think problem may be with some traefik options, in which I'm not there good

Ok I see. Sounds reasonable. Regarding reproducing this, that might be quite difficult. The stack looks as follows:
1. traefik reverse proxy v2.2, ACME SSL certificate generation through Let's Encrypt
1. nextcloud, needs to be configured to point to the ONLYOFFICE URL
1. ONLYOFFICE

All stacks are running in :whale: docker containers. Do you have a domain that allows wildcard subdomains? Then I could prepare an example stack for you to reproduce. The other option would be to change all paths to localhost, without SSL encryption and stuff. But maybe things are exactly failing there... Let me know.

**Comment by ShockwaveNN** [comment]
@patzm Yeah, this looks pretty complicated.

My advice is to try 

> The other option would be to change all paths to localhost, without SSL encryption and stuff.

And see if there will be errors. If not - enabling option one by one and see on which it fails.
Also try to scan any other logs, like nextcloud, I'm think there maybe errors.

**Comment by patzm** [comment]
I could get onlyoffice to work in a local, non-SSL fashion. But I didn't learn anything from that.
I don't know how to make the step from non-SSL to SSL _without_ using my domain and _without_ using the reverse proxy. Hence, I tried to google more and look at the logs. Then I found [this](https://termbin.com/e1lr), literaly paste:
```
2020/04/04 21:34:40 [error] 926#926: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.4, server: , request: "GET /5.5.0-165/doc/875794097/c/info?t=1586036080385 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/875794097/c/info", host: "office.patz.app", referrer: "https://office.patz.app/5.5.0-165/web-apps/apps/spreadsheeteditor/main/index_loader.html?_dc=5.5.0-165&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true"
2020/04/04 21:34:40 [error] 926#926: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.4, server: , request: "GET /5.5.0-165/doc/875794097/c/info?t=1586036080385 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/875794097/c/info", host: "office.patz.app", referrer: "https://office.patz.app/5.5.0-165/web-apps/apps/spreadsheeteditor/main/index_loader.html?_dc=5.5.0-165&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true"
2020/04/04 21:34:45 [error] 926#926: *1 no live upstreams while connecting to upstream, client: 172.29.0.4, server: , request: "GET /5.5.0-165/doc/875794097/c/info?t=1586036085406 HTTP/1.1", upstream: "http://docservice/doc/875794097/c/info", host: "office.patz.app", referrer: "https://office.patz.app/5.5.0-165/web-apps/apps/spreadsheeteditor/main/index_loader.html?_dc=5.5.0-165&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true"
2020/04/04 21:34:50 [error] 926#926: *1 no live upstreams while connecting to upstream, client: 172.29.0.4, server: , request: "GET /5.5.0-165/doc/875794097/c/info?t=1586036090408 HTTP/1.1", upstream: "http://docservice/doc/875794097/c/info", host: "office.patz.app", referrer: "https://office.patz.app/5.5.0-165/web-apps/apps/spreadsheeteditor/main/index_loader.html?_dc=5.5.0-165&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true"
```
`172.29.0.4` is my traefik server. So I I think that the document server wants to send stuff back to the nextcloud service, but does not use the original URL (sorry for lack of terminology, I mean https://cloud.patz.app), but the _local_ IP address of the reverse-proxy.

My traefik is currently only set up to forward cloud.patz.app domains to the nextcloud.

I also tried setting the _Server address for internal requests from the Document Editing Service_ to be the public (and routed) URL for nextcloud. However, then opening a file in nextcloud lets the Browser prompt to download the file.
![image](https://user-images.githubusercontent.com/5219726/78462155-bed29100-76cf-11ea-852b-92700894d3ef.png)

Apart from that, I am a bit at loss here. I am not a web-developer. I don't know which tools to use in this case. Any pointers would be great. Maybe in the end I can contribute a example setup that uses Traefik v2.x. All your examples still rely on Traefik v1.x. Between the versions quite substantial changes happend.

**Comment by patzm** [comment]
Ok, finally got it to work! This post showed how to configure Traefik in v2 correctly. Quite some unexpected tweaks and configs one has to set :thinking:.
https://community.containo.us/t/traefik-2-0-and-onlyoffice-not-work-work-correctly-in-v-2/3286/3?u=patzm
