### ISSUE TITLE
Default installation is vulnarable to BEAST attack

### ISSUE THREAD

**Issue by XenonOrion** [ONLYOFFICE/Docker-DocumentServer#239]
As `TLS 1.0` is still supported, the Document Server will be vulnerable to the [Beast Attack](https://blog.qualys.com/ssllabs/2013/09/10/is-beast-still-a-threat).

Is there a reason for the choice to keep TLS 1.0 enabled, can there be an option to disable this?

**Comment by SuperSandro2000** [comment]
While we are at it can we add an option to disable TLS 1.1?

**Comment by igwyd** [comment]
This has been fixed https://github.com/ONLYOFFICE/document-server-package/blob/master/common/documentserver/nginx/ds-ssl.conf.tmpl.m4#L46

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
