### ISSUE TITLE
Limit upload file types

### ISSUE THREAD

**Issue by minhuy58** [ONLYOFFICE/Docker-DocumentServer#24]
Hello,

Is there anyway we can limit the file types upload to community server? I don't want people use these document editors as a cloud storage at company. They flooded the storage with mp3, mp4, zip, iso files... Can we limit those file types?

I am sorry, I am not sure post this under document server or community server page. Please forgive me if I posted wrong place.

**Comment by ibnpetr** [comment]
Hello 
I regret to inform you that there is no way to disable the uploading of a certain type of files.
We will think about adding such limitation.
