### ISSUE TITLE
UPDATE API KEY FOR YANDEX TRANSLATOR SINCE 

### ISSUE THREAD

**Issue by mamiapatrick** [ONLYOFFICE/Docker-DocumentServer#241]
**Do you want to request a *feature* or report a *bug*?**
Features
**What is the current behavior?**
When you open documentserver now and try to use the translator plugin there is no language and the console display an error 403 with the URL https://translate.yandex.net/api/v1.5/tr.json/getLangs?key=trnsl.1.1.20160604T115612Z.107ebb05a7757bcc.804e900f347ddfbeadd7ca5999bd5cb6ca32805b&ui=en 
and when try to open it in a browser the message is {"code":404,"message":"Maximum daily translated text volume exceeded"} and i read that since version 1.5 users have to register to use a free API KEY. I already create a free api key but how to update this in the container
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The languages are available on document server web interfaces
**Did this work in previous versions of DocumentServer?**
I don't know
**DocumentServer Docker tag:**
onlyoffice/documentserver
**Host Operating System:**
Debian OS

**Comment by ShockwaveNN** [comment]
I think you can replace key at /var/www/onlyoffice/documentserver/sdkjs-plugins/translate/translate.js file

**Comment by mamiapatrick** [comment]
Yeah as i'm in k8s environement, i just mount a configmap, in the path 
>  /var/www/onlyoffice/documentserver/sdkjs-plugins/translate/translate.js
  with the content of the whole translate.js file and modify the api-key with a new one get at https://translate.yandex.com/developers/keys . Thanks @ShockwaveNN
