### ISSUE TITLE
add more information, how to adapt docker-compose

### ISSUE THREAD

**Issue by rubo77** [ONLYOFFICE/Docker-DocumentServer#247]
If you install via docker-compose, you have to adapt some variables in the file. please add more instructions, what you have to change and what can stay the default way.

for example, you have to change the database password.

I tried this, set passwords in all lines, that offer passwords,  but now I get the repeating error

     Access denied for user 'onlyoffice_mailserver_user'@'onlyoffice-community-server.nextcloud-onlyoffice_onlyoffice
     Access denied for user 'onlyoffice_user'@'onlyoffice-community-server.nextcloud-onlyoffice_onlyoffice'

**Comment by ShockwaveNN** [comment]
Are you sure this is correct repo for this issue? Not https://github.com/ONLYOFFICE/Docker-CommunityServer/blob/master/docker-compose.yml ?

**Comment by rubo77** [comment]
seems so.

But why are there two identical repositories for this?

**Comment by rubo77** [comment]
https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/88

**Comment by ShockwaveNN** [comment]
>But why are there two identical repositories for this?

What do you mean? ONLYOFFICE CommunityServer and ONLYOFFICE DocumentServer are completly separate products
