### ISSUE TITLE
Not all JWT options changed in local.json when using JWT_ENABLED='true' -e JWT_SECRET='<secretkey>'

### ISSUE THREAD

**Issue by zaggynl** [ONLYOFFICE/Docker-DocumentServer#249]
I ran into the same issue as the person here: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/248#issuecomment-598086418

Issue: 403 after specifying all the right options in nextcloud and for running the onlyoffice container and pressing save in nextcloud for the JWT secret key.

After manually changing the values in the container as described I can press save in Nextcloud after entering the secret.

**Comment by ShockwaveNN** [comment]
> After manually changing the values in the container as described 

There is several examples of values.
Please provide values that worked for you and I'll investigate this issue

**Comment by zaggynl** [comment]
That's a swift reply!

In /etc/onlyoffice/documentserver/local.json I've changed:

      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
(values were false before)
and

     "secret": {
        "inbox": {
          "string": "myactualsecret"
        },
        "outbox": {
          "string": "myactualsecret"
        },
        "session": {
          "string": "myactualsecret"
        }
(values were secret before)

**Comment by ShockwaveNN** [comment]
To be clear:

> (values were false before)

Are you saying if you run with `JWT_ENABLED=true` token.enable.request.* values was false? Seems something wrong.

This is what I got by running `docker run -itd -e JWT_ENABLED='true' -e JWT_SECRET='foo_secret' onlyoffice/documentserver`

![image](https://user-images.githubusercontent.com/668524/82791464-7edd8e00-9e76-11ea-8173-369252adf0fa.png)

Seems everything is ok.
Maybe you used some other options?

**Comment by zaggynl** [comment]
![image](https://user-images.githubusercontent.com/5062119/82839183-d3145c80-9ece-11ea-988d-29776e8f62be.png)
I'm fairly new to docker so I may be missing something.

**Comment by ShockwaveNN** [comment]
docker run enviroment options should be before image name.
Seems `-e JWT_ENABLED='true' -e JWT_SECRET='verymuchsecret'` are just ignored in your case.

Try to change docker run to
```
docker run --restart=always -i -t -d -p 80:80 -e JWT_ENABLED='true' -e JWT_SECRET='verymuchsecret' onlyoffice/documentserver
```

**Comment by zaggynl** [comment]
> docker run enviroment options should be before image name.
> Seems `-e JWT_ENABLED='true' -e JWT_SECRET='verymuchsecret'` are just ignored in your case.
> 
> Try to change docker run to
> 
> ```
> docker run --restart=always -i -t -d -p 80:80 -e JWT_ENABLED='true' -e JWT_SECRET='verymuchsecret' onlyoffice/documentserver
> ```

That did it, thanks!
