### ISSUE TITLE
After changed the container, to save for mirror, problems

### ISSUE THREAD

**Issue by bdxing** [ONLYOFFICE/Docker-DocumentServer#25]
Error info : “Conversion failed.”

**Comment by ibnpetr** [comment]
Hello 

> After changed the container, to save for mirror, problems

We need more information about how the product is configured.
Please provide us with a brief description of the environment.

**Comment by bdxing** [comment]
@ibnpetr I just use the docket commit to save it.

**Comment by bdxing** [comment]
@ibnpetr Add the font and then execute the “ documentserver-generate-allfonts.sh”.

**Comment by ShockwaveNN** [comment]
@bdxing 
Could you specify in more details?
I run this:
```
docker run -itd -p 80:80 onlyoffice/documentserver-integration
docker exec $(docker ps -q) apt-get update
docker exec $(docker ps -q) apt-get -y install fonts-roboto
docker exec $(docker ps -q) documentserver-generate-allfonts.sh
new_image_id=$(docker commit $(docker ps -q))
docker stop $(docker ps -q)
docker run -itd -p 80:80 ${new_image_id}
```
And after that I can create a new document and `roboto` font is present in list of font, I can selet it

**Comment by ShockwaveNN** [comment]
Closing due no response
