### ISSUE TITLE
Wrong permissions for docker image: redis refuses to start

### ISSUE THREAD

**Issue by marcoconstancio** [ONLYOFFICE/Docker-DocumentServer#251]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
redis refuses to start, returns **Waiting for connection to the localhost host on port 5432** error and as a result the document server does not start.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Starting or rebuilding the docker image

**What is the expected behavior?**
Redis server starting normally 

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer version:**
Latest 

**Operating System:**
Debian

**Fix:**
Setting the 644 permission on the **_/etc/hosts_** file

**Comment by ShockwaveNN** [comment]
This is strange, never seen problem like this.
Could you attach full `docker run` command you're using

**Comment by marcoconstancio** [comment]
I'm not using docker on command line, I'm using portainer on my openmediavault instalation. Not sure it helps, but I placed the portainer inspect section of that image in https://pastebin.com/mwTvrUrF

**Comment by ShockwaveNN** [comment]
Try to remove redis mount, seems permissions on host is incorrect

**Comment by marcoconstancio** [comment]
The portainer automatically creates volumes when I don't specify any path to map in my host. 

However I did try to reset/add a few more permissions on the folder where portainer keeps the container data to see if the container receives those permissions, didn't work, it contains the same permissions.

I also checked the permissions of host file on other containers and many have different permissions so I'm not sure why the docker image is different and how to change it.

**Comment by ShockwaveNN** [comment]
> The portainer automatically creates volumes when I don't specify any path to map in my host.

Since we do not guarantee that we work with portainer I not really sure this is problem on our side. 
Are you sure you cannot force portainer not to mount those folders?

I have no experience with portainer, so if anyone are ready to help - welcome

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
