### ISSUE TITLE
Allow to set rejectUnauthorized parameter on default.json

### ISSUE THREAD

**Issue by marcoconstancio** [ONLYOFFICE/Docker-DocumentServer#252]
**Do you want to request a *feature* or report a *bug*?**
feature

Similar to docker env variable JWT_ENABLED, if possible, please add a variable so the the user is able to set the parameter **rejectUnauthorized** in **/etc/onlyoffice/documentserver/default.json** file in order to people to use self sign certificate. This is useful when trying to this kind of certificate with nextcloud.

**Comment by ShockwaveNN** [comment]
@agolybev Please, take a look, could we add one more option

**Comment by marcoconstancio** [comment]
Upon checking the readme, I noticed that that the docker image has the option **USE_UNAUTHORIZED_STORAGE**. Not sure how I missed, but despite not changing the **rejectUnauthorized** variable, it does seem to have the same affect and it worked.

**Comment by ShockwaveNN** [comment]
Missed that too, so if I understand you - your problem is resolved and I'll close this issue.
Feel free to comment if got some troubles regarding this problem
