### ISSUE TITLE
Wrong username on nginx config

### ISSUE THREAD

**Issue by marcoconstancio** [ONLYOFFICE/Docker-DocumentServer#253]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
- error in nginx log file _/var/log/onlyoffice/documentserver/nginx.error.log_ withe the following message  **/var/lib/onlyoffice/documentserver/App_Data/cache/files/conv_check_2128470677_docx/output.docx" failed (13: Permission denied) in ...**
- error displayed on nextcloud **Error when trying to connect (Client error: `GET https://xxx.xxx.xxx.xx/cache/files/conv_check_185074210_docx/output.docx/check_185074210.docx?md5=.....**  when connecting nextcloud with onlyoffice documentserver

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Connecting onyloffice to nextcloud will result in this error.

**What is the expected behavior?**
Connecting onyloffice to nextcloud without error.

**Did this work in previous versions of DocumentServer?**
not sure

**DocumentServer Docker tag:**
Latest

**Host Operating System:**
Debian

**Fix:**
In _/etc/nginx/nginx.conf_ file replace **user www-data;** with **user ds;** since that is the user used to write in the _/var/lib/onlyoffice/documentserver/App_Data/cache/files/_

**Comment by ShockwaveNN** [comment]
@agolybev Please take a look, seems this is leftovers from times we didn't use `ds` user

**Comment by ShockwaveNN** [comment]
We add `www-data` to `ds`
like this `adduser --quiet www-data ds`
https://github.com/ONLYOFFICE/document-server-package/blob/master/deb/debian/postinst.m4#L271 
(private repo), but you can find this `postinst` file on your system

We don't think your problem related this, maybe you got some volumes mapped during `docker run`?

**Comment by marcoconstancio** [comment]
After reading you response, recreated the image without any mapped volumes, worked. Recreated the image with mapped volumes, with the permissions reseted and added a few more permissions and it worked. You were correct, thanks.

**Comment by ShockwaveNN** [comment]
I'll close this issue if it is resolved. Feel free to comment
