### ISSUE TITLE
'Document Server is running' when navigating to address

### ISSUE THREAD

**Issue by pr0letariat** [ONLYOFFICE/Docker-DocumentServer#26]
I installed OnlyOffice using [this](http://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx) guide.

When I start an image and navigate to `127.0.0.1` on port `80` I just get redirected to `http://127.0.0.1/welcome/` with a message saying `'Document Server is running'` with a green tick.

![screenshot at 2017-01-18 12 51 12](https://cloud.githubusercontent.com/assets/14975253/22064774/ee95cdac-dd7c-11e6-93ed-7da5de15e5e7.png)

How do I access the page where I enter my email and password?

**Comment by ibnpetr** [comment]
Hello 
This message means that you installed ONLYOFFICE Document Server and now it is up and running. 
The product can be integrated into your own solution.
Feel free to find more information [here](https://api.onlyoffice.com/editors/basic) 
If you are interested in Community Edition (Document Management, CRM, Projects, Mail, Blogs, etc.) please follow [this link](http://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx) 
Best regards
