### ISSUE TITLE
Why is it trying to connect to localhost when i write a https://domain in the settings?

### ISSUE THREAD

**Issue by Pushergene** [ONLYOFFICE/Docker-DocumentServer#260]
I am running docker-compose example of "fpm insecure" using reverse proxy running with 127.0.0.1:8080:80.

i am running onlyoffice, with port 127.0.0.1:8888:80 but with DIFFERENT! reverse proxy and with different domain. It has Lets encrypt certificate and it is reachable "

lets say the onlyoffice url is :onlyoffice.xyz

Document Server is running".

When i go to settings->onlyoffice, and i type the url, it gives me: Error when trying to connect (cURL error 7: Failed to connect to 127.0.0.1 port 8888:

i have 'allow'local_remote_servers' => true,

'overwrite.cli.url => 'https://mycloud.com' ( ! its not the onlyoffice one, i dont know how i can add multiple overwrite.cli.urls... maybe thats the problem?)

'overwritehost' => 'mycloud.com'

'trusted_proxies' =>

array(

0 => '127.0.0.1',

1 => 'onlyoffice.xyz''

),

'trusted_domains' => array(

0 => 'onlyoffice.xyz'

)

what do i have to do ? i think the issue is that it tries to connect with 127.0.0.1:8888 altough i write onlyoffice.xyz in the Document Editing Service address

**Comment by ShockwaveNN** [comment]
Sorry, didn't get your problem at all, starting with `docker-compose example of "fpm insecure"`

Could you provide some code example of `docker-compose.yml`?

**Comment by Pushergene** [comment]
I solved that issue by using apache instead FPM. I am using OnlyOffice now, i will close it.
