### ISSUE TITLE
Volume error when creating the container

### ISSUE THREAD

**Issue by valentinmne** [ONLYOFFICE/Docker-DocumentServer#261]
I want to create my ownvolume for the docker command but it returns me this when i run the following command :

> sudo docker run -i -t  -p 80:80  \
>     -v /home/edsadmin/onlyoffice/logs/onlyoffice:/var/log/onlyoffice  \
>     -v /home/edsadmin/onlyoffice/data:/var/www/onlyoffice/Data \
>     -v /home/edsadmin/onlyoffice/logs/nginx:/etc/onlyoffice/documentserver/nginx \
>     -v /home/edsadmin/onlyoffice/local:/etc/onlyoffice/documentserver onlyoffice/documentserver

json: error: undefined
json: error: undefined
json: error: undefined
json: error: undefined
json: error: undefined
json: error: undefined
json: error: undefined
/app/ds/run-document-server.sh: line 154: -3: substring expression < 0
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port

The issue is the last volume but i can't understand why

**Did this work in previous versions of DocumentServer?**

Didn't tested

**DocumentServer Docker tag:**

latest

**Host Operating System:**

Centos 7

**Comment by ShockwaveNN** [comment]
I agree that issue with last volume, `-v /home/edsadmin/onlyoffice/local:/etc/onlyoffice/documentserver`
Seems your host path `/home/edsadmin/onlyoffice/local` does not contain all needed file, did you copy content of contaner's `/etc/onlyoffice/documentsever` in your host folder?
There are critical files in this folder

**Comment by valentinmne** [comment]
I'm just trying to copy /etc/onlyoffice/documentserver content on, my host machine and i don't understand why it is not working

**Comment by ShockwaveNN** [comment]
Which command you're used to copy?

**Comment by valentinmne** [comment]
Just doing a volume

**Comment by valentinmne** [comment]
I just want to do a volume to access this particular document : ```/etc/onlyoffice/documentserver/nginx/onlyoffice-documentserver.conf```

**Comment by ShockwaveNN** [comment]
Why not create volume with this single file?

**Comment by valentinmne** [comment]
Because you can't only mount a file you need to mount a whole directory

**Comment by ShockwaveNN** [comment]
> Because you can't only mount a file you need to mount a whole directory

No, I don't think so
`docker run -v full_path/file.ext:/root/file.ext image` 
is correct mount

**Comment by valentinmne** [comment]
When i run : 

```sudo docker run -i -t  -p 80:80  \
    -v /home/edsadmin/onlyoffice/logs/onlyoffice:/var/log/onlyoffice  \
    -v /home/edsadmin/onlyoffice/data:/var/www/onlyoffice/Data \
    -v /home/edsadmin/onlyoffice/logs/nginx:/etc/onlyoffice/documentserver/nginx \
    -v $(pwd)/onlyoffice/local/local.json:/etc/onlyoffice/documentserver/local.json onlyoffice/documentserver ```

I have this error : 

```docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/edsadmin/onlyoffice/local/local.json\\\" to rootfs \\\"/var/lib/docker/overlay2/84194f5591b3e987b93f743e6bf6d670d76daa44ba40a1dcfa80e2fdf233ab8a/merged\\\" at \\\"/var/lib/docker/overlay2/84194f5591b3e987b93f743e6bf6d670d76daa44ba40a1dcfa80e2fdf233ab8a/merged/etc/onlyoffice/documentserver/local.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
ERRO[0000] error waiting for container: context canceled```

**Comment by ShockwaveNN** [comment]
That is output of `$(pwd)/onlyoffice/local/local.json` on your host system? https://stackoverflow.com/a/45985803/820501
Also please add info about docker verison

**Comment by valentinmne** [comment]
Docker version : Docker version 19.03.12, build 48a66213fe

Yes this is the output on my host system.

**Comment by ShockwaveNN** [comment]
> Yes this is the output on my host system.

Are you sure that 
`cat $(pwd)/onlyoffice/local/local.json` output file, not folder?

Anyway this is Docker issue, you should be able to mount single file as volume, if not - you're doing something wrong

**Comment by valentinmne** [comment]
I just want to have the content of : ```/etc/onlyoffice/documentserver/local.json``` On my host machine

**Comment by ShockwaveNN** [comment]
Start simple - does 
`docker run -v $(pwd)/onlyoffice/local/local.json:/root/local.json -d --name test-ubuntu ubuntu:18.04` works?
Does content of your local.json is mounted in container?
`docker exec test-ubuntu cat /root/local.json`

Also since you using $(pwd) in your mount path - please be correct with your path, maybe better use absolute path
If there is not $(pwd)/onlyoffice/local/local.json, docker will create folder with that name

**Comment by valentinmne** [comment]
Same error : 

``` sudo docker run -i -t  -p 80:80  \
>     -v /home/edsadmin/onlyoffice/logs/onlyoffice:/var/log/onlyoffice  \
>     -v /home/edsadmin/onlyoffice/data:/var/www/onlyoffice/Data \
>     -v /home/edsadmin/onlyoffice/logs/nginx:/etc/onlyoffice/documentserver/nginx \
>     -v $(pwd)/onlyoffice/local/local.json:/etc/onlyoffice/documentserver/local.json onlyoffice/documentserver
/app/ds/run-document-server.sh: line 154: -3: substring expression < 0
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
: forward host lookup failed: Unknown server error
Waiting for connection to the  host on port
```

**Comment by ShockwaveNN** [comment]
> Same error :

This is not a result of command (`docker run -v $(pwd)/onlyoffice/local/local.json:/root/local.json -d --name test-ubuntu ubuntu:18.04`) I asked, please read carefully

**Comment by valentinmne** [comment]
It tells me that local.json is a directory :

```sudo docker exec test-ubuntu cat /root/local.json
cat: /root/local.json: Is a directory
```

**Comment by ShockwaveNN** [comment]
This mean `$(pwd)/onlyoffice/local/local.json` is a directory, check your absolute path and fix it, so this is a file.

**Comment by valentinmne** [comment]
I checked and this is a file, it seems to create it as a container on the docker container

**Comment by ShockwaveNN** [comment]
Do you removed $(pwd) and used absolute path? Show me

**Comment by valentinmne** [comment]
With the absolute path : 

```sudo docker run -i -t  -p 80:80  \
>     -v /home/edsadmin/onlyoffice/logs/onlyoffice:/var/log/onlyoffice  \
>     -v /home/edsadmin/onlyoffice/data:/var/www/onlyoffice/Data \
>     -v /home/edsadmin/onlyoffice/logs/nginx:/etc/onlyoffice/documentserver/nginx \
>     -v /home/edsadmin/onlyoffice/local/local.json:/etc/onlyoffice/documentserver/local.json onlyoffice/documentserver

[sudo] password for edsadmin:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/edsadmin/onlyoffice/local/local.json\\\" to rootfs \\\"/var/lib/docker/overlay2/1a9d2b141da2ab3041e4ae3c069c7484aac9ff3fde779318bfc0b44d8fec0a7d/merged\\\" at \\\"/var/lib/docker/overlay2/1a9d2b141da2ab3041e4ae3c069c7484aac9ff3fde779318bfc0b44d8fec0a7d/merged/etc/onlyoffice/documentserver/local.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
ERRO[0000] error waiting for container: context canceled
```

Without the absolute path : 

```sudo docker run -i -t  -p 80:80  \
>     -v /home/edsadmin/onlyoffice/logs/onlyoffice:/var/log/onlyoffice  \
>     -v /home/edsadmin/onlyoffice/data:/var/www/onlyoffice/Data \
>     -v /home/edsadmin/onlyoffice/logs/nginx:/etc/onlyoffice/documentserver/nginx \
>     -v $(pwd)/onlyoffice/local/local.json:/etc/onlyoffice/documentserver/local.json onlyoffice/documentserver
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/edsadmin/onlyoffice/local/local.json\\\" to rootfs \\\"/var/lib/docker/overlay2/e684d61dd0094c64a8eb43c3bae5d2929824443846921852a4737b3e9466baa3/merged\\\" at \\\"/var/lib/docker/overlay2/e684d61dd0094c64a8eb43c3bae5d2929824443846921852a4737b3e9466baa3/merged/etc/onlyoffice/documentserver/local.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

**Comment by ShockwaveNN** [comment]
That is output of 
```
tree /home/edsadmin/onlyoffice/local
```

**Comment by valentinmne** [comment]
tree /home/edsadmin/onlyoffice/local
/home/edsadmin/onlyoffice/local
├── local.json
└── onlyoffice
    └── local
        └── local.json

**Comment by ShockwaveNN** [comment]
There two entries for `local.json`

Seems you got `local.json` as file and `local.json` as folder. This is why docker mount folder, remove folder

**Comment by valentinmne** [comment]
Sory it was the wrong one.

tree onlyoffice
onlyoffice
├── data
├── local
│   └── local.json
└── logs
    ├── nginx
    └── onlyoffice

**Comment by ShockwaveNN** [comment]
You giving me different info each post and I 99% sure this issue is not related to DocumentServer itself, but with Docker in general in you setup, since as you said here https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/261#issuecomment-651608025 simple command with ubuntu:18.04 container not work, you should figure out it first

**Comment by valentinmne** [comment]
Okay, I tell you if I find somthing, for the moment I close the ticket 

Have a nice day. :)
