### ISSUE TITLE
I can't find the path /etc/onlyoffice/documentserver/ !

### ISSUE THREAD

**Issue by FEliuze** [ONLYOFFICE/Docker-DocumentServer#266]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**

**Comment by ShockwaveNN** [comment]
Are you looking for this file inside container? It's should be there

Should your `docker run` command and how you `trying to find the path`

**Comment by FEliuze** [comment]
The install-command is "sudo docker pull onlyoffice/documentserver"
and the run-command is "sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver",
so where is the default.json? 
Can I take some params in my run-command to set it?

**Comment by ShockwaveNN** [comment]
You can set some params via env variables
https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters

And default.json should be inisde container

```
docker exec containerId cat /etc/onlyoffice/documentserver/default.json
```

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
