### ISSUE TITLE
"Download As" error

### ISSUE THREAD

**Issue by mdelerue** [ONLYOFFICE/Docker-DocumentServer#27]
Hi,

I created a docker image for Only Office.
Here is the Dockerfile : 
```
FROM onlyoffice/documentserver:latest
COPY ./default.json /etc/onlyoffice/documentserver/default.json
```

The problem is that I get an error when I try to download any document by clicking "Download As". The server send a HTTP 400 error.

I just modified the default.json by adding secret string and enabling token : 
```
"secret": {
        "inbox": {
          "string": "ABCDEFGHJ",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "ABCDEFGHJ",
          "file": ""
        },
        "session": {
          "string": "ABCDEFGHJ",
          "file": ""
        }
      },
      "token": {
        "enable": {
          "browser": true,
          "request": {
            "inbox": true,
            "outbox": true
          }
        },
        "inbox": {
          "header": "Authorization",
          "prefix": "Bearer "
        },
        "outbox": {
          "header": "Authorization",
          "prefix": "Bearer ",
          "algorithm": "HS256",
          "expires": "5m"
        },
        "session": {
          "algorithm": "HS256",
          "expires": "5m"
        }
      }
```

The weird part is that if I set `token.enable.browser`, `token.enable.request.inbox` and `token.enable.request.outbox` to `false` everything is ok and I can download files.

If somebody had a clue, it would be great.

Thank you.
Marc

**Comment by JohnPerkin** [comment]
Hello!
Please check if there is a field 'permissions' in the object for signature. Send to us the field 'Payload' and logs from the mapped folder.

**Comment by mdelerue** [comment]
Hi, I need to apologize : 
The token generation was wrong in our code and the payload was empty.
Fixing the token solve the download bug.

Thank you for everything.
Marc
