### ISSUE TITLE
Incorrect "changesurl" inside docker container

### ISSUE THREAD

**Issue by green-ghost** [ONLYOFFICE/Docker-DocumentServer#275]
Is there possible to change external url for onlyoffice document server?
I have seafile storage on host machine and onlyoffice document server (CE) inside docker container. Onlyoffice container has external url proxied by nginx (like https://ds.domain.com).
If I trying to save document, I have the following error in out.log:
```
Error: Error response: statusCode:500 ;body:
<...>
[ERROR] nodeJS - sendServerRequest error: <...>;url = https://store.domain.com/onlyoffice/editor-callback/;data = {"key":"19dfa3b04b95e06f2e58","status":2,"url":"**http://docservice**/cache/files/19dfa3b04b95e06f2e58_454/output.docx/output.docx?md5=fWRBqfaHLK1JoDCJi6L22A&expires=1596526666&disposition=attachment&filename=output.docx","changesurl":"http://docservice/cache/files/19dfa3b04b95e06f2e58_454/changes.zip/changes.zip?md5=YFbwsP84LHkO1c_2siA0Fg&expires=1596526666&disposition=attachment&filename=changes.zip"
```
Where "dockservice" is the name of the service inside docker-compose file.
May be exist some config property to change the url for document server?

OS: Linux Debian 
Docker image onlyoffice/documentserver:latest

**Comment by ShockwaveNN** [comment]
Hi
No I don't think there is a setting to change that

You can try to change it it `/etc/nginx/includes/ds-docservice.conf` file inside container, but never tried it and can cause major troubles

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by aoberest** [comment]
@green-ghost Hello,
I have a similar error. Have you found a solution?
