### ISSUE TITLE
Sensible default for NGINX_WORKER_CONNECTIONS

### ISSUE THREAD

**Issue by kykc** [ONLYOFFICE/Docker-DocumentServer#28]
Regarding nginx worker connections limit, as defined [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh#L25):

Querying ulimit from inside the container:
```
root@abc201f5e274:/# ulimit -n
1048576
```

I don't think it's rather sensible default value, as it greatly affects memory footprint: on 8-thread processor I got 8 workers each consuming 404MiB of RES memory for nginx alone, which is quite excessive IMO.

In any case, I think it's a good thing to mention that this option greatly affects memory consumption of the container in ``README.md``

### Update

Can't find info about ``docker run`` behavior when ``--ulimit`` is not present, but seems that ``docker`` sets such ulimit inside all containers on my host for some reason.  On the host itself ulimit has pretty usual value:
```
kykc@yes:~$ ulimit -n
1024
```

**Comment by ShockwaveNN** [comment]
You can use env variables:
NGINX_WORKER_PROCESSES - to set nginx worker process
NGINX_WORKER_CONNECTIONS - to set max connetion for each worker
Also you can change ulimit by docker `--ulimit` key - see https://docs.docker.com/engine/reference/commandline/run/#/set-ulimits-in-container---ulimit
We will add info about that in manuals, thanks.

**Comment by agolybev** [comment]
Added nginx params description. See [Available Configuration Parameters](https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters) section for details.
