### ISSUE TITLE
Add option to disable CPU-heavy tasks on startup

### ISSUE THREAD

**Issue by jkumeboshi** [ONLYOFFICE/Docker-DocumentServer#281]
Docker entrypoint  /app/ds/run-document-server.sh calls the following script:
/usr/bin/documentserver-generate-allfonts.sh

that script calls 2 heavy tasks:
allfontsgen (about 5 minutes on my slow VM)
allthemesgen (about 20 minutes on my slow VM)

(question: Can the Document server be used while that tasks are running in background?)

Are that tasks really required to run at **each** startup?
Would it be possible to disable it in some way, such as using environment variables o startup switches?
I think that they shall be run just once and re-run again only if the themes or the fonts are updated (so, only if I update the docker image).

**Comment by ShockwaveNN** [comment]
@jkumeboshi Hi, yeah, I agree with you

@agolybev can we add option to Docker envs to disable those task on startup?

**Comment by teacupx** [comment]
+1 for adding the option to disable the task on startup
