### ISSUE TITLE
Allow turning off TLS verification from env variable

### ISSUE THREAD

**Issue by SleepingShell** [ONLYOFFICE/Docker-DocumentServer#290]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
You must edit the /etc/onlyoffice/documentserver/default.json to set rejectUnauthorized, however editing this file does not do anything when the server is already running as a container. 

**What is the expected behavior?**
Have an environment variable that can set 'rejectUnauthorized' to false before the document server is actually started.

**Did this work in previous versions of DocumentServer?**
No, this has been discussed in #96 . The suggested workaround on that issue is to rebuild the docker image every update with the edited file, but that is not very feasible.

**Comment by ShockwaveNN** [comment]
Hi

> The suggested workaround on that issue is to rebuild the docker image every update with the edited file

I may be wrong, but rebuilding of image every update is not needed if used like I described here
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/96#issuecomment-506295760

But in general - I agree, specific option for this would be great. @agolybev any thoughts?

**Comment by SleepingShell** [comment]
> Hi
> 
> > The suggested workaround on that issue is to rebuild the docker image every update with the edited file
> 
> I may be wrong, but rebuilding of image every update is not needed if used like I described here
> [#96 (comment)](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/96#issuecomment-506295760)
> 
> But in general - I agree, specific option for this would be great. @agolybev any thoughts?

You're right I didn't try that solution due to the one person saying it didn't work, but it I can confirm that solution works. Although it is definitely hacky.

**Comment by igwyd** [comment]
Hello @SleepingShell, sorry for the late reply. It's implemented ```USE_UNAUTHORIZED_STORAGE=true``` https://github.com/ONLYOFFICE/Docker-DocumentServer?tab=readme-ov-file#available-configuration-parameters

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
