### ISSUE TITLE
docker-compose missing Dockerfile

### ISSUE THREAD

**Issue by Schnuecks** [ONLYOFFICE/Docker-DocumentServer#298]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
docker-compose up exiting with ERROR: Cannot locate specified Dockerfile: Dockerfile

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just run docker-compose up -d

**What is the expected behavior?**
that the containers start normal 

**Did this work in previous versions of DocumentServer?**
haven't had before

**DocumentServer Docker tag:**

**Host Operating System:**
OS: CentOS 7.8.2003
Docker:  19.03.13
Compose:  1.27.4

**Comment by ShockwaveNN** [comment]
@Schnuecks Hi, Dockerfile is [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml)

And I just checked via `docker-compose up -d` command - there is no error, are you sure you use correct working directory to run it?

**Comment by Schnuecks** [comment]
Hi, the instruction says wget compose.yml and dc Up not clone the repo. i will try this.

**Comment by ShockwaveNN** [comment]
> instruction says wget compose.yml

Could you point out which instruction?

**Comment by Schnuecks** [comment]
Or, use docker-compose. For the mail server correct work you need to specify its hostname 'yourdomain.com'. Assuming you have docker-compose installed, execute the following command:

​wget https://raw.githubusercontent.com/ONLYOFFICE/Docker-CommunityServer/master/docker-compose.yml
docker-compose up -d.

Installing ONLYOFFICE Document Server integrated with Community and Mail Servers

**Comment by ShockwaveNN** [comment]
This is instruction part for setting up `ONLYOFFICE CommunityServer`, and should work fine if you want to setup CommunityServer.

But for me your error seems that your trying to call `Setup CommunityServer` command on `docker-compose` file of DocumentServer, document server could not be setup just via wget it compose file

**Comment by Schnuecks** [comment]
Thanks for pointing out, i have used the DocumentServer compose not the CommunityServer compose
