### ISSUE TITLE
toolbar icons not displayed

### ISSUE THREAD

**Issue by ferdiga** [ONLYOFFICE/Docker-DocumentServer#302]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
toolbar icons not displayed for sheets 
![image](https://user-images.githubusercontent.com/6248560/96432114-b7567d80-1204-11eb-84e7-b95badf84f38.png)
and for  text
![image](https://user-images.githubusercontent.com/6248560/96432227-e40a9500-1204-11eb-8733-5e39d4af6c74.png)

hovering over the icons displays the correct text
I have already seen the icons, but after opening a few documents the icons are not displayed any more.
BTW - 

- I have reinstalled the server after docker system prune. didn't help
- same behavior on chrome, chromium on ubuntu 2004 and apple
- same behavior on firefox on ubuntu

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open ods, xlsx document
**What is the expected behavior?**
display icons 
**Did this work in previous versions of DocumentServer?**
my first install
**DocumentServer Docker tag:**
6.0.0.105
**Host Operating System:**
debian 9

**Comment by ShockwaveNN** [comment]
We got similar issue but never found reas reason as far as I remember 

https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/125

Did you by any chancse use Apache ModPagespeed? 

If not could you attach full `docker run` command?

**Comment by ferdiga** [comment]
ModPagespeed Off
did the trick 
works now
thanks

**Comment by ShockwaveNN** [comment]
Good to hear. In that case I'll close it )

**Comment by ferdiga** [comment]
may be this incompatibility should be mentioned in the installation docs

**Comment by ShockwaveNN** [comment]
@ferdiga Sorry, I don't think so, we can get a pretty long list if we list any option in any software (for example we even didn't use apache by default for DocumentServer) that can be used with DocumentServer

I think issue is the best way to track this situation and this is second time anyone mention this problem for years, if there is plenty of users - in that case I think we will
