### ISSUE TITLE
No connection from Nextcloud to Document Server in Version 6.0.0.105

### ISSUE THREAD

**Issue by ttjaden** [ONLYOFFICE/Docker-DocumentServer#303]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
It's not possible to open files from nextcloud, see 
(from Firefox):
![grafik](https://user-images.githubusercontent.com/16917049/96708464-91aead00-1399-11eb-8e56-a8446595d422.png)
(from chrome)
![grafik](https://user-images.githubusercontent.com/16917049/96708618-c3277880-1399-11eb-8a6e-4ff37c5018ad.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Server 1:
Ubuntu 18.04 LTS
Nextcloud 19 with Onlyoffice 6.1.0

Server 2:
Ubuntu 18.04 LTS
Onlyoffice installed as Docker via opensource-install.sh and updated with workspace-install.sh
communityserver:11.0.0.1458
documentserver:6.0.0.105

**What is the expected behavior?**
I expect the Editor to show up

**Did this work in previous versions of DocumentServer?**
- Before updating the documentserver to version 6.0.0.105 everything worked fine!
- Settings within Nextcloud say, that everything works with Service URL: https://office.*********.de/ds-vpath/
![grafik](https://user-images.githubusercontent.com/16917049/96708972-4cd74600-139a-11eb-98f0-cff9070ff262.png)
- DocumentServer works perfect from within onlyoffice Community Portal

**Comment by ShockwaveNN** [comment]
Hi, sorry for late response, seems I missed your issue

Since I don't understand your language at all I have no idea that are the errors you getting

If this problem still actual could you provide logs of documentserver? They're inside container in `/var/log/onlyoffice` path

**Comment by ttjaden** [comment]
With Nextcloud 21 on Server 1 and another documentserver which doesn't belong to community server on Server 2, the problems are gone! Sorry for not closing this issue!

**Comment by ShockwaveNN** [comment]
Glad your issue is resolved
