### ISSUE TITLE
Missing help langages in RPM package

### ISSUE THREAD

**Issue by durandx** [ONLYOFFICE/Docker-DocumentServer#31]
The latest RPM binary onlyoffice-documentserver.x86_64.rpm only conains help langage for en and ru.

The following langage are missing for help pages (```\var\www\onlyoffice\documentserver\web-apps\apps\documenteditor\main\resources\help\```):
```
de, es, it, fr
```

Do we need to install extra langages packages ?

FYI, those langages are correctly bundled in ```\var\www\onlyoffice\documentserver\web-apps\apps\documenteditor\main\locale\```

**Comment by agolybev** [comment]
Hi durandx. Thank you for your interest for ONLYOFFICE DocumentServer.
There are no mistakes. 
The folder `\var\www\onlyoffice\documentserver\web-apps\apps\documenteditor\main\locale\` contains localized resources for document editor interface, the folder `\var\www\onlyoffice\documentserver\web-apps\apps\documenteditor\main\resources\help\` contains the localized help pages only for the English and Russian language.
P.S. Bugs and suggestions related to the ONLYOFFICE Document Server, but not related to the docker container, please send to [DocumentServer issue tracker](https://github.com/ONLYOFFICE/DocumentServer/issues)
