### ISSUE TITLE
OnlyOffice server test for Moodle

### ISSUE THREAD

**Issue by makgab** [ONLYOFFICE/Docker-DocumentServer#312]
Hi!
We have a CentOS8 server with Moodle 3.8.3. We would like to use the onlyoffice server to convert documents for view.
I installed the docker document server in centos:
`sudo podman run -i -t -d -p 82:80 \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v /app/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq \
    -v /app/onlyoffice/DocumentServer/redis:/var/lib/redis \
    -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver`

It is running in browser accessible:  http://localhost:82
See attachement.
How can I test the document server? Because Moodle can't use it with these plugins:
https://github.com/logicexpertise/moodle-mod_onlyoffice
https://github.com/learnweb/moodle-fileconverter_onlyoffice

![onlyoffice-welcome](https://user-images.githubusercontent.com/4254493/99566309-068efa00-29cd-11eb-817c-239897e8abcc.png)

**Comment by ShockwaveNN** [comment]
> How can I test the document server?

You can start text example via command shown on screenshot, go to `http://localhost:82/example` and see if DocumentServer works.

This is steps to test DocumentServer itself, I have no experience with Moodle at all, so I cannot help with integration.
I can move you issue to https://github.com/ONLYOFFICE/onlyoffice-moodle, maybe someone from this repo can help you

**Comment by makgab** [comment]
> You can start text example via command shown on screenshot, go to `http://localhost:82/example` and see if DocumentServer works.
> 

The examples is needed to install. :)
`podman exec <container_id> sudo supervisorctl start ds:example`

Then it is accessible: http://localhost:82/example

But when I created a document the server sent back message "...can't save it".  :o

**Comment by ShockwaveNN** [comment]
> But if I created a document then the server sent back message "...can't save it". :o

Try to open it no via `http://localhost:82`, but with `http://server_ip:82`

**Comment by makgab** [comment]
thanks, ok!
I saw in video that we can manage users. But the page "Startup.aspx" does not exists. (I think it was the url.)
http://server.name/Startup.aspx
(http://server.name/Default.aspx)

`Cannot GET /Startup.aspx`

**Comment by ShockwaveNN** [comment]
@makgab That is the video? This may be urls of `ONLYOFFICE CommunityServer`, another product, but not sure they use exact those url

I have no expirience with Moodle itself, maybe it's Moodle's urls?

But I'm 100% sure that those urls are not from DocumentServer

**Comment by makgab** [comment]
It was the video: https://helpcenter.onlyoffice.com/video/install-docker.aspx

**Comment by makgab** [comment]
Hi!
I see it is working with Moodle... but I don't know which plugin with. :)
https://github.com/learnweb/moodle-fileconverter_onlyoffice
https://github.com/logicexpertise/moodle-mod_onlyoffice

But we have a tiny problem. We can view those documents which were uploaded from today! :o
We cannot view the documents which were uploaded yesterday and before.
What may be the reason?

**Comment by ShockwaveNN** [comment]
> It was the video: https://helpcenter.onlyoffice.com/video/install-docker.aspx

This video is installing ONLYOFFICE CommunityServer as additional soft, I don't think this is variant for you

> I see it is working with Moodle... but I don't know which plugin with. :)
> https://github.com/learnweb/moodle-fileconverter_onlyoffice
> https://github.com/logicexpertise/moodle-mod_onlyoffice

Both of those plugins are developed not by us, onlyoffice team, but some other developers, you should contact them

There is our variant, https://github.com/ONLYOFFICE/onlyoffice-moodle, but I don't know if it's in working condition, you should create issue there if you got troubles.

This repo, ONLYOFFICE/Docker-DocumentServer is for troubles with starting documentserver itself, and if you got no troubles with starting DocumentServer, but troubles it integrating with moodle - you should create new issue at integration repo you're using

**Comment by makgab** [comment]
> 
> There is our variant, https://github.com/ONLYOFFICE/onlyoffice-moodle, but I don't know if it's in working condition, you should create issue there if you got troubles.
> 
> 

It is not for us.
Thanks!
