### ISSUE TITLE
Opening Big Spreadsheet File Return Error : "The filesize exceeds the limitation of your server"

### ISSUE THREAD

**Issue by RadesGhani** [ONLYOFFICE/Docker-DocumentServer#313]
**Do you want to request a *feature* or report a *bug*?**
Might be a bug.

**What is the current behavior?**
Opening encrypted spreadsheet file (xlsx) over the size of 200MB++ return Error : "The filesize exceeds the limitation of your server. ". When opening another encrypted spreadsheet file of smaller size, it works normally.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here's my server environment :

- OnlyOffice Document Server docker container, latest version (Tag : Latest)

- *Nextcloud13 running on different machine & port, already integrated with aforementioned OnlyOffice.

And here's the steps to reproduce it :

1. Upload an encrypted xlsx file of over 200MB into *Nextcloud13. 
2. Open it from *Nextcloud13, it will be redirected to OnlyOffice service.
3. A pop up window will appear : 
![image](https://user-images.githubusercontent.com/23325122/99747457-20cff180-2b0d-11eb-88d7-b99481a8a75a.png)

**What is the expected behavior?**
A pop up window asking for password should appear like this :
![image](https://user-images.githubusercontent.com/23325122/99749197-95585f80-2b10-11eb-8b8f-f9f01ee6742e.png)

**Did this work in previous versions of DocumentServer?**
It didn't.

**DocumentServer Docker tag:**
Latest, pulled yesterday (2020Y/11M/19D)

**Host Operating System:**
Centos7

**What I already tried to do**
This issue is a continuation of this issue comment : https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/236#issuecomment-730198275 . As suggested by @ShockwaveNN I created a new issue here.

Finally here's my log file on /var/log/onlyoffice/documentserver/converter/
![image](https://user-images.githubusercontent.com/23325122/99747424-131a6c00-2b0d-11eb-86c3-efe55c10d8ea.png)

Also it seems after I edited /etc/onlyoffice/documentserver/local.json file as posted in https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/236#issuecomment-730198275 OnlyOffice failed to open any files. Before local.json file edited it works for smaller (normal sized) document files. Before edited, local.json contents is default from docker image. 

Here's the error for smaller file now : 
![image](https://user-images.githubusercontent.com/23325122/99749334-e2d4cc80-2b10-11eb-9e77-4e2d6defe9a6.png)

The updated log file (/var/log/onlyoffice/documentserver/converter/) (after the error above) :
![image](https://user-images.githubusercontent.com/23325122/99749589-67bfe600-2b11-11eb-9193-3a28f4ace243.png)

*edited

**Comment by RadesGhani** [comment]
Here's  my pastebin of  /etc/onlyoffice/documentserver/local.json :
https://pastebin.com/WTyu8ibB
and /var/log/onlyoffice/documentserver/converter/out.log :
https://pastebin.com/36JxWk3H

**Comment by ShockwaveNN** [comment]
> Also it seems after I edited /etc/onlyoffice/documentserver/local.json file as posted in #236 (comment) OnlyOffice failed to open any files. Before local.json file edited it works for smaller (normal sized) document files. Before edited, local.json contents is default from docker image.

To be clear - is error 

```
Error response: content length: 221586944
```

Is this error appears even on default config?
If so I think this may be trouble not on DocumentServer side, but on integration side and DocumentServer cannot download this file correctly

Could you attach this file? Without pasword, it's ok
Or for example remove all sensitive information from this file, by replacing it with some junk

**Comment by RadesGhani** [comment]
> Is this error appears even on default config?
If so I think this may be trouble not on DocumentServer side, but on integration side and DocumentServer cannot download this file correctly

Yes, that error appeared even on default config when opening the aforementioned xlsx. 

> Could you attach this file? Without pasword, it's ok

Unfortunately I didn't have the password myself since my task is simply to investigate the cause of the problem and that file is just a sample (in which if the password pop up displayed correctly it's assumed to be working correctly). However I will try to ask my supervisor for the password. I will get back to you soon, thankyou very much for your assitance.

**Comment by ShockwaveNN** [comment]
> Unfortunately I didn't have the password myself since

To be clear, I don't need a password, I need just file to test if it's problem in DocumentServer or in nextcloud connector

**Comment by RadesGhani** [comment]
> 
> 
> > Unfortunately I didn't have the password myself since
> 
> To be clear, I don't need a password, I need just file to test if it's problem in DocumentServer or in nextcloud connector

So would the file alone suffice? In that case I will upload it somewhere.

**Comment by ShockwaveNN** [comment]
Yes, for now file alone is enough

**Comment by RadesGhani** [comment]
Try this
https://chanthel.solusi247.com/index.php/s/YHFJ22DNwftNBYF

**Comment by ShockwaveNN** [comment]
@RadesGhani Thanks, I've downloaded this file, I'll come back as soon as I figure out that is wrong

**Comment by ShockwaveNN** [comment]
I was able to get password promt page, using only integrated test example

My steps are:
1. Run DocumentServer `docker run -itd -p 80:80 onlyoffice/documentserver`
2. Start test example `docker exec -it 6f246e7951e2 supervisorctl start all`
3. go to `/example` and upload your file
Got `Upload error`, in Browser console there is
 `/example/upload?:1 Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`
Seems this is nginx error.
I edited `/etc/nginx/includes/ds-common.conf` by changing to `client_max_body_size 400M;` to http section and `service nginx restart`
Changed default upload size in test example via editing 
and adding `server:maxFileSize` with value 4073741821 and restarting it via `supervisorctl restart all` 
File uploaded. So far so good.
3. Now it give me error via DocumentServer editors interface, that size too mush
Setting `"maxDownloadBytes": 504857600` in `/etc/onlyoffice/documentserver/default.json` and restarting once again and got password promt
![image](https://user-images.githubusercontent.com/668524/99798839-bcc82000-2b42-11eb-980f-459d1ff777b8.png)

On some stages I saw 
```
[2020-11-20T12:06:14.951] [ERROR] nodeJS - error downloadFile:url=http://192.168.1.238/example/files/192.168.1.238/tdirect%20phase%205%20(q3)%20-%20uat%20(mobile%20android)%20v1.0.xlsx;attempt=1;code:EMSGSIZE;connect:null;(id=-1160365541)
```

Error in logs, so check you nginx settings for `client_max_body_size`, seems this file just too large to be uploaded with default nginx settings

**Comment by RadesGhani** [comment]
Sorry for the late reply, I have tried the steps above. However I might get this one wrong 

> Changed default upload size in test example via editing
and adding `server:maxFileSize` with value 4073741821 and restarting it via `supervisorctl restart all`

Which file should I change? I tried to add it on `default.json` as folows :
![image](https://user-images.githubusercontent.com/23325122/99932817-cbedde80-2d8b-11eb-8aa1-153830badece.png)


and proceed to do all the steps, unfortunately this is as far as I can get :
![image](https://user-images.githubusercontent.com/23325122/99931778-72d07b80-2d88-11eb-9b76-486a2d58d2c6.png)

I checked the log file `var/log/onlyoffice/documentserver/nginx.error.log`, it does show an error albeit a little different than yours : 

> 2020/11/23 03:45:51 [error] 5626#5626: *49 client intended to send too large body: 221587270 bytes, client: 192.168.1.201, server: , request: "POST /example/upload? HTTP/1.1", host: "192.168.1.204:1380", referrer: "http://192.168.1.204:1380/example/"


The error appeared before I try the steps though, after that no error logged on that file but I still get the error on browser. I checked the browser console when uploading too but nothing written there.

**Comment by ShockwaveNN** [comment]
MaxFileSize option should be changed in `/etc/onlyoffice/documentserver-example/default.json`, not in `/etc/onlyoffice/documentserver/default.json`

**Comment by p-klassen** [comment]
Hi there! I have the same issue and tried all things mentioned above.
Of course I also restarted the services and even tried to restart the whole docker container, but unfortunately I get the same error again and again. Is there any other config file or something where I can modify the limit?

**Comment by ShockwaveNN** [comment]
@p-klassen I think it's better to create another issue, because I think I will close this one, since author not answered anything since november of 2020

Please describe versions of product, all the steps you did to change config and files you're trying to open
