### ISSUE TITLE
Is license now required for Docker-DocumentServer?

### ISSUE THREAD

**Issue by N3tFX** [ONLYOFFICE/Docker-DocumentServer#315]
I've just tried to update the Docker-DocumentServer and, in Nextcloud, it suddenly stopped working giving a message that the license has expired and needs to be renewed. I made a clean installation of the latest docker of Docker-DocumentServer and managed to make it run but it now has a yellow label on the lest side saying it's in trial mode. Version is 6.1.0.

Is license now required for Docker-DocumentServer?

**Comment by daygr** [comment]
I would also like to know this, I am experiencing the same issue, though I do not see if there is any actual limitation in functionality due to the yellow trial mode label.

@N3tFX I've reverted to using the 6.0 tag for now which works fine.

**Comment by ShockwaveNN** [comment]
Sorry, seems we released default container `onlyoffice/documentserver` with enterprise edition package inside
This is not intended change

Currently figuring out that went wrong

**Comment by ShockwaveNN** [comment]
Sorry guys, it was a bug in our Docker Container deploy script
It should be fixed now, you should re-pull `onlyoffice/documentserver` image

**Comment by N3tFX** [comment]
It seems it works now. No messages about license or yellow trial label.

**Comment by ShockwaveNN** [comment]
@N3tFX Thanks for feedback. In that case I'll close this issue, feel free to comment or create new issue if got any questions
