### ISSUE TITLE
The editor is just still "Loading..."

### ISSUE THREAD

**Issue by marvinwankersteen** [ONLYOFFICE/Docker-DocumentServer#32]
Hey guys,

we have a problem to get onlyoffice running.
We use rancher in our environment. In front of the documentserver we have a loadbalancer (haproxy tcp-mode) and in front of the loadbalancer an reverseproxy (nginx) with SSL termination.

The documentserver is reachable with the FQDN "office.domain.com". If I load the page then I get the message "Thank you for choosing ONLYOFFICE! Document Server is running".

In "nextcloud.domain.com" I configured "https://office.domain.com". If i try to edit an document, a new tab is opening and only a white page appears.
With the developer-tools of the browser I get a link like "https://office.domain.com/2017-03-07-13-37/web-apps/apps/documenteditor/main/index.html?_dc=2017-03-07-13-37&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeEditor".
If I open this link in a new tab, I see forever the moving colors from top to bottom and "ONLYOFFICE Loading...". No errors or something.

Inside the documentserver https://nextcloud.domain.com is reachable.

I use the following images:
- nextcloud:11-apache
- onlyoffice/documentserver:latest

How can I better debug the progress?
Do you have any idea what is the problem?

marvin

**Comment by physios** [comment]
I am having the same problem, help would be nice

**Comment by cromulus** [comment]
same problem.

**Comment by agolybev** [comment]
Hello @marvinwankersteen 
Cloud you provide me your reverseproxy (nginx) config? 
At first, I have to make sure that you add `X-Forwarded-Host` and `X-Forwarded-Proto` headers with domain name and protocol to the proxing requests.
You can use [this](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/minimal.conf) example as reference to do this. [Here](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-https-to-http.conf) the nginx reverseproxy config with SSL termination for documentserver.

**Comment by suchasplus** [comment]
using docker image in Synology DS918+, same problem

**Comment by ShockwaveNN** [comment]
I'll close this issue, since it's pretty old
If issue still actual please create new issue at https://github.com/ONLYOFFICE/onlyoffice-nextcloud repo
