### ISSUE TITLE
nc (netcat) has a broken symlink to nc.openbsd in docker image

### ISSUE THREAD

**Issue by kernie** [ONLYOFFICE/Docker-DocumentServer#324]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
`docker log ONLYOFFICEIMAGE` results in many, many lines  with:
`/app/ds/run-document-server.sh: line 186: nc: command not found`
When I open an interactive bash terminal in image, I see that nc has a broken symlink to nc.openbsd.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Pull latest docker image
- Start it up
- Do `docker log` and check behavior

**What is the expected behavior?**
No error should be encountered.
**Did this work in previous versions of DocumentServer?**
Yes
**DocumentServer Docker tag:**
6.2.0

**Host Operating System:**
Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Hi, never seen such error

Could you show parameter of `docker run` you've used?

**Comment by kernie** [comment]
See below, $onlyoffice_version is set to latest.
```
docker run --name=ONLYOFFICEDOCKER -i -t -d -p 443:443 --restart=always \
        -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
        -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
        -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
        -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql \
        -e JWT_ENABLED='true' \
        -e JWT_SECRET='*************' \
    onlyoffice/documentserver:$onlyoffice_version
```

**Comment by ShockwaveNN** [comment]
I've checked simplest docker run command
```
docker run -itd --name=ONLYOFFICEDOCKER onlyoffice/documentserver:latest
sleep 120
docker exec -it ONLYOFFICEDOCKER nc
```

and there is no errors

Could you try to remove -v option one-by-one to determine which mount volume cause you this error?

**Comment by kernie** [comment]
So, seems the problem sat before the screen...

What I didn't mention, but was there: `-v OOetc:/etc` to make available the configuration files. Since this worked for all 5.x versions, I would conclude that the conf is not compatible for versions 6.x?
Same may go for the other folders?

**Comment by ShockwaveNN** [comment]
I think that mounting /etc worked in 5.x is just a luck

If you want to have mounted config file - try to mount `/etc/onlyoffice` - I think this may work

But also please note, that our config files are not always combatible, so if you just place config from version 5.x in 6.1 in may just not start, but at least you see correct error message in logs, not just very strange error about `nc`

**Comment by kernie** [comment]
OK, thanks!

It is tarting up now, however doing healthcheck in browser gives me:
```
[2021-01-12T17:42:26.734] [ERROR] nodeJS - healthCheck error
error: password authentication failed for user "onlyoffice"
    at Connection.parseE (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

New issue?

**Comment by ShockwaveNN** [comment]
> New issue?

No, I think it's all releated to your current config stored in `/etc`

Could you try to run same container without mountint your `/etc/onlyoffice`, then check that DocumentServer running correctly, extract `/etc/onlyoffice` content from this correct container and see diff in config file line by line, seems there is something different in db authentication

**Comment by kernie** [comment]
I didn't mount it this time... Same error. Can I provide more info?

**Comment by ShockwaveNN** [comment]
> I didn't mount it this time... Same error. Can I provide more info?

Try to remove some `-v` mounts and find which result of broken container
I want you to  provide some `docker run` which will fail on my environment - because your error with `nc` is definitely new for us

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
