### ISSUE TITLE
Error starting PostgreSQL 12 database server

### ISSUE THREAD

**Issue by kernie** [ONLYOFFICE/Docker-DocumentServer#325]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I fix temporalily issue #324 with a new symlink, then the script `/app/ds/run-document-server.sh` produces another error:
```
* Starting PostgreSQL 12 database server                                        * Error: Could not open logfile /var/log/postgresql/postgresql-12-main.log
Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /var/lib/postgresql/12/main -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1: 
                                                                         [fail]
 * Starting RabbitMQ Messaging Server rabbitmq-server                            * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
                                                                         [fail]
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Fix #324 and start docker container.
**What is the expected behavior?**
No error encountered
**Did this work in previous versions of DocumentServer?**
Yes.
**DocumentServer Docker tag:**
6.2.0
**Host Operating System:**
Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
I take a look at this issue as soon as we found out reason of #324

**Comment by kernie** [comment]
Closing because reason was discussed in #324 .
