### ISSUE TITLE
loading document forever

### ISSUE THREAD

**Issue by SuperHYJ** [ONLYOFFICE/Docker-DocumentServer#329]
1.starting onlyoffice by docker-compose:  docker-compose up -d

2.download the PHP demo from https://api.onlyoffice.com/app_data/editor/PHP Example.zip

3.open index page of PHP Example, browser shows like below:
![image](https://user-images.githubusercontent.com/20654049/105825032-1133c400-5ffa-11eb-83d6-f62fdba2b61a.png)

4 click create document to open a new page. and keeps showing "loading document"
![image](https://user-images.githubusercontent.com/20654049/105825219-50621500-5ffa-11eb-9a3a-364754d4d642.png)

below is my docker-compose.yml:
![image](https://user-images.githubusercontent.com/20654049/105825379-7f788680-5ffa-11eb-9516-51881631b5df.png)

**Comment by ShockwaveNN** [comment]
Hi, that are the errors in DocumentServer logs?
Seems something goes major wrong, maybe volume permissions

**Comment by SuperHYJ** [comment]
> Hi, that are the errors in DocumentServer logs?
> Seems something goes major wrong, maybe volume permissions
thanks for response.
I've check out all volumes that configured in `docker-compose.yml`:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - /usr/share/fonts
all directories are empty.

**Comment by SuperHYJ** [comment]
@ShockwaveNN 
thanks for response.
I've check out all volumes that configured in docker-compose.yml:
- /var/www/onlyoffice/Data
- /var/log/onlyoffice
- /var/lib/onlyoffice/documentserver/App_Data/cache/files
- /var/www/onlyoffice/documentserver-example/public/files
- /usr/share/fonts
all directories are empty.

**Comment by ShockwaveNN** [comment]
Try to connect to running DocumentServer container via 
`docker exec -it container-id bash`
and inisde it look at logs at `/var/log/onlyoffice`

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
