### ISSUE TITLE
Add information on how to restrict acces only to a Nextcloud/Owncloud server

### ISSUE THREAD

**Issue by e-alfred** [ONLYOFFICE/Docker-DocumentServer#33]
Hello,

please add information on how to restrict access to the Onlyoffice DocumentServer  only to a legitimate Nextcloud/Owncloud instance. It shouldn't be possible for other unauthorized users  on the network to access the Onlyoffice DocumentServer by e. g. sending excessive load to the server (resulting in a denial of service for legitimate users).

**Comment by JohnPerkin** [comment]
Hello!
Later we will implement a more advanced solution JWT and inform you about it.
In the current version of DS you may restrict access from alternative ownCloud, NextCloud or other file storages by editing Document Server configuration file **/etc/onlyoffice/documentserver/default.json**. Find the section `'filter'` and change it to the following look :
```"ipfilter": {
                   "rules": [
                     {
                       "address": "owncloud_IP_or_DN",
                       "allowed": true
                     },
                     {
                       "address": "*",
                       "allowed": false
                     }
                   ],
                   "useforrequest": true,
                   "errorcode": 403
                 }
```
After editing configuration file use the command `'supervisorctl restart all'`.
If you are using Docker version at first enter the container with `'docker exec -it container_ID /bin/bash'` and then perform previously mentioned operations.
Thank you for the interest in ONLYOFFICE.

**Comment by Huster-at-github** [comment]
Is it possible to mount **/etc/onlyoffice/documentserver/default.json** outside Docker container?

**Comment by himbeere** [comment]
Well the changes made in  /etc/onlyoffice/documentserver/default.json  are gone after the docker container restarts right? At least this is the case on my setup. There has to be a more persistent solution.

thanks and cheers

**Comment by SeWieland** [comment]
It should possible to mount the file outside of docker and make the changes persistent.
Just copy it once from your running docker container:
`docker cp onlyoffice:/etc/onlyoffice/documentserver/default.json /local/path/`
Make your changes and recreate the container using the file as a volume:
`- v /local/path/default.json:/etc/onlyoffice/documentserver/default.json`

**Comment by jory3** [comment]
Hi,
I configured document server as proposed above to limit access to DS: 
C:\Program Files\ONLYOFFICE\DocumentServer\config\default.json
`"ipfilter": {
        "rules": [
          {
            "address": "x.y.z.30",
            "allowed": true
          },
		  {
            "address": "x.y.z.31",
            "allowed": true
          },
{
            "address": "*",
            "allowed": false
          }
        ],
        "useforrequest": true,
        "errorcode": 403
      },`

But I can still edit my documents from comunity server on x.y.z.35. 

Community Server and Documentserver run on two virtual Windows 2016-Servers. 

Any ideas how to prevent others from using my DS-installation? 
Thanks!

**Comment by ShockwaveNN** [comment]
Hm, I created documentserver via docker with this config
```
"ipfilter": {
        "rules": [
                     {
                       "address": "159.203.164.133",
                       "allowed": true
                     },
                     { 
                       "address": "*",
                       "allowed": false
                     }
                   ],
                   "useforrequest": true,
                   "errorcode": 403
      }
```
And used nodejs test examples on `159.203.164.133` ip and `165.227.101.43` and everyhing worked as expected (159.203.164.133 can access documentserver, and 165.227.101.43 cannot).
But all my operations are done on ubuntu DigitalOcean droplets with docker, maybe it has something to do with windows

**Comment by agolybev** [comment]
Hi @jory3. Did you restart Document Server services after changing settings?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
