### ISSUE TITLE
About collaborative office

### ISSUE THREAD

**Issue by wardenlzr** [ONLYOFFICE/Docker-DocumentServer#331]
Dear open source, I don't know who the operator is and how to configure login permissions when working in collaboration？
Now I use these two commands to create an instance document.
`sudo docker exec ae210a3281b8 sudo supervisorctl start ds:example
sudo docker exec ae210a3281b8 sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf`

**Comment by ShockwaveNN** [comment]
Hi, could you describe your problem in more details, I think I'm not following you, especially 

> how to configure login permissions when working in collaboration

Which DMS  are you using? Nextcloud, owncloud, our test example or something other?

**Comment by wardenlzr** [comment]
I use https://github.com/zjyfdu/engineercms to build LAN online documents

**Comment by ShockwaveNN** [comment]
Are you a developer of this system or just an user?

Login permission are handled on DMS side

**Comment by wardenlzr** [comment]
I'm a user. Is an Android Developer, for this is completely Xiaobai, rookie

**Comment by ShockwaveNN** [comment]
@wardenlzr If you're are a user you better contact https://github.com/zjyfdu/engineercms team, since this is not product of ONLYOFFICE team

**Comment by wardenlzr** [comment]
That's OK. Thank you very much!
