### ISSUE TITLE
How can I create a real document?

### ISSUE THREAD

**Issue by wardenlzr** [ONLYOFFICE/Docker-DocumentServer#332]
Dear open source：
  I'm a rookie！How can I create a real document? Now I am used
 
    `sudo docker exec 3a4d1e15ca74 sudo supervisorctl start ds:example`    
    `sudo docker exec 3a4d1e15ca74 sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf`    

Example created
----------------------------------------------------------------------------------------------------------------------------
Other information，I don't know if it's useful to you:
ONLYOFFICE Docs™ Community Edition – Welcome!

Congratulations! Your Document Server has successfully started. Now you can integrate ONLYOFFICE Docs™ collaborative online document editing into your Web Application and use this Community Edition to open, edit and save your own documents with the most popular file formats, such as .DOCX, .XLSX, .PPTX, etc. Our editors are fully implemented in HTML5!
Open, Edit and Save existing documents for in-browser editing using ONLYOFFICE™ Server documents.
Collaborative co-editing functions – chat, comments and other multi-user features.
Use of Auto-save function.
All editing operations are processed on this virtual machine. Your documents stay under your complete control.

Want to learn the magic?
Explore ONLYOFFICE Docs™ Community Edition API Documentation.

Still not sure where to start?
Give a try to our test example which will allow you to upload your own local Office files from your computer for testing. It can be easily run with the following commands:
sudo docker exec 3a4d1e15ca74 sudo supervisorctl start ds:example
Add the example to the autostart:
sudo docker exec 3a4d1e15ca74 sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
Once started the example will be available here.
Please note, that the example is used for demonstration purposes only and it can be accessed by anyone. Once you finish examining it, we recommend that you disable this example for security reasons.
Any questions?
Please, submit your request here.
© Ascensio Systems Inc 2020. All rights reserved

**Comment by ShockwaveNN** [comment]
If you trying to integrate DocumentServer intro some 3rd party Document Management System (since you're already mention it here) - creation of document is handled on DMS side, not on  DocumentServer side

**Comment by wardenlzr** [comment]
I'm afraid you can't understand my Chinglish. I'll ask you another way。。。thanks  thanks  thanks
