### ISSUE TITLE
New integration edition Docker images are not published

### ISSUE THREAD

**Issue by immanuelfodor** [ONLYOFFICE/Docker-DocumentServer#337]
**Do you want to request a *feature* or report a *bug*?**

Bug, probably related to CI

**What is the current behavior?**

The latest Docker OO IE release is 6.0.2 which is old and lagging behind the main repo: https://hub.docker.com/r/onlyoffice/documentserver-ie/tags?page=1&ordering=last_updated

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See the links above and below

**What is the expected behavior?**

The latest OO Docker release is 6.2.0 and it was even preceded by 6.1.1 and 6.1.0: https://hub.docker.com/r/onlyoffice/documentserver/tags?page=1&ordering=last_updated

**Did this work in previous versions of DocumentServer?**

Yes, images were published in parallel

**DocumentServer Docker tag:**

Latest: 6.2.0, and all the way back to 6.0.2 which is the last working version

**Host Operating System:**

Unrelated

**Additional context**

Integration edition was published for project contributors to work with the contributor license. Should we now use the `documentserver` with the license instead of the `documentserver-ie` flavor? Has it been deprecated in the meantime?

**Comment by ShockwaveNN** [comment]
Hi

`documentserver-ie` is deprecated and you should use `documentserver-ee`

As far as I remember - there was an email notification about it to all active customers

**Comment by immanuelfodor** [comment]
Ohh, I didn't get that, thanks for the heads up! 

It indeed contains the latest release: https://hub.docker.com/r/onlyoffice/documentserver-ee/tags?page=1&ordering=last_updated
