### ISSUE TITLE
Written content isnt saved

### ISSUE THREAD

**Issue by FlorianTaut** [ONLYOFFICE/Docker-DocumentServer#35]
Hey guys,

i implemented the DocumentServer to my Nextcloud.
Iam accessing an WebDAV share via an NextCloud-App.

I was creating a new Spreadsheet and it was automatically opened in OnlyOffice.
Now when im writing content to the document and it is automatically saved and then open it on my Windows Computer the written content doenst appear in it...

Does anybody have a solution for this?
It seems like there is any Problem with SSL encryption, do you need the Nextcloud logs?

Should i open an issue at Nextclouds Github Page?

Thank you very much

**Comment by taut98** [comment]
@JohnPerkin Could you please ask the devs if they can start something with this:
![onlyoffice](https://cloud.githubusercontent.com/assets/18403881/25481866/736341f2-2b4f-11e7-9438-2897ca4c97a3.PNG)

**Comment by JohnPerkin** [comment]
Hello @taut98 
Thank you for the great attention to ONLYOFFICE and your remarks on its working but initially ownCloud/NextCloud integretion app was designed to work with ownCloud and NextCloud storages. To implement working Document Server with external storages is different task at all.
Best regards
John
ONLYOFFICE support team

**Comment by alexanderonlyoffice** [comment]
Hello @FlorianTaut 

Please download the new version of the application connector [here](https://github.com/ONLYOFFICE/onlyoffice-owncloud/releases). Unpack it to the **_/nextcloud/apps/onlyoffice/_** Open the config file **_/nextcloud/config/config.php_**. And add a section: 

'onlyoffice' =>
  array (
    've1rify_peer_off' => TRUE,
  )
