### ISSUE TITLE
Concurrent Doc Editing

### ISSUE THREAD

**Issue by joelchittum** [ONLYOFFICE/Docker-DocumentServer#356]
**Do you want to request a *feature* or report a *bug*?** Question

**What is the current behavior?**  Limited number of concurrent document editors

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** NA

**What is the expected behavior?** NA

**Did this work in previous versions of DocumentServer?**  NA

**DocumentServer Docker tag:** documentserver:6.2

**Host Operating System:** Manjaro 20

I have run into an issue where the document server will not allow for more connections.  I am curious if there is a way to increase this value.

Screenshot of the error: 
![Screenshot_20210422_124036](https://user-images.githubusercontent.com/10146922/116881107-db9e0880-abf0-11eb-988f-ccb298104aaf.png)

**Comment by ShockwaveNN** [comment]
I'm sorry, I think the message is very clear that you need to do - you should buy license, correct me if is not clear enough

**Comment by dreua** [comment]
I haven't tried that myself, but it's open source so it should be possible to find and increase the number of this limit, right? You should, however, seriously consider supporting the company behind this by playing fair and buying a license. I think proper document editing means a lot of hard work and as far as I can tell, onlyoffice is doing a good job at this!

**Comment by ShockwaveNN** [comment]
> but it's open source so it should be possible to find and increase the number of this limit, right

I'm sorry but I will not discuss in our official issue tracker how to broke our monetization and left me without job )

**Comment by dreua** [comment]
@ShockwaveNN I absolutely understand that :smile: Thought I might add it anyway, hope you don't mind. Btw, I'm up for hire for both sides, Email is in my profile :wink:

**Comment by ShockwaveNN** [comment]
I'll close this issue since we discuss all related problems
