### ISSUE TITLE
Regarding opening of a document from local on document server.

### ISSUE THREAD

**Issue by bharatramawat28** [ONLYOFFICE/Docker-DocumentServer#369]
I am unable to open any document for the java example given on site. I have installed onlyoffice document server on Docker and now I have changed all the URL required in settings.property. but still, it is not opening and showing 

[2021-07-22T14:30:04.460] [ERROR] nodeJS - postData error: docId = -191991650;url = http://localhost:8088/OnlineEditorsExampleJava/IndexServlet?type=track&fileName=TestExcelOnlyOffice.xlsx&userAddress=192.168.29.241;data = {"key":"-191991650","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: connect ECONNREFUSED 127.0.0.1:8088
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

Please help me out.

**Comment by ShockwaveNN** [comment]
Hi, I need more details

Judging by url are you using 8088 port for both DocumentServer and java example?

**Comment by bharatramawat28** [comment]
I have my docker installed on localhost port 80 and then I am running this example from eclipse tomcat whose port is 8088.

**Comment by bharatramawat28** [comment]
These are my settings.property


filesize-max=5242880
storage-folder=app_data

files.docservice.viewed-docs=.pdf|.djvu|.xps
files.docservice.edited-docs=.docx|.xlsx|.csv|.pptx|.txt
files.docservice.convert-docs=.docm|.dotx|.dotm|.dot|.doc|.odt|.fodt|.ott|.xlsm|.xltx|.xltm|.xlt|.xls|.ods|.fods|.ots|.pptm|.ppt|.ppsx|.ppsm|.pps|.potx|.potm|.pot|.odp|.fodp|.otp|.rtf|.mht|.html|.htm|.xml|.epub|.fb2
files.docservice.timeout=120000

files.docservice.url.site=http://localhost/
files.docservice.url.converter=ConvertService.ashx
files.docservice.url.command=coauthoring/CommandService.ashx
files.docservice.url.api=web-apps/apps/api/documents/api.js
files.docservice.url.preloader=web-apps/apps/api/documents/cache-scripts.html
files.docservice.url.example=

files.docservice.secret=Secret
files.docservice.header=Authorization

**Comment by ShockwaveNN** [comment]
> files.docservice.url.site=http://localhost/

If you run DocumentServer in docker I think this should be your local ip, not localhost because there may be connection issues

**Comment by bharatramawat28** [comment]
Still Having issues:

2021/07/22 15:09:16 [error] 6237#6237: *56 open() "/var/www/onlyoffice/documentserver/sdkjs/common/libfont/wasm/file.js" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /sdkjs/common/libfont/wasm/file.js HTTP/1.1", host: "192.168.29.241", referrer: "http://192.168.29.241/web-apps/apps/api/documents/cache-scripts.html"
2021/07/22 15:09:16 [error] 6237#6237: *56 open() "/var/www/onlyoffice/documentserver/sdkjs/common/libfont/wasm/engine.js" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /sdkjs/common/libfont/wasm/engine.js HTTP/1.1", host: "192.168.29.241", referrer: "http://192.168.29.241/web-apps/apps/api/documents/cache-scripts.html"
2021/07/22 15:09:16 [error] 6237#6237: *56 open() "/var/www/onlyoffice/documentserver/sdkjs/common/libfont/wasm/manager.js" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /sdkjs/common/libfont/wasm/manager.js HTTP/1.1", host: "192.168.29.241", referrer: "http://192.168.29.241/web-apps/apps/api/documents/cache-scripts.html"

**Comment by ShockwaveNN** [comment]
Those errors are normal, for wasm files

Does opening files are not working?

Could you attach a video of error

**Comment by bharatramawat28** [comment]
https://user-images.githubusercontent.com/63096895/126665445-88f5bf64-4f7f-4751-a73b-c3121883c5f8.mp4

Hi please find the attached mp4 file. 

Thanks a lot for helping me out on this.

**Comment by ShockwaveNN** [comment]
On 11 second it opened on localhost, it should be opened on local ip

**Comment by bharatramawat28** [comment]
I have changed this as you said => files.docservice.url.site=http://192.168.29.241/
still, it is opening on that. How can I change that?

**Comment by ShockwaveNN** [comment]
You missing my point

Your setting in config is correct

You should open chrome with `http://192.168.29.241:8088/, not with `http://localhost:8088/ (see 11 second)

**Comment by bharatramawat28** [comment]
![image](https://user-images.githubusercontent.com/63096895/126669831-d57935d9-6cc6-44f8-80c3-fbaf27a1357e.png)

Now I have done that but it's showing an error and the file is not opening to edit.

**Comment by bharatramawat28** [comment]
![image](https://user-images.githubusercontent.com/63096895/126670116-f6b25d26-8e62-460a-982e-9cf9e9391ade.png)

This screen is opening after the ok button part.

**Comment by bharatramawat28** [comment]
When I upload any file then it remains forever stuck in the conversion part.

![image](https://user-images.githubusercontent.com/63096895/126670502-1d1755df-40f3-4c66-a4b1-2486b84b9382.png)

**Comment by bharatramawat28** [comment]
Please help me out with this conversion issue.

**Comment by ShockwaveNN** [comment]
Is there any errors in logs of DocumentServer?

**Comment by bharatramawat28** [comment]
No just the wasm errors.

**Comment by bharatramawat28** [comment]
once I upload the file then this conversion process is running like forever.

**Comment by ShockwaveNN** [comment]
Hm, did you say you downloaded version from site? There is maybe incorrect version there

Could you try this: https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/java

It should you older design like this:
![image](https://user-images.githubusercontent.com/668524/126753396-3c0532bc-4565-41ae-acaa-bc6a3534902d.png)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
