### ISSUE TITLE
Container fails to start. RabbitMQ initialisation error onlyoffice/documentserver:latest

### ISSUE THREAD

**Issue by benricok** [ONLYOFFICE/Docker-DocumentServer#373]
Hi, I'm having trouble installing the onlyoffice document server in conjunction with nextcloud with a known working configuration file. (I've used it before with great success on a different server(arch linux with docker) and on the same hardware with a previous installation of proxmox and an identical Debian VM also running docker)

**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behaviour?**
The onlyoffice document server doesn't initialise properly after installation. (Starting of RabbitMQ fails)

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I've attached my docker-compose.yml file (add your own domains, passwords, file locations) for reproduction purposes.

**What is the expected behaviour?**
The container initialises properly without errors (rabbitMQ)

**Did this work in previous versions of DocumentServer?**
Yes, this docker-compose configuration worked multiple times with previous installs.

**DocumentServer Docker tag:**
onlyoffice/documentserver:latest (v6.3 I think?)

**Host Operating System:**
Debian Buster VM on Proxmox host
Docker version: 18.06.3-ce
4 vCPU, 8GB RAM (VM)

Attached to this message is the container.log, docker-compose.yml and RabbitMQ log files.
[Container.log](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/7025883/Container.log)
[docker-compose.yml.txt](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/7025889/docker-compose.yml.txt)
[startup_err (RabbitMQ).log](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/7025892/startup_err.RabbitMQ.log)
[startup_log (RabbitMQ).log](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/7025894/startup_log.RabbitMQ.log)

**Comment by ShockwaveNN** [comment]
Personally I dont think this is problem of DocumentServer, since all I see that rabbitmq is crashing on boot 

Is there more detailed error in Rabbitmq log at `/var/log/rabbitmq/rabbit@c8901396ecf1.log`?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
