### ISSUE TITLE
Error  When Provides Custom File Storage Path On Editor Page

### ISSUE THREAD

**Issue by abhi5003** [ONLYOFFICE/Docker-DocumentServer#378]
When providing a custom storage path for document edit I got an error.
Files always goes in app_data folder of the workspace directory.
I want to provide custom path for file storage.
![Capture](https://user-images.githubusercontent.com/55706631/132865687-ef888e7d-e9b8-4300-a7c6-8adcdab3aafb.PNG)

**Comment by ShockwaveNN** [comment]
Hi, this error usually means that DocumentServer cannot download a file you've trying to edit
Usually, it's a firewall/network related problem

You can see for more details in log in `/var/log/onlyoffice/`

**Comment by abhi5003** [comment]
When we try to open other then app_data storage folder i got error
![Capture](https://user-images.githubusercontent.com/55706631/132867492-ce0567a1-f44d-4379-bea8-91e667cf21ee.PNG)

**Comment by ShockwaveNN** [comment]
> When we try to open other then app_data storage folder i got error

I do not understand how it's related to my statement about logs

Please read my answer carefully and I do not understand how your screenshot related to your problem without any logs

Please note, that Github is not a support forum, it's the site you post issues with our product, and issue report should be strict and reproducible on our side

**Comment by abhi5003** [comment]
by default to download file in editor take this path from computer
http://192.168.1.100:8081/OnlineEditorsExampleJava/app_data/192.168.1.100/WR_08252021.docx

I want to give another custom path

**Comment by ShockwaveNN** [comment]
This path provided by integration, more info [here](https://api.onlyoffice.com/editors/config/document#url)

**Comment by abhi5003** [comment]
i got this error in log

[2021-09-08T09:25:07.540] [ERROR] nodeJS - postData error: docId = -2028686615;url = http://192.168.1.100:8081/OnlineEditorsExampleJava/IndexServlet?type=track&fileName=WR_08272021.docx&userAddress=192.168.1.100;data = {"key":"-2028686615","status":4,"actions":[{"type":0,"userid":"uid-1"}]}
Error: connect ECONNREFUSED 192.168.1.100:8081

**Comment by ShockwaveNN** [comment]
> Error: connect ECONNREFUSED 192.168.1.100:8081

This literally means that DocumentServer trying to download the file by host/port `192.168.1.100:8081` and for some reason cannot connect to this host with this port

**Comment by ShockwaveNN** [comment]
I think this is configuration problem on your integration example, not an issue with DocumentServer

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
