### ISSUE TITLE
Send request to application after file updated.

### ISSUE THREAD

**Issue by xunmeng2015** [ONLYOFFICE/Docker-DocumentServer#380]
I'm running docker-communityServer and docker-documentServer, i want to send a request to my backend application after file updated, but i don't want to interrupt normal procedure. It means that my application get request (and return something) only, without save file or any other operations.

**Comment by ShockwaveNN** [comment]
I think one way to solve this problem - you should create a service that monitors changes in the version of the file in CommunityServer using API and if changes are detected - send request to your server

Also please note that GitHub is not a forum - your problem sound like not an issue, but some idea - so you've better discuss it on [forum ](https://forum.onlyoffice.com/)
