### ISSUE TITLE
REDIS_SERVER_PWD is it avalible variable like this to add password of external redis ?

### ISSUE THREAD

**Issue by masterwishx** [ONLYOFFICE/Docker-DocumentServer#385]
Help
Added External postgres database also redis container by:

REDIS_SERVER_HOST: The IP address or the name of the host where the Redis server is running.
REDIS_SERVER_PORT: The Redis server port number.

if i have password on redis how to add it ?
Thanks

**Comment by ShockwaveNN** [comment]
@igwyd Please take a look as soon as you got free time

**Comment by igwyd** [comment]
Hello @masterwishx, sorry for the late reply. We have addition param for redis, you can add your password in /etc/onlyoffice/documentserver/local.json
```
{
  "services": {
    "CoAuthoring": {
...
      "redis": {
        "host": "YOUR_HOST",
        "port": "YOUR_PORT"
        "options": {"password": "YOUR_PASSWORD"}
      },
...
```

**Comment by igwyd** [comment]
We havn't param, but i created enhancement bug 57286 in our private issue tracker to implement this.

**Comment by masterwishx** [comment]
will be good to have ENV = REDIS_SERVER_PASS

**Comment by igwyd** [comment]
It's fixed at: https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/466
And will be released in the next major release.

**Comment by masterwishx** [comment]
> And will be released in the next major release.

Thanks . and what redis db index it will use ?

**Comment by masterwishx** [comment]
Also wanted to ask if i really need using redis if i use onlyoffice docker with PostgresSQL
on Nextcloud Docker that using redis  (memcache.locking' => '\\OC\\Memcache\\Redis',)

**Comment by igwyd** [comment]
@masterwishx in DE and EE version onlyoffice-documentserver required redis. We don't specify an index number, I guess using db0 by default, but you can do that if you want. We use [node-redis](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) for connection.

**Comment by masterwishx** [comment]
Thanks, im using CE version its also using redis right ?
i asked about base index becose having an Authelia already on db 0 by default .

**Comment by igwyd** [comment]
no, the community version doesn't use redis.

**Comment by masterwishx** [comment]
> no, the community version doesn't use redis.

Thanks i got it

**Comment by varac** [comment]
Please release a new docker image soon containing this fix, the last version on docker hub is 3 month old ([7.1.1.23](https://hub.docker.com/layers/documentserver/onlyoffice/documentserver/7.1.1.23/images/sha256-8a1edcc13f9d9dd61f3e77bcb172b0f32d0788aa2c63bb5a1206a7633e3dd2f8?context=explore)):

![image](https://user-images.githubusercontent.com/488213/186709775-cbec4015-7176-4c9a-acd1-9a5613bdb619.png)

**Comment by ShockwaveNN** [comment]
@varac We update version as soon as v7.2 will be ready for release, probably next month

Right now it's not in production-ready state

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
