### ISSUE TITLE
Docker Container cannot start

### ISSUE THREAD

**Issue by BentiGorlich** [ONLYOFFICE/Docker-DocumentServer#387]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I try to start the docker container, I get this error message: `docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.`
My start command: ` sudo docker run -i -t -d -p 8002:443 --restart=always     -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice      -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data      -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice     -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver:6.3.0`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it starts the docker container
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer Docker tag:**
tried 6.3, 6.3.0, latest
**Host Operating System:**
debian10u2

I updated a bunch of libraries, but why would that get me that error. Any help is appreciated.

**Comment by ShockwaveNN** [comment]
This is new for me, but I don't think it's our problem, maybe error in Docker itself

I've found something like this:
https://stackoverflow.com/questions/67791683/docker-container-starting-issue-setting-cgroup-config-for-prochooks-process-cau

I think you first should update your host os to latest version of docker and contained

P.S. To be clear - your host OS is not ARM-based?

**Comment by BentiGorlich** [comment]
Hello,
I had trouble to find stuff that is truly connected to my issue. The problem is it sounds like something with cgroup, but I do not have cgroup installed...
I already tried to fully reinstall docker and it didn't change anything.

No I am running on x86 (Intel NUC)

**Comment by ShockwaveNN** [comment]
Could you try this on another server?

Generally speaking this error is raised from docker program itself, so I'm 95% sure it's not related to DocumentServer

**Comment by ShockwaveNN** [comment]
And I'm not mean upgrading your system, but updating. This shouldn't be a risk.

At least make sure that you've using latest version of docker packages

**Comment by BentiGorlich** [comment]
Ok. Yeah I did that and that's when docker began to give me that error message. 
I ran a complete
```
sudo apt-get update
sudo apt-get upgrade
```

**Comment by ShockwaveNN** [comment]
Ok in that case I'm almost sure this is issue in docker side and you should report it appropriate repo

**Comment by BentiGorlich** [comment]
ok, then I will try to get an answer from there. I thought you may have an idea whats causing this. Thanks for the answers :)

**Comment by ShockwaveNN** [comment]
> I thought you may have an idea whats causing this

No sorry, never saw an error like this in our app
And docker itself is a very complicated tool, so reason may be anything

The only advice I have - try to set up new server with Debian 10 and see in clear setup if everything works fine - if not maybe this problem is more global than your machine

**Comment by ShockwaveNN** [comment]
Also I found this

https://github.com/opencontainers/runc/issues/3008

So as far as I understand it depends on combination of system kernel and docker service version, but this may be another error

**Comment by BentiGorlich** [comment]
Yeah, I created an issue on the https://github.com/moby/moby/ repo and they asked the same. The `hello-world` image did throw the same error. So it is definatley not an only office issue.
https://github.com/moby/moby/issues/42909

**Comment by ShockwaveNN** [comment]
@BentiGorlich Got it, thanks
