### ISSUE TITLE
Documentation-extension on configuration for variables

### ISSUE THREAD

**Issue by aignerat** [ONLYOFFICE/Docker-DocumentServer#388]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Documentserver Configuration is hardcoded - Especially on the publically known storage-Secret-Key "verysecretkey"

**What is the expected behavior?**
Documentation on how to change Config-Values in the recommended way (most probably ENV).

**DocumentServer Docker tag:**
Documentation

**Host Operating System:**
Centos 7 (irrelevant)

**Comment by ShockwaveNN** [comment]
We added ability to specify this secret via ENV
https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/444

It will be released in next major release, v7.2.0

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions
