### ISSUE TITLE
Bind for 0.0.0.0:8080 failed: port is already allocated

### ISSUE THREAD

**Issue by HaroldoPayares** [ONLYOFFICE/Docker-DocumentServer#39]
Hello,

I have followed step bu step the "README.md", i ran the docker image in this way:

sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver

But when i get to "Configuring Docker Image" part:

sudo docker run -i -t -d -p 8080:80 \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice onlyoffice/documentserver

After i enter the last line i got this error message:

0f52c208c343095c23917b8ccc1a2d43b7d394e9dbc00e78d8686b44a5ff5617
docker: Error response from daemon: driver failed programming external connectivity on endpoint loving_shaw (ac23a807cb82ab29742b0fcacb2eab4b48e26858d34c4f5966ba0796aa64995f): Bind for 0.0.0.0:8080 failed: port is already allocated.

What am i doing wrong?, What can i do to fix this?

Thank you in advance

**Comment by agolybev** [comment]
Hello,
It seem like port 8080 is already being used by another application.
Check it with `sudo netstat -ntpl | grep 8080`

**Comment by HaroldoPayares** [comment]
Thank You for your answer. I did check with `sudo netstat -peanut` and that port wasn't used.
I decided to run a new process from 0, i got the same error:

First i opened de 8 port and cheked is no used:

```
~$ sudo netstat -peanut
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      111        17292       1184/mysqld     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          15204       1155/sshd       
tcp        0    228 192.168.254.20:22       192.168.252.103:33742   ESTABLISHED 0          31194       4871/sshd: sistemas
tcp6       0      0 :::80                   :::*                    LISTEN      0          15224       1310/apache2    
tcp6       0      0 :::22                   :::*                    LISTEN      0          15206       1155/sshd       
tcp6       0      0 :::443                  :::*                    LISTEN      0          15228       1310/apache2    
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          13171       1094/dhclient 
```

Then install and run the image:
  
```
~$ sudo docker run -i -t -d -p 8:8 onlyoffice/documentserver
Unable to find image 'onlyoffice/documentserver:latest' locally
latest: Pulling from onlyoffice/documentserver
30d541b48fc0: Pull complete 
8ecd7f80d390: Pull complete 
46ec9927bb81: Pull complete 
2e67a4d67b44: Pull complete 
7d9dd9155488: Pull complete 
5620cbf30007: Pull complete 
33c528c7fa34: Pull complete 
b69368ba62d0: Pull complete 
61c24e4c0f08: Pull complete 
Digest: sha256:3f5c86fdc61d9bbb550b2323b67d422c5925b7bb308a35970f00ecd7daf8c7e3
Status: Downloaded newer image for onlyoffice/documentserver:latest
4e010fb90bc36f3d1cfc56da2f304f5f091d3c2169e1246e58e8ad68bf82d451
```

Then again check the port, now is used by docker-proxy:

```
~$ sudo netstat -peanut
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      111        17292       1184/mysqld     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          15204       1155/sshd       
tcp        0    228 192.168.254.20:22       192.168.252.103:33742   ESTABLISHED 0          31194       4871/sshd: sistemas
tcp6       0      0 :::80                   :::*                    LISTEN      0          15224       1310/apache2    
tcp6       0      0 :::22                   :::*                    LISTEN      0          15206       1155/sshd       
tcp6       0      0 :::443                  :::*                    LISTEN      0          15228       1310/apache2    
tcp6       0      0 :::8                    :::*                    LISTEN      0          32584       5253/docker-proxy
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          13171       1094/dhclient  
``` 

Then in the next step i got the same issue after i enter the last line :

```
~$ sudo docker run -i -t -d -p 8:8 \

`> -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \`

`> -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \`

`> -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice onlyoffice/documentserver`
ed27f08f79e7267405519516e7a3a2331ffd33ea2935cc111088c7ed23a5c97b
docker: Error response from daemon: driver failed programming external connectivity on endpoint inspiring_beaver (03a04a5d48e9930598162cac56033ee5ecff143e35c2594bb5016aeac2cf4016): Bind for 0.0.0.0:8 failed: port is already allocated.
```

What am i doing wrong?

**Comment by agolybev** [comment]
Hello,
It seems like you are trying to start the onlyoffice/documentesrver container twice.
First time by 
`sudo docker run -i -t -d -p 8:8 onlyoffice/documentserver` command
Second time by 
```
sudo docker run -i -t -d -p 8:8 \
 -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
 -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
 -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice onlyoffice/documentserver
```

**Comment by HaroldoPayares** [comment]
Thank you for your time, your advise did help.

**Comment by cama0047** [comment]
You have to stop all the services before executing the 

> docker-compose up -d

that would solve the problem.

**Comment by Jeff-Enriquez** [comment]
Hi, I'm getting this same error and everything I look up says to do the same thing. Run 'docker-compose up -d' or run 'docker-compose down' then 'docker-compose up'. Anytime I try those commands I get the same error. 'Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?' How do I solve this?

**Comment by ShockwaveNN** [comment]
> Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?

Seems that is separate issue, not related to this, please create new issue
