### ISSUE TITLE
Error: EACCES: permission denied, open '/etc/onlyoffice/documentserver/log4js/production.json'

### ISSUE THREAD

**Issue by ghostman-git** [ONLYOFFICE/Docker-DocumentServer#390]
Error: EACCES: permission denied, open '/etc/onlyoffice/documentserver/log4js/production.json'

**Comment by ShockwaveNN** [comment]
Hi, could you describe in more details your error, when it happened, how do you run DocumentServer

I don't think current report can be informative for anyone

**Comment by ghostman-git** [comment]
![image](https://user-images.githubusercontent.com/13376074/141400862-f33395f3-8f18-45df-b760-9a26b06988b7.png)
