### ISSUE TITLE
Wrong Permissions: /etc/ssl/private/ssl-cert-snakeoil.key blocked container start

### ISSUE THREAD

**Issue by geraldurbas** [ONLYOFFICE/Docker-DocumentServer#394]
* Starting PostgreSQL 12 database server         * Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /var/lib/postgresql/12/main -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1: 

2021-12-05 11:44:23.305 UTC [141] FATAL:  could not load private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied

2021-12-05 11:44:23.305 UTC [141] LOG:  database system is shut down

Had to:
`chmod 400 /etc/ssl/private/ssl-cert-snakeoil.key`

Just pulled the image from via docker

**Comment by ShockwaveNN** [comment]
I think we mention about this in [README](https://github.com/ONLYOFFICE/Docker-DocumentServer#installation-of-the-ssl-certificates) if this is your own cert

> chmod 400 /app/onlyoffice/DocumentServer/data/certs/tls.key

I don't know what's the file `/etc/ssl/private/ssl-cert-snakeoil.key`

So maybe something wrong with your docker run command and you've mounted your host system certs?

**Comment by geraldurbas** [comment]
I configured SSL_CERTIFICATE_PATH and SSL_KEY_PATH
Dont know why PG is refering the snake oil certs...

Maybe an error in postgres:9.5 image...

**Comment by ShockwaveNN** [comment]
> Maybe an error in postgres:9.5 image...

By default, we got integrated postgres in our default image

So to able to figure out your error we need exact step-by-step guide how to reproduce it

**Comment by geraldurbas** [comment]
The (quite old) Docker lived on a strange NAS Linux ... Guess its related to that.
Tested it on updated Ubuntu 20.04 and cant reproduce it there

**Comment by ShockwaveNN** [comment]
> The (quite old) Docker lived on a strange NAS Linux

Yep, this may be a reason
Thanks for clarification
