### ISSUE TITLE
PK ##################

### ISSUE THREAD

**Issue by iwkse** [ONLYOFFICE/Docker-DocumentServer#4]
Hi,
suddenly I'm having this problem with OnlyOffice API. When the document is saved, everything that is inside is erased and there's only PK ##################
Do you have an hint about what could it be? Since now it was working flawless.
[edit]
PK is referring to what? Public Key?
I've just reset all, and get a new docker image but still the issue persist. It's weird.

**Comment by ibnpetr** [comment]
Hello
We need some additional information in order to be able to reproduce the issue.
Please specify the type of connection
Arу you using alfresco?
Describe your actions step by step and submit the file for analysis 
Feel free to send it to server@onlyoffice.com

**Comment by iwkse** [comment]
Hi,
the connection should be by websocket, I'm using Alfresco and this extension: 
https://github.com/cetra3/onlyoffice-alfresco

The issue is not with a file in particular but all files. Anything that I use makes the same issue.

Steps are:
1. Open a file in OnlyOffice
2. Do some changes and Save

After this in Alfresco the file corrupted and inside there's only  "PK#############"

Could you provide some info how to debug that?
I want to know what happens after saving the document,

Thanks

**Comment by iwkse** [comment]
I just did some tests and I notice that the file is corrupted just before sending it back to Alfresco. When I click save, I can see the file modified correctly, the issue happens after this. But it's a mystery.
Anyone nice for a hint?

**Comment by iwkse** [comment]
Hi,
please anyone could give me a hint to monitor this issue? Is what I wrote in last message correct? PK is referred to the compression of the document?
I hope in a reply,
kind regards,

**Comment by ibnpetr** [comment]
Could you please specify the exact moment when you see this PK### 
Please send full description, screenshots of the document interface and any warning message to server@onlyoffice.com
I regret to inform you that we still cannot reproduce the issue.
It also would be great if you give us access to the alfresco panel for testing

**Comment by iwkse** [comment]
Thanks for your reply, I just sent you an email to the supplied email address.

**Comment by iwkse** [comment]
Hi, I would like to close this bug as it's connected to the kernel used. As showed here http://aufs.sourceforge.net/ aufs support has been dropped on October 2015 and OnlyOffice right now is not capable to deal with xfs without running into this bug. OnlyOffice team communicates that the issue is being fixed for Enterprise but not yet for the open source version.
I hope this bug will be fixed for open source as well.

**Comment by iwkse** [comment]
Unluckily switching to something else from xfs doesn't fix it.
