### ISSUE TITLE
Nginx Proxy Manager Internal ERROR

### ISSUE THREAD

**Issue by adamelo007** [ONLYOFFICE/Docker-DocumentServer#407]
Hello I need some help. I just installed Nginx Proxy Manager and connected it to the CLOUDFLERE DNS server, when I set it to Nigix a new link writes me ERROR (Internal Erron).
Wher I look for SSL shows HTTP only and not working at all.

Please help.
Thansk.

Adam Križaj
![Zajeta slika4](https://user-images.githubusercontent.com/99595253/153752893-2e56185e-b905-4248-b2eb-eaf2af254833.PNG)
![Zajeta slika5](https://user-images.githubusercontent.com/99595253/153752991-2b2e7c8a-17a7-4a88-9d29-e299f4a6c02f.PNG)

**Comment by ShockwaveNN** [comment]
Hi, are you sure there is some problem in DocumentServer side?

I've never had any experience with Nginx Proxy manager but is other application work fine on your setup

If so, we need some more additional details - that is docker run command for DocumentServer, which version are you using and some more detailed guide how did you setup Nginx Proxy manager

**Comment by adamelo007** [comment]
Hi yes I have Plex and Transmition.... all application work conplitly fine.
Witch DocumentServer do you need??

**Comment by ShockwaveNN** [comment]
> Witch DocumentServer do you need??

Sorry, do not understand this question

We need step-by-step instruction how to reproduce this problem with DocumentServer on our infrastructure without any previous experience with Nginx Proxy Manager

**Comment by adamelo007** [comment]
I followed these instructions:
https://www.youtube.com/watch?v=bQdqf5xAyUk&t=491s

**Comment by adamelo007** [comment]
For DNS server and domain, these are the two videos:
1.  https://www.youtube.com/watch?v=Nf7m3h11y-s&t=290s
2.  https://www.youtube.com/watch?v=m-RYTu-Qq3A&t=902s

**Comment by ShockwaveNN** [comment]
Ok, we'll have a look then we got free time, one last question

Which version of ONLYOFFICE DocumentServer is involved in this setup?

**Comment by adamelo007** [comment]
I don't know what it is and where I get it

**Comment by adamelo007** [comment]
What is ONLYOFFICE DocumentServer?

**Comment by ShockwaveNN** [comment]
If you don't know that it is why you posted it to our issue tracker?

This is issue tracker for ONLYOFFICE DocumentServer, read README file in this project

Are you saying this issue is not related to our product at all?

**Comment by adamelo007** [comment]
sorry
