### ISSUE TITLE
DocumentServer not working on port other than 80

### ISSUE THREAD

**Issue by robeatoz** [ONLYOFFICE/Docker-DocumentServer#410]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I will begin with a working example:

If I start the DocumentServer with the following command, copied from the [README.md](https://github.com/ONLYOFFICE/Docker-DocumentServer#readme), everything work fine:

```
docker run -i -t -d -p 80:80 onlyoffice/documentserver

[Wait until startup finished]

docker exec 8a3b36853fb4 sudo supervisorctl start ds:example
```

![image](https://user-images.githubusercontent.com/32271374/155854103-407600f6-7e29-42ee-a3fc-0bd85d6fe6ca.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

But if I start the DocumentServer with the following command, copied from the [README.md](https://github.com/ONLYOFFICE/Docker-DocumentServer#readme), too, I can not open any type of document:

```
docker run -i -t -d -p 8080:80 onlyoffice/documentserver

[Wait until startup finished]

docker exec c1862fcebf78 sudo supervisorctl start ds:example
```

![image](https://user-images.githubusercontent.com/32271374/155854189-1e4ddecb-1e54-4fff-8370-d08da821a200.png)

The log shows:

```
[2022-02-26T17:54:28.689] [ERROR] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=172.17.0.1;attempt=3;code:ECONNREFUSED;connect:null;(id=172.17.0.1http___localhost_8080_example_files_172.17.0.1_new.docx1645898065685)
Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

**What is the expected behavior?**

I expected that it does not matter which port docker routes to the DocumentServer container

**Did this work in previous versions of DocumentServer?**

Same behavior with `onlyoffice/documentserver:6.4.2.6`

**DocumentServer Docker tag:**

- `latest`
- `7.0.1.37`
- `6.4.2.6`

**Host Operating System:**

Docker on Windows and Ubuntu

**Comment by ShockwaveNN** [comment]
Hi, you should not access it in your browser via `localhost`, but you should via your local ip, like `http://192.168.1.238/example` in my home network

Because `localhost` for your browser and `localhost` inside container - is a different `localhosts`

**Comment by robeatoz** [comment]
I will give it a try, thank you @ShockwaveNN!

**Comment by ShockwaveNN** [comment]
@robeatoz Thanks for clarification

Maybe you can provide `docker network` commands you've used? 
I see now that it was rather easy to do via `docker-compose` since (at least for me) networking between containers are easier in `docker-compose`

**Comment by robeatoz** [comment]
@ShockwaveNN I use docker-compose, too, and corrected my comment to singular `docker network`.

**Comment by Dnhatsave** [comment]
I think i'm  facing  the same issue,

I have Apache **Httpd** for reverse proxy and **Nginx** at backend instead.
can you share your configurations files of nginx and your proxy of your solution? I ask for your docker network too if its possible. @robeatoz

**Comment by robeatoz** [comment]
@Dnhatsave 

> can you share your configurations files of nginx and your proxy of your solution?

I use the [nginx-proxy-manager](https://github.com/NginxProxyManager/nginx-proxy-manager) in my setup because it handles all the proxy stuff I prefer not to handle manually. 
It generates all configuration files. 
I'm not a Nginx pro, but the interesting part looks like:

```conf
server {
  set $forward_scheme http;
  set $server         "onlyoffice-documentserver";
  set $port           80;

  listen 80;
  listen [::]:80;

  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name onlyoffice.publicdomain.de;
  proxy_set_header Upgrade $http_upgrade;
}
```

> I ask for your docker network too if its possible

I use docker-compose and the network created on the startup of this docker-compose. Furthermore, I did not create an external docker-network
