### ISSUE TITLE
Using External nginx configurations

### ISSUE THREAD

**Issue by Dnhatsave** [ONLYOFFICE/Docker-DocumentServer#413]
Hi everyone,

I'm trying to use external configurations files for nginx.
I've achieve these goal by using Docker file running the script below to edit directly the ds.conf.tmpl inside a container:

`RUN sed -i "s/80/8089/g" /etc/onlyoffice/documentserver/nginx/ds.conf.tmpl`

As this is an temporally workaround solution, i like to know that its possible to use an external **ds.conf** and then copy into **/etc/nginx/conf.d** inside a docker container of onlyoffice image.

I already try to do that using the COPY comand inside my Dockerfile like that:
```

COPY config/ds.conf.tmpl /etc/onlyoffice/documentserver/nginx/
COPY config/ds.conf /etc/nginx/conf.d/
CMD ["/etc/init.d/nginx restart"]
```

But every time i try to do that the nginx server inside a docker image fails to start. what is wrong with these aproach? there is an better way to achieve that goal ???

Best Regards,
DIN.

**Comment by ShockwaveNN** [comment]
Hi, I think your changes may be reverted because we change nginx config on CMD stage in `run-document-server.sh`
https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh#L418

I think approach that will work will be
1. Allow `run-document-server.sh` to make all needed substitution
2. After DocumentServer container is successfully runs - make changes via `docker exec` command
I have an example [here](https://github.com/ONLYOFFICE-QA/documentserver-docker-updater/blob/master/after-run.sh#L15)

**Comment by Dnhatsave** [comment]
Thanks it works now,

I've change the **ONLYOFFICE_DATA_CONTAINER_PORT=$PORT** at `run-document-server.sh`

Then i've copy first the ds.conf.tmpl and then run-document-server.sh like that:
```

COPY ds.conf.tmpl /etc/onlyoffice/documentserver/nginx/
COPY run-document-server.sh /app/ds/run-document-server.sh
```

**Comment by Dnhatsave** [comment]
I don't want to change the port only, i want to create extra context for web proxy. and I'm not running the image using docker or docker compose. 
I'm using Marathon and Mesos to deploy and scale the onlyoffice image. that's why i need to separate the nginx configurations files.

**Comment by ShockwaveNN** [comment]
Ok fair enough

I agree that some settings cannot be changed via ENV vars and required changes in nginx.conf itself
And sorry never heard about Marathon/Mesos 

If I understand you right - you've resolved your problem with [this solution ](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/413#issuecomment-1067954971) and I'll close this issue, but feel free to comment if got any more questions
