### ISSUE TITLE
Docker-setup/testing error

### ISSUE THREAD

**Issue by boulder47** [ONLYOFFICE/Docker-DocumentServer#416]
**Do you want to request a *feature* or report a *bug*?**
 requesting help with setting up/testing.
using this docker git, pulled and replaced docker-compose.yml with my modified version to include persistant volumes.
using self-signed certs, named to defaults and placed in default locations. (for quick setup)

**What is the current behavior?**
browser error = "document could not be saved"
logs = error: ETIMEOUT
after error tried these:
wget to file : https://<server name>/example/track?filename=new.docx <-- 404 not found
curl to file : https://<server name>/example/track?filename=new.docx <-- 404

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
fresh docker install,
execute: "docker compose up -d" 
on completion of containers, copy over ssl certs to docker volumes certs dir. chown ds:ds on certs, chmod 400 ok key
chown ds:ds -R -> var/www/onlyoffice/documentserver-example/public (docker volume mapped)
execute: "docker restart <container id>"
browser -> access https://<server name>, displays /welcome page.
copy the Enable Example , and paste and run docker cmd.
Browser -> click go to /example , displays example page,
click on new doc/spreadsheet - go to new page -> loads the editor -> Wait 10 sec, -> error, cannot save 
-> wait 10 sec -> second error: download failed.

**What is the expected behavior?**
to open /example, create test document for testing editor functionality, verify document server is working correctly.

**Did this work in previous versions of DocumentServer?**
current version : 7.0.1. Build: 37

**DocumentServer Docker tag:**

**Host Operating System:**
Photon OS 4.0 Rev2 -> https://github.com/vmware/photon/wiki/Downloading-Photon-OS

attached : "docker-compose,yml" to replace the github version, & Logs dir from container with error codes.
[test.zip](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/8270607/test.zip)

**Comment by ShockwaveNN** [comment]
Seems it's some kind networkning error

Could you attach inside runnin DocumentServer container and check that your host `https://docsedit.blueflame47` is accesable

For example run `curl https://docsedit.blueflame47` inside container

For me this error looks like that DocumentServer container has no idea that is https://docsedit.blueflame47, maybe you should specify docker hosts (not sure how to do that, I think it's docker configuration problem and not related to our container per-se)

**Comment by ShockwaveNN** [comment]
Glad I've helped
