### ISSUE TITLE
Dokument size error PDF

### ISSUE THREAD

**Issue by ZID-TU-Graz** [ONLYOFFICE/Docker-DocumentServer#417]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Opening PDF file in nextcloud that's bigger than 100MB fails , even when we set file limits in default.json as described here
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/354#issuecomment-824678415
https://github.com/ONLYOFFICE/DocumentServer/issues/1674#issuecomment-1063371961

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open an pdf file greater than 100 (?) MB (tested size was 235MB)

![Bildschirmfoto_2022-03-18_21-05-24](https://user-images.githubusercontent.com/100593683/159076774-0f657de1-5e39-4f85-a05f-ce50bdbe63ce.png)
![Bildschirmfoto_2022-03-18_21-05-57](https://user-images.githubusercontent.com/100593683/159076771-69f8e6c6-85bd-4b9a-b692-5308b373c97f.png)

**What is the expected behavior?**
File opens

**Did this work in previous versions of DocumentServer?** no

**DocumentServer Docker tag:** 7.0.1 (latest)

**Host Operating System:** Debian

**Comment by ShockwaveNN** [comment]
Hi, could you share this file for me to check

**Comment by DonCarlosGraz** [comment]
@ShockwaveNN https://cloud.tugraz.at/index.php/s/tLN8J6t4PwHSgXq/download (I'll remove the file "soon")

**Comment by ZID-TU-Graz** [comment]
@ShockwaveNN https://cloud.tugraz.at/index.php/s/tLN8J6t4PwHSgXq/download

**Comment by ShockwaveNN** [comment]
Maybe you doing something wrong?

I've rechecked:

1. I've run latest stable docker
2. Wait until it finished booting
3. `docker exec -it <container_id> bash`
4. Pasted and executed
```
#!/usr/bin/env bash

sed -i -e 's/104857600/10485760000/g' /etc/onlyoffice/documentserver-example/production-linux.json

sed -i '9iclient_max_body_size 1000M;' /etc/onlyoffice/documentserver-example/nginx/includes/ds-example.conf
sed -i '16iclient_max_body_size 1000M;' /etc/nginx/nginx.conf

sed -i -e 's/104857600/10485760000/g' /etc/onlyoffice/documentserver/default.json
sed -i -e 's/50MB/5000MB/g' /etc/onlyoffice/documentserver/default.json
sed -i -e 's/300MB/3000MB/g' /etc/onlyoffice/documentserver/default.json

service nginx restart
supervisorctl restart all
```

And after that opened your file via `/example` and it opened (after rather lengthy wait)
![image](https://user-images.githubusercontent.com/668524/159223779-2b978da3-6c55-4ef2-a767-b2ef1683b72d.png)

**Comment by ShockwaveNN** [comment]
Maybe for some reason some files in your case have not sed-ed new values, please recheck all files manually

**Comment by ZID-TU-Graz** [comment]
you are right, it works now. I'll close this issue

**Comment by jiriks74** [comment]
If you'd like I'm maintaining a [Docker image](https://hub.docker.com/r/jiriks74/onlyoffice-documentserver) that has the option for larger files built in and can be set by a variable in `docker-compose.yml`. Everything can be found on my [GitHub repository](https://github.com/jiriks74/Docker-DocumentServer) if you're interested in how it works.

**Comment by jiriks74** [comment]
Try to do
```
'onlyoffice' =>
    array (
      "jwt_secret" => "yourSecret",
      "jwt_header" => "AuthorizationJwt"
  )
```
instead of 
```
'onlyoffice' =>
    array (
      "jwt_secret" => "yourSecret",
  )
```
Also, I need your onlyoffice config. If you don't use docker, I don't know where the config files are
