### ISSUE TITLE
rtl crying in the corner

### ISSUE THREAD

**Issue by firashacker** [ONLYOFFICE/Docker-DocumentServer#427]
the fact that rtl lack had been reported 5 year's ago and still the same annoying me i't the reason i can't use the suit

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

Sorry, we got no news about this, I cannot change priorities, it's better to contact sales@onlyoffice.com
