### ISSUE TITLE
ERROR: unknown database type

### ISSUE THREAD

**Issue by youhuowa** [ONLYOFFICE/Docker-DocumentServer#428]
**Do you want to request a *feature* or report a *bug*?*need some help*

**What is the current behavior?*docker run with errors*

**Did this work in previous versions of DocumentServer?*first deploy*

**DocumentServer Docker tag:*latest*

**Host Operating System:*ubuntu18.04*

I was trying to deploy an onlyoffice container, it worked perfectly when I ran
 `docker run -i -t -d -p 443:443 --restart=always \
-v /opt/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver`
 in the user guilds.

But I want some changes in the local.json file, so I ran
 `docker run -i -t -d -p 443:443 --restart=always -v /opt/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /opt/onlyoffice/config/local.json:/etc/onlyoffice/documentserver/local.json  onlyoffice/documentserver`

It ended up like this

root@seafile:~# docker logs --details -f 3b489837dcc6
 ERROR: unknown database type
 ERROR: unknown database type
 ERROR: unknown database type
 ERROR: unknown database type
 ERROR: unknown database type
 ERROR: unknown database type
 ERROR: unknown database type

The local.json in the host is basically default, I only add 'autoAssembly'
`{
  "services": {
    "CoAuthoring": {
      "sql": {
        "type": "postgres",
        "dbHost": "localhost",
        "dbPort": "5432",
        "dbName": "onlyoffice",
        "dbUser": "onlyoffice",
        "dbPass": "onlyoffice"
      },
      "token": {
        "enable": {
          "request": {
            "inbox": false,
            "outbox": false
          },
          "browser": false
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "secret"
        },
        "outbox": {
          "string": "secret"
        },
        "session": {
          "string": "secret"
        }
      }
	  "autoAssembly": {
        "enable": true,
        "interval": "5m"
        }
    }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}`

Am I missing something?

**Comment by dreua** [comment]
Please format your Json, this is very hard to read for humans ;)
Maybe you just missed a comma between the closing } and "autoAssembly"🤔

**Comment by youhuowa** [comment]
miss a comm indeed:sweat:, thx a lot
