### ISSUE TITLE
Full document crash when editing via OnlyOffice

### ISSUE THREAD

**Issue by brendan-pike** [ONLYOFFICE/Docker-DocumentServer#437]
When editing a docx file with tracking enabled for all if I perform a find/replace the document 'crashes', ie. editing is ceased and unavailable, I am forced to return to files and initiate a new onlyoffice edit of the file.

There are not errors in the docker onlyoffice/documentserver container logs or the nextcloud logs.  The user is shown a module pop-up which states 
```
An error occurred during the work with the document.
Use the 'Download as...' option to save the file backup copy to your computer hard drive.
```
In the browser console I get these errors:

`Error: Permission denied to access property "ownerDocument"`
and
`Uncaught TypeError: this.aa[b] is undefined
    hU https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7325
    hU https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7713
    Ar https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7666
    EQ https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:9696
    Qkd https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:9699
    u5f https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all-min.js:1106
    onQueryReplaceAll https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    forEach https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    g https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    forEach https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    onBtnClick https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    dispatch https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    handle https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    add https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    I https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    each https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:9
    each https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:9
    I https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    on https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    render https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20
    show https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:14
    show https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20
    showSearchDlg https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    onShortcut https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    o https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:67
    <anonymous> https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    <anonymous> https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    <anonymous> https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
[sdk-all.js:7325:189](https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js)
    hU https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7325
    hU https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7713
    Ar https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7666
    EQ https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:9696
    Qkd https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:9699
    u5f https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all-min.js:1106
    onQueryReplaceAll https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    forEach https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    g https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    forEach https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    fireEvent https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13
    onBtnClick https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    dispatch https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    handle https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    (Async: EventListener.handleEvent)
    add https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    I https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    each https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:9
    each https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:9
    I https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    on https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10
    render https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20
    show https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:14
    show https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20
    showSearchDlg https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    onShortcut https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    M https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    n https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8
    o https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:67
    <anonymous> https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    (Async: EventListener.handleEvent)
    f https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    <anonymous> https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68
    <anonymous> https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68`

Let me know if/how I can provide more information.
Thanks

**Comment by ShockwaveNN** [comment]
Hi, to track this issue we need something to be done:

1. Update to latest v7.1.0 and check if this error still occurs
2. If it's occurred - please create a new issue with step-by-step description (and probably file on which this error occurs) how to reproduce this problem

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
