### ISSUE TITLE
利用dzzoffice使用onlyoffice, 手动设置文件主版本为新建文件时的版本出现异常

### ISSUE THREAD

**Issue by xinaiwunai** [ONLYOFFICE/Docker-DocumentServer#438]
**Do you want to request a *feature* or report a *bug*?**
I want to report a *bug*。

**What is the current behavior?**
利用dzzoffice使用onlyoffice, 手动设置文件主版本为新建文件时的版本出现异常。
新建一个ppt文件，任意修改内容保存，会产生一个新版本。
然后在文件夹页面，将新建文件时的版本指定为主版本。
将导致该文件夹无法显示，原因为该版本下，文件名为null。
导致jsz执行时出现异常。

filemanage.js?KX4:1233 Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at Function._filemanage.Sort (filemanage.js?KX4:1233)
    at _filemanage.showIcos (filemanage.js?KX4:757)
    at Object.success (filemanage.js?KX4:107)
    at i (jquery.min.js?KX4:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?KX4:2)
    at A (jquery.min.js?KX4:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js?KX4:4)

![截图_选择区域_20220519095059](https://user-images.githubusercontent.com/37302121/169186715-73c77c3e-26fb-4299-a4ac-19636f72480e.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**
linux
user@user-PC:~/Desktop$ sudo docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                                                  NAMES
9f1074528f1c   onlyoffice/documentserver   "/app/ds/run-documen…"   5 minutes ago   Up 5 minutes   443/tcp, 0.0.0.0:9000->80/tcp, :::9000->80/tcp         reverent_tereshkova
75fae6c9d2b4   mysql:5.7.27                "docker-entrypoint.s…"   17 hours ago    Up 17 hours    0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   mysql
d28245bb0dc1   imdevops/dzzoffice:latest   "docker-php-entrypoi…"   18 hours ago    Up 18 hours    0.0.0.0:80->80/tcp, :::80->80/tcp                      dzzoffice

**Comment by ShockwaveNN** [comment]
Hi

First of all - we allow only English in our issue reports
Second - judging by your error - this has nothing to do with ONLYOFFICE DocumentServer, error is not from our source code
Third - we do not officially support `dzzoffice` and honestly, I don't know that it is, all documentation is on unknown language to me, but I think it's better to contact those guys

I'm closing this, since seems it's not related to us
