### ISSUE TITLE
Make OnlyOffice self-hosted version allow specifying our own self-hosted redirect URI

### ISSUE THREAD

**Issue by collaborate-ever** [ONLYOFFICE/Docker-DocumentServer#454]
**Do you want to request a *feature* or report a *bug*?**
Requesting for a new feature

**What is the current behavior?**
OnlyOffice self-hosted version expects us to specify "https://service.onlyoffice.com/oauth2.aspx" as the redirect URI in Google project to sync Google Drive to OnlyOffice Documents module.

**What is the expected behavior?**
Make OnlyOffice self-hosted version allow us to specify our own self-hosted redirect URI.  For e.g., if our self-hosted OnlyOffice is hosted at https://test.ourcompany.com then allow us to specify "https://test.ourcompany.com/oauth2.aspx" instead of making it mandatory to specify "https://service.onlyoffice.com/oauth2.aspx" for self-hosted software too.  If not possible, request you to let us know as to why cloud based https://service.onlyoffice.com/oauth2.aspx needs to be specified for synchronizing Google Drive into our self-hosted OnlyOffice package.

**Host Operating System:**
Linux CentOS

**Comment by ShockwaveNN** [comment]
Hi, I think this is issue is for CommunitySrever product, not DocumentServer, since I don't remember that DocumentServer using oauth URLs at all, am I right?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
