### ISSUE TITLE
js path missing on page load,Second-level domain name lost

### ISSUE THREAD

**Issue by nomatterfine** [ONLYOFFICE/Docker-DocumentServer#456]
api.js is loaded through vue like this https://idemo.com/onlineEditor/web-apps/apps/api/documents/api.js
![image](https://user-images.githubusercontent.com/90117583/177114709-1df7532b-da1d-4c11-b0db-ebb6006502ae.png)

The final access address is https://10.16.11.11:9000/web-apps/apps/api/documents/api.js

The relationship of domain name mapping is    idemo.com/onlineEditor/**onlineEditor**  --->10.16.11.11:9000

But when loading` https://idemo.com/onlineEditor/web-apps/apps/documenteditor/main/index.html`, directly switch to `https://idemo.com/7.1.1-23/web -apps/apps/documenteditor/main/index.html`；
 
Second-level domain name lost !   /onlineEditor lost !
The address required here is _https://idemo.com/onlineEditor_/7.1.1-23/web -apps/apps/documenteditor/main/index.html

![image](https://user-images.githubusercontent.com/90117583/177107948-9ac4b688-9f05-4e46-adb8-faee8119a3a0.png)

![image](https://user-images.githubusercontent.com/90117583/177108033-eabfa2e2-124a-4b3c-8553-b41b2f64929c.png)

I started it through docker, how should I configure to keep this second-level domain name so that the second-level domain name is not lost

**Comment by ShockwaveNN** [comment]
Hi, not sure but I think DocumentServer docker is not designed that way so it can be part of subdomain

In that case you should manually setup nginx and forward https://idemo.com/onlineEditor/web-apps/apps/documenteditor/main/index.html to https://10.16.11.11:9000/web-apps/apps/api/documents/api.js

**Comment by nomatterfine** [comment]
> Hi, not sure but I think DocumentServer docker is not designed that way so it can be part of subdomain
> 
> In that case you should manually setup nginx and forward https://idemo.com/onlineEditor/web-apps/apps/documenteditor/main/index.html to https://10.16.11.11:9000/web-apps/apps/api/documents/api.js

The nginx reverse proxy has been configured as demo.com/onlineEditor/**onlineEditor** ---> 10.16.11.11:9000 

这个路径https://idemo.com/onlineEditor/web-apps/apps/documenteditor/main/index.html会重定向到https://idemo.com/7.1.1-23/web -apps/apps/documenteditor/main/index.html，**二级域名/onlineEditor丢失了**

**Comment by nomatterfine** [comment]
> Hi, not sure but I think DocumentServer docker is not designed that way so it can be part of subdomain
> 
> In that case you should manually setup nginx and forward `https://idemo.com/onlineEditor/web-apps/apps/documenteditor/main/index.html` to `https://10.16.11.11:9000/web-apps/apps/api/documents/api.js`

This path` **https://idemo.com**/onlineEditor**/web-apps**/apps/documenteditor/main/index.html` will redirect to `https:/**/idemo.com/7.1.1-23**/web-apps/apps/documenteditor /main/index.html`, the second-level domain name **onlineEditor is lost**

**Comment by ShockwaveNN** [comment]
@igwyd Pleas take a look, if ever had experience with such configurations

**Comment by iqbalhasnan** [comment]
I'm also running into this issue. I believe something in the JS that makes the call to the root host instead of the proxy path. 

<table>
  <tr>
    <td>
<img width="800" alt="after" src="https://user-images.githubusercontent.com/794601/178905786-c75dc433-93cc-4dc2-98b4-76491fa06dbf.png">
    </td>
  </tr>
</table>


Iframe path is getting the correct one from the getBasePath function which is basically getting the proxy path from the api.js script tag

<table>
  <tr>
    <th>Script tag with proxy path</th>
    <th>Iframe gets the correct proxy path</th>
  </tr>
  <tr>
    <td>
<img width=“800” alt="before" src="https://user-images.githubusercontent.com/794601/178906419-e11b19ea-4fb8-482d-af49-ca3844d7dbfe.png">
</td>
    <td>
<img width=“800” alt="after" src="https://user-images.githubusercontent.com/794601/178906010-3e9466b3-62dc-4016-afad-ed39a8532e2e.png">
    </td>
  </tr>
</table>


```    
function getBasePath() {
        var scripts = document.getElementsByTagName('script'),
            match;

        for (var i = scripts.length - 1; i >= 0; i--) {
            match = scripts[i].src.match(/(.*)api\/documents\/api.js/i);
            if (match) {
                return match[1];
            }
        }

        return "";
    }
```

call to the cache/file endpoint should use the same getBasePath function to resolve it correctly ?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by imwower** [comment]
if use subFolder or not port 80, the config should be like:
```
      location /onlyoffice/ {
        proxy_pass https://{{DOCUMENTSERVER_ADDRESS}}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $proxy_connection;
        proxy_set_header X-Forwarded-Host $the_host:$server_port/onlyoffice;
        proxy_set_header X-Forwarded-Proto $the_scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```
the `onlyoffice` is your subFolder, the `server_port` is your custom port.
