### ISSUE TITLE
Documentation request: Docker Hub release schedule

### ISSUE THREAD

**Issue by dantefromhell** [ONLYOFFICE/Docker-DocumentServer#457]
As of 2022-07-06 Docker hub [1] lists version `7.1.1.23` (digest `8a1edcc13f9d`) as the most current release, while this repo has a variety of tags that indicate version number `7.2`.

It would be great if the documentation contains information what qualifies a release/ version for release on Docker Hub.

Thank you!!!

[1] https://hub.docker.com/r/onlyoffice/documentserver

**Comment by ShockwaveNN** [comment]
Hi, docker hub repo has always latest stable version in it, it will be 7.1.1.23 as of now

7.2 version is currently in development and may contain some critical bugs (and I can confirm that right now there is critical bugs in 7.2)

We don't use releases in this (Docker-DocumentServer) repo, and we use tags for our nightly builds

But we always release the Docker version at the same time as all other natives (exe, deb, rpm) versions so you can safely check for new releases here - https://github.com/ONLYOFFICE/DocumentServer/releases

And as soon as the DocumentServer repo has a new release - docker hub will have it in 100% of cases

**Comment by dantefromhell** [comment]
Thanks for clarifying @ShockwaveNN

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
