### ISSUE TITLE
Does not work on Manjaro Gnome + BTRFS Filesystem 

### ISSUE THREAD

**Issue by zilexa** [ONLYOFFICE/Docker-DocumentServer#469]
Continuing from here: 
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/426

My latest post:
Now that more people are using my docker compose example, others running Manjaro with BTRFS filesystem are also unable to get OnlyOffice Documentserver working. No issue with other docker images.

I know you spend time testing this, but us there a chance you can test this on a real machine instead of VM and by selecting BTRFS (no swap) as filesystem during installation?

Compose used: 
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/426#issuecomment-1127634160

log from today: 

```
Waiting for connection to the officedb host on port 5432
Waiting for connection to the officedb host on port 5432
Waiting for connection to the officedb host on port 5432
Waiting for connection to the officedb host on port 5432
Waiting for connection to the officerabbitmq host on port 5672
Waiting for connection to the officerabbitmq host on port 5672
Waiting for connection to the officerabbitmq host on port 5672
Waiting for connection to the officerabbitmq host on port 5672
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:4: NOTICE:  table "doc_callbacks" does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:9: NOTICE:  function merge_db(pg_catalog.varchar,int2,int8,pg_catalog.timestamp,pg_catalog.varchar,int8,int8) does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:10: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,pg_catalog.varchar,int4,int4) does not exist, skipping
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron
   ...done.
 * Starting nginx nginx
   ...done.
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx
   ...done.
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2022-07-24T18:28:37.999] [WARN] nodeJS - update cluster with 1 workers
[2022-07-24T18:28:38.011] [WARN] nodeJS - worker 419 started.
[2022-07-24T18:28:38.015] [WARN] nodeJS - update cluster with 1 workers
[2022-07-24T18:29:29.733] [WARN] nodeJS - update cluster with 1 workers
[2022-07-24T18:29:29.740] [WARN] nodeJS - worker 482 started.
[2022-07-24T18:29:29.743] [WARN] nodeJS - update cluster with 1 workers

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2022-07-24T18:28:38.835] [WARN] nodeJS - Express server starting...
[2022-07-24T18:28:38.837] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-07-24T18:28:38.900] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.1.1. Build: 23
[2022-07-24T18:29:29.096] [WARN] nodeJS - Express server starting...
[2022-07-24T18:29:29.100] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-07-24T18:29:29.181] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.1.1. Build: 23

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
24 Jul 18:28:37 - [376] reading config file: ./config/config.js
24 Jul 18:28:37 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==
```

result: 
`localhost:8811` still loads forever (and ever and ever) 

I am not using a VM. This has been tested on multiple devices and since I published my compose on github, more users using Manjaro Gnome with BTRFS filesystem (no swap) have the exact same issue. 

Port 80 and 443 are forwarded in my router to this system for other purposes. This should not affect OnlyOffice at all. 
I see in the log, NodeJS is listening to port 8000. Could this be the culprit? 
Is there an issue with this part in my compose: 
```
    ports:
      - 8811:80
```

Also notice from the previous issue, the image simply fails for RabbitMQ and PostGres so I have to use seperate containers for those, as you can see in my compose. 
This is STILL the case, this has not been solved. Since this has not been solved, please do not close this issue. 

I see 3 or 4 issues when using this image via Docker Compose on Manjaro Gnome with BTRFS filesystem (not in a VM): 

1. Image fails to work with built in RabbitMQ
2. Image fails to work with PostGres
3. Image might have NGINX issues, but nginx error log is empty. 
4. Page loads forever, even when you use seperate (working) containers for RabbitMQ and PostGres

**Comment by ShockwaveNN** [comment]
Hi

>  on a real machine instead of VM and by selecting BTRFS (no swap) as filesystem during installation

Is there is a really need to have a separate real machine to test that? I'm not sure that I can get access to any extra machine to setup non-virtualized version of Arch and BTRFS

Correct me if I'm wrong, but if I use VirtualBox with Manjaro in it and use BTRFS as FS, it will probably have the same result as native BTRFS?

**Comment by zilexa** [comment]
All I know is: 
- the image does not work on Manjaro Gnome with BTRFS filesystem, fully up to date, Docker and Compose installed. 
- there are several unresolved issues that you also confirmed (the issues with built in RabbitMQ and PostgreSQL). 
- you confirmed the compose example with minimal set of elements but with separate containers for RabbitMQ and DB works in a VM. 
- I can confirm it does not work outside VM. 

I suspect NGINX is the culprit, but since zero error reporting is provided, you and I can only guess what is happening. The log says its up and running, the page loads forever with each test. 

I could not even imagine host OS being an issue for this image, but it was. I do not know why, since it uses elements such as RabbitMQ, PostgreSQL, NGINX that work totally fine built into other docker images. 

This means something does go wrong that seems to be OS specific. Perhaps also Docker-filesystem driver specific. When it comes to OS and filesystem specific stuff, indeed things can be different from VM perspective.

But I do agree with you, we should not need to go through hoops to perform these (blind) tests, because we are both really blind here without more information about what is really going on when the container is initiated. There is just too little error reporting (none!), even though the log clearly shows it creates ` err.log` files, they are always empty.

**Comment by ShockwaveNN** [comment]
> It would be helpful if a developer could shine a light as to what non-standard/uncommon configuration they are applying.

There is literally zero private code for OpenSource version of DocumentServer so you can dig in source code and try to find out yourself, not sure that anything has to do with FS itself, so it may be issue with some of our dependencies, since I don't think we have any direct read-write to FS without libraries

I'll try to setup Manjaro VM with BTRFS then I got some free time

**Comment by ShockwaveNN** [comment]
Oops sorry, my bad

After a little wait connection to 5432 established, we long was longer that usual but it's connected

**Comment by ShockwaveNN** [comment]
It's loaded file on specified port without any troubles

![image](https://user-images.githubusercontent.com/668524/180815223-4d9d9c67-06fe-4d8c-9e09-176f27bc2f47.png)

**Comment by zilexa** [comment]
Now I really do not understand what else can be the difference between our systems. Sorry but I tried everything I could and I know at least 3 others with exact same experience. I've asked them to create a GitHub account and post here.

I am not a developer. I do not know anything about coding. Pointing a user to do a developers task doesn't make much sense. 
Everything I know about docker compose is by googling and reading some documentation. 

I guess then I give up. Without proper error messaging, there is nothing left for me to do.


Why do you not confirm my other points? Because you keep referring to my compose that works, but that by itself is a workaround because of the image failing to get RabbitMQ and the DB working. 
So please confirm at least that there are definitely issues with the image itself.

**Comment by ShockwaveNN** [comment]
> Why do you not confirm my other points? Because you keep referring to my compose that works, but that by itself is a workaround because of the image failing to get RabbitMQ and the DB working.
> So please confirm at least that there are definitely issues with the image itself.

Sorry, but I do not understand that I can check

I can agree with you that some issue exists for some specific setup
Is this issue only for DocumentServer? I don't thinks so, I think it's more an issue with docker itself, since it's got trouble starting some 3rd party services required by DocumentServer

Can I reproduce an issue and file some kind of issue in any kind of issue tracker (ours or some other produce) - no, because this issue raised several time and not even once I've reproduced it on my hardware

**Comment by zilexa** [comment]
But you keep using my Compose. Can you confirm all those test work with the built in RabbitMQ and DB? Because those are bypassed by my compose, remember?

**Comment by ShockwaveNN** [comment]
> Can you confirm all those test work with the built in RabbitMQ and DB

If you mean the simplest setup possible with

```
docker run -itd -p 80:80 onlyoffice/documentserver
```

I've rechecked it now and can confirm that it's started fine on Manjaro BTRFS without any troubles

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
