### ISSUE TITLE
Failed on starting RabbitMQ

### ISSUE THREAD

**Issue by lindeer** [ONLYOFFICE/Docker-DocumentServer#476]
start docker container as wiki:
```
mkdir logs data lib rabbitmq redis db
docker run -it -p 9000:80 \
    -v logs:/var/log/onlyoffice  \
    -v data:/var/www/onlyoffice/Data  \
    -v lib:/var/lib/onlyoffice \
    -v rabbitmq:/var/lib/rabbitmq \
    -v redis:/var/lib/redis \
    -v db:/var/lib/postgresql  onlyoffice/documentserver
```
failed on `Starting RabbitMQ` after nearly 30 minutes:
```
 * Starting PostgreSQL 12 database server                                           [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                                                                    
 * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}                                        [fail]
```
but when I logged in container, both `startup_log` and `startup_err` are empty:
```
root@1c932e2c6873:/# ll /var/log/rabbitmq
total 56
drwxr-xr-x. 1 rabbitmq rabbitmq  4096 May 30 00:35  ./
drwxr-xr-x. 1 root     root      4096 Aug 14 05:53  ../
drwxr-xr-x. 2 rabbitmq rabbitmq  4096 May 30 00:33  log/
-rw-r--r--. 1 rabbitmq rabbitmq 19050 May 30 00:35 'rabbit@373ec734943c.log'
-rw-r--r--. 1 rabbitmq rabbitmq    66 May 30 00:33 'rabbit@373ec734943c_upgrade.log'
-rw-r--r--. 1 root     root         0 May 30 00:35  shutdown_err
-rw-r--r--. 1 root     root       174 May 30 00:35  shutdown_log
-rw-r--r--. 1 rabbitmq rabbitmq     0 Aug 14 06:01  startup_err
-rw-r--r--. 1 rabbitmq rabbitmq     0 Aug 14 06:01  startup_log
```
and console output is:
```
Waiting for connection to the localhost host on port 5672
Waiting for connection to the localhost host on port 5672
Waiting for connection to the localhost host on port 5672
```
my host info:
```
$ docker images 
REPOSITORY                  TAG              IMAGE ID       CREATED              SIZE
onlyoffice/documentserver   latest           5a50e3a2d2ed   2 months ago         2.93GB

$ uname -ar
Linux lenovo 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/meminfo 
MemTotal:        7941348 kB
MemFree:          356780 kB
MemAvailable:    4935752 kB
Buffers:          727312 kB
Cached:          3746372 kB
SwapCached:           44 kB
Active:          1863568 kB
Inactive:        4491144 kB
Active(anon):      44160 kB
Inactive(anon):  2163052 kB
Active(file):    1819408 kB
Inactive(file):  2328092 kB
Unevictable:      102648 kB
Mlocked:             808 kB
SwapTotal:      12004344 kB
SwapFree:       11991544 kB
Dirty:              3552 kB
Writeback:             0 kB
AnonPages:       1983736 kB
Mapped:           736908 kB
Shmem:            327480 kB
KReclaimable:     738700 kB
Slab:             920376 kB
SReclaimable:     738700 kB
SUnreclaim:       181676 kB
KernelStack:       14560 kB
PageTables:        47520 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    15975016 kB
Committed_AS:   10414348 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       68328 kB
VmallocChunk:          0 kB
Percpu:             7008 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      438100 kB
DirectMap2M:     7759872 kB
DirectMap1G:     1048576 kB
```

**Comment by ShockwaveNN** [comment]
Hi, I think there may be something to do with permissions to mount the folder

Could you try to run 

`docker run -it -p 9000:80 \onlyoffice/documentserver` without any mounts, check that it worked and start adding mount one by one to find out which is causing this trouble

**Comment by lindeer** [comment]
> `docker run -it -p 9000:80 \onlyoffice/documentserver` without any mounts, check that it worked and start adding mount one by one to find out which is causing this trouble

hi @ShockwaveNN , I tried as you said without any volume mounts `docker run -it -p 9000:80 onlyoffice/documentserver`, but it did not work and result was same.

**Comment by ShockwaveNN** [comment]
@lindeer Ok, thanks

Seems this may be same issues as
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/469
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/386
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/426

But I was not able to reproduce this issue even once on my own Arch or non-arch based system, I think it's more a Docker issue than some issue on our side, but without some specific ways to setup my Arch to reproduce that I don' think we can help in any way

**Comment by lindeer** [comment]
hi @ShockwaveNN , I'm trying to build onlyoffice docker image on another machine and I had a question about Dockerfile. This machine is `arm64` arch, so the base image `ubuntu:20.04` pulled from hub is `arm64` arch, and `PACKAGE_URL` in Dockerfile should end with `_arm64.deb`, am I right? Thanks.

**Comment by ShockwaveNN** [comment]
> and PACKAGE_URL in Dockerfile should end with _arm64.deb, am I right?

Yeah, I think so

But plese keep this issue in line with original topic, you can ask question in discussion

**Comment by lindeer** [comment]
ok @ShockwaveNN :smiley:, I built local images 'case I tried to start onlyoffice service in another machine, but still failed, took me a long time to find the cause of  incompatible arch :innocent:, not a bit out of box...

**Comment by ShockwaveNN** [comment]
> not a bit out of box...

I don't think it was checked to build on an arm architecture
Why did you try our official arm image, without building it manually?

**Comment by lindeer** [comment]
thanks for reminding, just found the `latest-arm64` tag :sweat_smile:

**Comment by lindeer** [comment]
Finally, it worked on my arm machine!
```
$ docker images
onlyoffice/documentserver   latest-arm64        bd99d7503a3b
$ uname -ar
Linux wesley-UOS 4.19.71-arm64-desktop #1 SMP PREEMPT Thu Jul 15 14:18:15 CST 2021 aarch64 GNU/Linux
$ docker --version
Docker version 19.03.8, build e781081667
```

and I also upgraded my Fedora36 to latest: `Linux lenovo-f31 5.18.17-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 11 14:36:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` with docker version `Docker version 20.10.17, build 100c701`, not sure which side cause the issue, system or docker.
