### ISSUE TITLE
Highliting Problem

### ISSUE THREAD

**Issue by Dratonix** [ONLYOFFICE/Docker-DocumentServer#479]
**Do you want to request a *feature* or report a *bug*?**
report a "bug"
**What is the current behavior?**
Basically I highlight something and if I restart onlyoffice I can't unhighlight the highlited text

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
highlight text, restart onlyoffice, try to unhighlight text, fail
**What is the expected behavior?**
unhighlight text
**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**
Linux

**Comment by Dratonix** [comment]
Sorry if I put this bug in the wrong place, I'm kinda new to github

**Comment by ShockwaveNN** [comment]
Sorry, I don't get that do you mean by `unhighlight text, fail`

Are you selecting `no highlight` in menu?

I think if you record video it will help us detect a problem

**Comment by Dratonix** [comment]
I think someone fixed it

**Comment by ShockwaveNN** [comment]
I do not understand what do you mean by `someone fixed it`? 

I can guess this issue is resolved for you?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
