### ISSUE TITLE
Email management tool with docker-compose? 

### ISSUE THREAD

**Issue by hermesalvesbr** [ONLYOFFICE/Docker-DocumentServer#493]
**Do you want to request a *feature* or report a *bug*?**
FEATURE
**What is the current behavior?**
MAIL DIDN'T INSTALLED

Would it be possible, via docker, to have webmail properly installed next to the document server?
Any environment variables that enable this, or some script?

https://www.onlyoffice.com/en/mail.aspx

**Comment by ShockwaveNN** [comment]
Mail-related products are not the part of DocumentServer

Link you've shared if for CommunityServer, please check CommunityServer documentation and create an issue in appropriate repo if some problem occurs
