### ISSUE TITLE
Use external MySQL server

### ISSUE THREAD

**Issue by as-com** [ONLYOFFICE/Docker-DocumentServer#5]
In the community server Docker container, there is an option to use an external MySQL server (i.e, not inside the container). Could you please add such an option here? The second MySQL server inside the container is using too much RAM.

**Comment by ibnpetr** [comment]
Thank you very much for your suggestion.
This feature will be added soon.

**Comment by agolybev** [comment]
Fixed, see a [configuration parameters](https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters)

**Comment by amaccuish** [comment]
Hi. I can't find the option to use an external mysql server. For the time being I've overriden the /etc/onlyoffice/documentserver/default.json file to use my mysql server. Is there a clean way to pass this information via env variables?

**Comment by ShockwaveNN** [comment]
@amaccuish https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/README.md#available-configuration-parameters
you can use env params `POSTGRESQL_SERVER_HOST` and etc to configure it
