### ISSUE TITLE
Can't edit a file using reverse-proxy

### ISSUE THREAD

**Issue by Kcchouette** [ONLYOFFICE/Docker-DocumentServer#50]
**Do you want to request a *feature* or report a *bug*?** To my mind it's a bug.

**What is the current behavior?** Doesn't open the iframe.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Using nextcloud on server1 with HTTPS enable + a domain name, using nginx
- Having documentserver installed using docker on server2, no HTTPS, no domain name

- To use onlyoffice from server2 on the server1 through nextcloud, I need to have HTTPS. So I've created on server1 a reverse-proxy thing:

```
location /onlyoffice/ {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://IP_SERVER_2/;

        # Proxy websockets
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
}
```
- On the nextcloud extension, I've indicated `https://DOMAINE-NAME-SERVER1/onlyoffice`

.The error I've seen on the web console is: `Refused to frame 'https://IP_SERVER2/201X-0X-XX/web-apps/apps/documenteditor/main/inde…&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor' because it violates the following Content Security Policy directive: "frame-src https://DOMAIN_NAME_SERVER1/onlyoffice/".`

We can see that frame is coming from HTTPS of the SERVER 2, but HTTPS is not enable so even without the refused-frame, I'll fail.

**What is the expected behavior?**

Can see the iframe to edit the document

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

Last DocumentServer Docker version as May 13th 2017, browser Mozilla Firefox and Chrome are affected, OS I've installed on Debian Jessie.

Thank you very much :)

**Comment by agolybev** [comment]
Hello,
You must add the X-Forwarded-Host header with the host name and location to the requests sent to the ONLYOFFICE DocumentServer.
Like this:
```
location /onlyoffice/ {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Host $http_host/onlyoffice;
 
        proxy_pass http://IP_SERVER_2/;

        # Proxy websockets
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
}
```
See the similar example [here](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-to-virtual-path.conf)

**Comment by inbjo** [comment]
> Hello, You must add the X-Forwarded-Host header with the host name and location to the requests sent to the ONLYOFFICE DocumentServer. Like this:
> 
> ```
> location /onlyoffice/ {
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header X-Forwarded-Port $server_port;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>         proxy_set_header X-Forwarded-Host $http_host/onlyoffice;
>  
>         proxy_pass http://IP_SERVER_2/;
> 
>         # Proxy websockets
>          proxy_http_version 1.1;
>          proxy_set_header Upgrade $http_upgrade;
>          proxy_set_header Connection "upgrade";
> }
> ```
> 
> See the similar example [here](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-to-virtual-path.conf)

thank you, it's help for me. 👍
