### ISSUE TITLE
Multiple Cert-files break run-document-server.sh

### ISSUE THREAD

**Issue by J-a-x-u** [ONLYOFFICE/Docker-DocumentServer#502]
The recent change in run-document-server.sh breaks SSL if one has the host's certificate and intermediate certificates in separate files, thus *.crt expands to multiple files an leads to an error.

https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/ad066be1c82813514da3cfd4ee768d098c5a741f/run-document-server.sh#L44

I would propose to check for *.key instead since this should always be only one file:
`if [[ -d ${DATA_DIR}/certs ]] && [ -e ${DATA_DIR}/certs/*.key]; then`

**Comment by igwyd** [comment]
Hello @J-a-x-u. I don't think it's necessary. Сommon practice to bundle all certs into one file, it will be your certificate. We use the fullchain in our [nginx ](https://github.com/ONLYOFFICE/document-server-package/blob/master/common/documentserver/nginx/ds-ssl.conf.tmpl.m4#L39)config anyway.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
