### ISSUE TITLE
Bugs in example

### ISSUE THREAD

**Issue by murrometz** [ONLYOFFICE/Docker-DocumentServer#505]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I install onlyoffice/documentserver and follow all the recomendations, but when I'm trying to use the installed example - I get an error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. sudo docker run -i -t -d -p 1082:80 onlyoffice/documentserver
2. sudo docker exec 4b9090d54f43 /var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
3. sudo docker exec 4b9090d54f43 sudo supervisorctl start ds:example
4. sudo docker exec 4b9090d54f43 sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf
5. Go to http://localhost:1082/welcome/ in browser
6. Go to text example http://localhost:1082/example/
7. Click Document in the left top corner block "Create new"
8. As a result I always get this error:
"The document could not be saved. Please check connection settings or contact your administrator.
When you click the 'OK' button, you will be prompted to download the document."
followed by 
"Download failed"

Though the files in "Your documents" at http://localhost:1082/example/ that were created automatically are downloading correctly.

**What is the expected behavior?**
User can create a file or upload a new one

**Did this work in previous versions of DocumentServer?**
I don't know. I am a new user

**DocumentServer Docker tag:**
onlyoffice/documentserver:latest

**Host Operating System:**
Ubuntu 20.04.1 LTS
Docker 20.10.7

**Comment by ShockwaveNN** [comment]
Hi, you shouldn't use localhost in your browser.
Use your local IP or external IP

**Comment by AndreySolod** [comment]
Hi, I have the same problem, and use 127.0.0.1 didn't work;
I want to note that when using 80:80 everything works correctly (even as localhost) (443:443 not tested).

**Comment by AndreySolod** [comment]
Ok, I figured out the problem
Need instead of using http://localhost:81 / or http://127.0.0.1:81 use http://192.168.0.1:81 - why so I do not know.
There are also some problems with docker network, as I wrote in https://github.com/ONLYOFFICE/onlyoffice-redmine/issues/49

**Comment by igwyd** [comment]
@AndreySolod  it's because docker inside the container resolves to the localhost container's IP address, you should use IP address instead of localhost.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
