### ISSUE TITLE
No compatibility with Chrome and self-signed Cert

### ISSUE THREAD

**Issue by TautFlorian** [ONLYOFFICE/Docker-DocumentServer#51]
Hey guys,

im not sure if this is a bug but it should be noticed anywhere.
I'm using Nextcloud and OnlyOffice Documentserver.

I generated self-signed certs for both systems.

When i try to open a document in my nextcloud im recieving the following error:
![1111unbenannt](https://cloud.githubusercontent.com/assets/18403881/26192308/75d22dfa-3bb1-11e7-8dea-99fbfe3d61b2.PNG)

No errors where shown in the logs.
When i access my documentserver via browser and accept the following warning:
![22222](https://cloud.githubusercontent.com/assets/18403881/26192316/7b4a5636-3bb1-11e7-8fc6-c9c90527729b.PNG)

The Documentserver says "Documentserver is running"

And now i can edit Files within my Nextcloud.

**Probably the error is shown because of the warning chrome shows when accessing a website with an invalid cert and because of this nextcloud cant connect to the documentserver.

With Firefox this is working**

**Comment by JohnPerkin** [comment]
Hello @FlorianTaut !
We would recommend to use letsencrypt.org certificates instead of self-signed. Then Chrome will stop to take the connection as untrusted.

**Comment by FlorianTaut** [comment]
@JohnPerkin Yes would be possible, but not for internal usage. Letsencrypt doenst work for internal IP's.
This is just a Problem if you use it internal and access it via IP and not via f.e. office.domain.com for which you could request a SSL-Cert from Letsencrpyt.

**Comment by thomass4t** [comment]
You should create your certificates and sign it with one CA.
Import this CA into the trusted ceriticates (Vertrauenswürdige Stammzertifizierungsstellen).
This will prevent the warning in IE, Chrome and Edge.
The CA can also be distributed via GPO.

**Comment by ShockwaveNN** [comment]
I'll close this issue, since it's pretty old
If issue still actual please create new issue
