### ISSUE TITLE
table "doc_changes" was cleared

### ISSUE THREAD

**Issue by suibber** [ONLYOFFICE/Docker-DocumentServer#515]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
i use external mariadb ，when i chart on onlyoffice web, i found data has been store to table "doc_changes", but when i restart the server, table "doc_changes" was cleared

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
restart the server

**What is the expected behavior?**
Data needs to be preserved

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer Docker tag:**
v6.x

**Host Operating System:**
linux x86

**Comment by suibber** [comment]
> 

Thank you for reply, i found when the session closed, the data will be cleared. Is that the product design?

So is there any need to persist the data？

**Comment by ShockwaveNN** [comment]
@suibber After the session is closed those changes are sent to the document stored in DMS and a new version of the document with the applied changes is built

If you need to store the diff I think it's should be done on the DMS side

DocumentServer is designed that way, that if there is currently no opened sessions and there is no unsaved document - it store no data and you can safely update it, or drop database table without loosing any data - all file data is stored in document in DMS

**Comment by suibber** [comment]
I see. Thank you for your patience
