### ISSUE TITLE
Error creating a document when port is different from 443

### ISSUE THREAD

**Issue by MrSnoozles** [ONLYOFFICE/Docker-DocumentServer#518]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.0.204

### Expected Behavior

I'm able to use the test example to create new documents.

### Actual Behavior

When creating or opening a document I get the following error

`Download failed. Press "OK" to return to document list.`

![grafik](https://user-images.githubusercontent.com/17496592/196421863-14ff569e-6608-499f-b915-f60f82ec12ce.png)

### Reproduction Steps

1. Setup Docker-DocumentServer
2. Map port 443 to 8433 and 80 to 8080
3. start the container
4. start the example project
5. create a blank document

### Additional information

When the DocumentServer is installed on the default ports (80 + 443) the example projects works correctly.
docker-compose.yml used: 
~~~
version: '3'
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:7.2
    container_name: "ddev-${DDEV_SITENAME}-onlyoffice"
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
    stop_grace_period: 60s
    volumes:
      - /home/me/webdev/www/docs/OnlyOfficeData/logs:/var/log/onlyoffice/logs
      - /home/me/webdev/www/docs/OnlyOfficeData/data:/var/www/onlyoffice/Data
      - /home/me/webdev/www/docs/OnlyOfficeData/lib:/var/lib/onlyoffice
      - /home/me/webdev/www/docs/OnlyOfficeData/rabbitmq:/var/lib/rabbitmq
      - /home/me/webdev/www/docs/OnlyOfficeData/redis:/var/lib/redis
      - /home/me/webdev/www/docs/OnlyOfficeData/db:/var/lib/postgresql

    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=mySecret
      - ONLYOFFICE_HTTPS_HSTS_ENABLED=false
~~~

**Comment by ShockwaveNN** [comment]
@MrSnoozles I think maybe specifying hostname via `--hostname` run param may help

Problems comes that inside container documentserver knows nothing about your host name, you can check it via connecting to container and ping your host name (in your current config, without specifying hostname) - I think it will fail

P.S. Moved this issue to correct repo

**Comment by MrSnoozles** [comment]
The problem I see is that the hostname of the document server is not configurable. When embedding the script I can not use the internal name, so I have to add

`<script type="text/javascript" src="https://docs.ddev.site:8443/web-apps/apps/api/documents/api.js"></script>`

to load the api successfully.

When the document gets saved, the editor calls the document manager to store the document. The request body then contains:

~~~
{
    'key': ...,
    'status': 2,
    'url': 'https://docs.ddev.site:8443/cache/files/data/23017468451666383355_8503/output.docx/output.docx?md5=dCqXY4ou2Hu2KbJ47I4Ipw&expires=1666384279&filename=output.docx',
}
~~~

Now the url should be the service name of the container  (in my case `https://ddev-docs-onlyoffice`) because the document manager doesn't know ´https://docs.ddev.site´.

**Comment by igwyd** [comment]
@MrSnoozles Of course, you will not be able to address by the name of the container outside the docker network, need external name. 

>Now the url should be the service name of the container (in my case https://ddev-docs-onlyoffice) because the document manager doesn't know ´[https://docs.ddev.site´](https://docs.ddev.xn--site%20-bfd/).

Configure your DNS server or ```extra_hosts``` in docker so that the container with the document manager knows where the document server is. Or you can to configure nginx for using virtual path, we have example [here](https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx).

**Comment by Rita-Bubnova** [comment]
I'll close this issue. Feel free to comment or reopen it if you got further questions.
