### ISSUE TITLE
port issue

### ISSUE THREAD

**Issue by CrotchBurnt** [ONLYOFFICE/Docker-DocumentServer#528]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I did `sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver`, when I tried to open files, docker logs shows this:
![02c4e32bf7de9380718a456913adb3e](https://user-images.githubusercontent.com/6418433/198497734-73b0bdc3-fa77-4e90-9b49-248cc1f1f69e.jpg)
Idk where did this ":80" comes from.

**What is the expected behavior?**
The port should be "8080" instead of "80"

**Did this work in previous versions of DocumentServer?**
Not know

**DocumentServer Docker tag:**
7.2.1

**Host Operating System:**
CentOS 7.5

**Comment by ShockwaveNN** [comment]
Juding by path (`/office/download/...`) - this comes from DMS, not DocumentServer, so please check connection settings in your nextcloud/owncloud/etc..

**Comment by CrotchBurnt** [comment]
because of misconfigured nginx
