### ISSUE TITLE
No changes in NC file system - but safed for OO

### ISSUE THREAD

**Issue by Huster-at-github** [ONLYOFFICE/Docker-DocumentServer#55]
XML documents can be edited in Onlyoffice, changes also saved.

But:

* No file versions
* No activities
* No time stamp change
* Files not synched to clients because of changes

I start Onlyoffice with this command:

    sudo docker run -i -t -d -p 8888:443 \
        -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
        -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
        onlyoffice/documentserver

When I append the lib folder as mount point to the docker start command

    sudo docker run -i -t -d -p 8888:443 \
        -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
        -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
        -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice  \
        onlyoffice/documentserver

then I get an Error at file opening and data inside the XML file is lost.

**Comment by agolybev** [comment]
Hello,
See my comment [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/54#issuecomment-304230708)

**Comment by Huster-at-github** [comment]
Thanks @agolybev ,

`chmod -R 777 /app/onlyoffice/`

and a container restart with this command
```
sudo docker run -i -t -d -p 8888:443  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files  onlyoffice/documentserver
```

helped. Now I can

* edit docx and xlsx files

Still not working:

* changes to files system / activities
* converting xls or doc files

Error log when trying to convert:

```
Error	onlyoffice	Failed download converted file: https://myNCdomain.com:8888/cache/files/conv_28078741495790019_docx/output.docx/output.docx?md5=m1pIhhRWDFDyPWzLHD-j8A==&expires=1498385642&disposition=attachment&ooname=output.docx	a minute ago
Error	PHP	file_get_contents(https://myNCdomain.com:8888/cache/files/conv_28078741495790019_docx/output.docx/output.docx?md5=m1pIhhRWDFDyPWzLHD-j8A==&amp;expires=1498385642&amp;disposition=attachment&amp;ooname=output.docx): failed to open stream: operation failed at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#267	a minute ago
Error	PHP	file_get_contents(): Failed to enable crypto at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#267	a minute ago
Error	PHP	file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed at /var/www/nextcloud/apps/onlyoffice/controller/editorcontroller.php#267	a minute ago
```

**Comment by Huster-at-github** [comment]
Added `-v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice  \` to docker start 

```
sudo docker run -i -t -d -p 8888:443  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files  onlyoffice/documentserver
```

Does not help.

**Comment by enboig** [comment]
I have the same problem. Anything else to test?

**Comment by agolybev** [comment]
Hello @enboig 
Could you please submit new issue and describe your problem there?

**Comment by teknoprep** [comment]
i am getting a very similar issue as well - this is the log output from onlyoffice docker image. It appears to have a local cache of changes this is why we can see them in onlyoffice app but when it comes to the changes being pushed to nextcloud we will not see them

[2017-08-26 13:12:26.866] [ERROR] nodeJS - sendServerRequest error: docId = 8489415036705492;url = https://gei-files.NEXTCLOUD_SERVER.com/index.php/apps/onlyoffice/track?doc=YWFo
TUkvRERuNVY1OVBMekFLZXNNOUFNeFNLdGpNYkxaTkkwTWNrQzdQdz0/eyJmaWxlSWQiOjg0ODk0LCJvd25lcklkIjoiMjYwQjE0MjgtQTYwOS00MDdELTkzMDItRUQzMDJEQTczNkMwIiwiYWN0aW9uIjoidHJhY2sifQ%3
D%3D;data = {"key":"8489415036705492","status":2,"url":"https://geicollabora.NEXTCLOUD_SERVER.com:8444/cache/files/8489415036705492_452/output.xlsx/output.xlsx?md5=3o5k7MbXaFMRdA
7wn3euww==&expires=1506345147&disposition=attachment&ooname=output.xlsx","changesurl":"https://geicollabora.NEXTCLOUD_SERVER.com:8444/cache/files/8489415036705492_452/changes.zip
/changes.zip?md5=DAiQSmo1zASwP61yz9oKlw==&expires=1506345147&disposition=attachment&ooname=output.zip","history":{"serverVersion":"4.3.6","changes":[{"created":"2017-08
-25 20:32:48","user":{"id":"3BF1F2CB-46F7-4962-9D6D-9A62464C97D4","name":"Michael Dornblum"}}]},"users":["3BF1F2CB-46F7-4962-9D6D-9A62464C97D4"],"actions":[{"type":0,"u
serid":"3BF1F2CB-46F7-4962-9D6D-9A62464C97D4"}],"lastsave":"2017-08-25T20:32:54.616Z","notmodified":false}
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:260:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
[2017-08-26 13:12:30.034] [ERROR] nodeJS - postData error: docId = 8489415036705492;url = https://gei-files.NEXTCLOUD_SERVER.com/index.php/apps/onlyoffice/track?doc=YWFoTUkvRERuN
VY1OVBMekFLZXNNOUFNeFNLdGpNYkxaTkkwTWNrQzdQdz0/eyJmaWxlSWQiOjg0ODk0LCJvd25lcklkIjoiMjYwQjE0MjgtQTYwOS00MDdELTkzMDItRUQzMDJEQTczNkMwIiwiYWN0aW9uIjoidHJhY2sifQ%3D%3D;data
 = {"key":"8489415036705492","status":1,"users":["3BF1F2CB-46F7-4962-9D6D-9A62464C97D4"],"actions":[{"type":1,"userid":"3BF1F2CB-46F7-4962-9D6D-9A62464C97D4"}]}
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:260:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by ShockwaveNN** [comment]
I'll close this issue, since it's pretty old
If issue still actual please create new issue at https://github.com/ONLYOFFICE/onlyoffice-nextcloud repo
