### ISSUE TITLE
Crashing due to automatic changing authorization method local.json and default.json

### ISSUE THREAD

**Issue by SaschaMuehl** [ONLYOFFICE/Docker-DocumentServer#570]
**Do you want to request a *feature* or report a *bug*?**
Bug (is also related to #556)

**What is the current behavior?**
After installation and testing the server sucessfully the jwt token isn't working anymore due to automatic changes (e.g. after restart of the container or the server, after approx. a day) in **local.json** and **default.json**.
After new installation or reconfiguration of the Docker-Container the server works well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Installing Onlyoffice with JWT enabled in Linux Docker: 
`docker run --name=ONLYOFFICEDOCKER -i -t -d -p 4433:443 -e JWT_ENABLED='true' -e JWT_SECRET='mypasswd' --restart=always -v logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data onlyoffice/documentserver`
2. Change values in installation i.a.w. https://helpcenter.onlyoffice.com/installation/docs-configure-jwt.aspx

    a.   Open the Docker Container :        
    `docker exec -it <dockernummer>   /bin/sh  ` 
    b. set all values in “header” to: “AuthorizationJwt”  (before “Authorization”)         
    `nano /etc/onlyoffice/documentserver/local.json`   
    c. set all value: “rejectUnauthorized” to false:
    `nano /etc/onlyoffice/documentserver/default.json`   
    d. goto https://onlyoffice.xXx.de/ and start test example
    e. supervisorctl restart ds:example

3. check, if https://onlyoffice.xXx.de/ works
4. Start Test example
5. Integrate server adress and JWT password in Nextcloud.

**What is the expected behavior?**
No automatic changes in local.json and default.json

**Host Operating System:**
Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-137-generic x86_64)
nginx version: nginx/1.23.3
PHP 8.1.14 (cli)

**How can I tell the container to not change the authorization method?
The system tells me the ds:example is just for testing purposes only but how can I start my own production/environment? (eg. ds:myserver)**

**Comment by weasam** [comment]
My situation is every time the docker restart it change my custom setting "AuthorizationJwt" back to "Authorization"

**Comment by wabadoo-wabadee** [comment]
same problem for me. secret in local.json changes on every startup. This is now almost 2 years old, any motivation to fix such an fundamental issue?

**Comment by igwyd** [comment]
Hello, sorry for the late reply. This is the correct behavior, [docker variables](https://github.com/ONLYOFFICE/Docker-DocumentServer?tab=readme-ov-file#available-configuration-parameters) work this way. If you need to change the jwt header or jwt secret, you will have to stop the old container and run a new one with the new data ```JWT_SECRET=new-secret``` and ```JWT_HEADER=new-header```. Because every time you restart the container, the variables you started with will be checked and applied.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by wabadoo-wabadee** [comment]
> Hello, sorry for the late reply. This is the correct behavior, [docker variables](https://github.com/ONLYOFFICE/Docker-DocumentServer?tab=readme-ov-file#available-configuration-parameters) work this way. If you need to change the jwt header or jwt secret, you will have to stop the old container and run a new one with the new data `JWT_SECRET=new-secret` and `JWT_HEADER=new-header`. Because every time you restart the container, the variables you started with will be checked and applied.

Thank you.

For anybody coming here via google who wants to set a secure jwt secret, here's how it's done (using docker-compose)

1. start you documentserver container

2. get the (randomized) secret via
`docker exec <container-id> sudo documentserver-jwt-status.sh`
3. save the secret in your environment variable / docker-compose / ...
4. restart the container with the variable set
`docker exec onlyoffice-documentserver documentserver-prepare4shutdown.sh; docker-compose down; docker-compose up -d`
