### ISSUE TITLE
pdf 打开报错：Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by YaKazama** [ONLYOFFICE/Docker-DocumentServer#589]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
在浏览器中打开、编辑 pdf 时，滚动页面，会出现 warning 提示及报错（如下图），在 F12 中可以查看到如题的报错信息。
![image](https://user-images.githubusercontent.com/46774332/223977577-511453d4-c7c1-412b-a1c5-76ce7350dc9d.png)
![image](https://user-images.githubusercontent.com/46774332/223979232-fc81ac74-f290-42f7-adde-c4fca4a2d27b.png)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. 在主界面，点击 Upload file 按钮，上传任意一个 pdf 文件
2. 打开已经上传的 pdf 文件
3. 上下滚动打开后的文件
**What is the expected behavior?**
能正常查看 pdf 文件
**Did this work in previous versions of DocumentServer?**
v7.3.3.45
**DocumentServer Docker tag:**
onlyoffice/documentserver:latest
**Host Operating System:**
macOS Ventura 13.2.1 , Google Chrome 110.0.5481.177

**Comment by starshowing** [comment]
怎么有中文的bug描述啊？

**Comment by igwyd** [comment]
Hello @YaKazama, sorry for the late reply. On github we communicate in English, correct your message please.

**Comment by igwyd** [comment]
@YaKazama i checked your scenario on the latest vesion 7.5.1 of the onlyoffice/documentserver:latest and this is not repited for me. Update your server and try it again. If the behavior is repeated, could you please provide that PDF file?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
