### ISSUE TITLE
How to build a docker image only with DocumentServer, nothing else....

### ISSUE THREAD

**Issue by gowy222** [ONLYOFFICE/Docker-DocumentServer#621]
Hi everyone,
I'm trying to build a minimal OnlyOffice Docker image using Dockerfile. 
I want to exclude any unnecessary components and dependencies to reduce the resource consumption. 
I also want to link the image to third-party SQL, RabbitMQ, AWS S3, and Redis using Docker environment and volumes via docker-compose.yml.
Can anyone provide some guidance on how to achieve this?

**Comment by festina-lente-z** [comment]
https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx

**Comment by trofim24** [comment]
@festina-lente-z thanks for your link. It's our instruction for Compiling ONLYOFFICE Docs
@gowy222 you could use it or [run our Docker](https://github.com/ONLYOFFICE/Docker-DocumentServer#running-docker-image)
