### ISSUE TITLE
/var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by wangchangkui** [ONLYOFFICE/Docker-DocumentServer#644]
I am using version 7.4。but now i find logs have one error .why not find socket.io.min.js.map?

**Comment by igwyd** [comment]
Hello @wangchangkui, because socket.io not provide distribution without .map, this message is for debugging and does not affect the operation of the ONLYOFFICE-Docs.  I can confirm, this is bug, issue #61138

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/763.
