### ISSUE TITLE
Endless error loop of rabbitmq connection issue

### ISSUE THREAD

**Issue by pop4ever** [ONLYOFFICE/Docker-DocumentServer#647]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Install together with traefik 2 within the same docker compose file. postgresql and rabbitmq work fine without any error. However, the document server raise endless error loop of rabbitmq connection issue when it starts compeletly. The error message is shown below. I changed the AMQP_URI from rabbitmq hostname to IP address, but it would won't solve the problem. The error ouptup shows that the document server is still trying to connect to the IP of 127.0.0.1.

![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/20612221/bac22ce7-71d7-47fd-9b0b-fd73508f6df6)

"[ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672"
2023-07-23T05:20:33.393944694Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use the latest docker compose file with minor changes to setup traefik together.

**What is the expected behavior?**
Is the error by design? and actually there is no negative impact with it at all?

**Did this work in previous versions of DocumentServer?**
N/A

**DocumentServer Docker tag:**
Latest

**Host Operating System:**
Debian 11 LXC container in PVE7.4

**Comment by pop4ever** [comment]
BTW, I believe it's a bug instead of by design. Since I encountered 520 bad gateway error when I accessed the healthcheck webpage. Therefore I can't integrate it with nextcloud.

**Comment by igwyd** [comment]
Hello @pop4ever, sorry for the late reply. If the ampq connection error still appears, then the connection has not been established. It works as planned. How you changed connection(describe it please)? Show parts of apmq config in ```/etc/onlyoffice/documentserver/local.json``` and ```/etc/onlyoffice/documentserver/default.json```

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
