### ISSUE TITLE
Docker compose setup failed, ttf-mscorefonts-installer loop

### ISSUE THREAD

**Issue by post-duif** [ONLYOFFICE/Docker-DocumentServer#649]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

#0 134.2 ttf-mscorefonts-installer: processing...
#0 134.2 ttf-mscorefonts-installer: downloading http://downloads.sourceforge.net/corefonts/andale32.exe
Err:1 http://downloads.sourceforge.net/corefonts/andale32.exe
#0 135.2   Redirection loop encountered
E: Failed to fetch http://downloads.sourceforge.net/project/corefonts/the%20fonts/final/andale32.exe?download&failedmirror=deac-riga.dl.sourceforge.net  Redirection loop encountered
#0 135.2 E: Download Failed
#0 135.5 Created symlink /etc/systemd/system/timers.target.wants/update-notifier-download.timer → /lib/systemd/system/update-notifier-download.timer.
#0 135.6 Created symlink /etc/systemd/system/timers.target.wants/update-notifier-motd.timer → /lib/systemd/system/update-notifier-motd.timer.
#0 135.6 Setting up ubuntu-mono (20.10-0ubuntu2) ...
#0 135.8 Setting up ttf-mscorefonts-installer (3.8ubuntu2) ...
#0 136.0 Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
#0 136.1 Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.2) ...
#0 136.1 Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
#0 136.3 msttcorefonts failed to download
------
failed to solve: process "/bin/sh -c echo \"#!/bin/sh\\nexit 0\" > /usr/sbin/policy-rc.d &&     apt-get -y update &&     apt-get -yq install wget apt-transport-https gnupg locales lsb-release &&     locale-gen en_US.UTF-8 &&     echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections &&     apt-get -yq install         adduser         apt-utils         bomstrip         certbot         curl         gconf-service         htop         libasound2         libboost-regex-dev         libcairo2         libcurl3-gnutls         libcurl4         libgtk-3-0         libnspr4         libnss3         libstdc++6         libxml2         libxss1         libxtst6         mysql-client         nano         net-tools         netcat-openbsd         nginx-extras         postgresql         postgresql-client         pwgen         rabbitmq-server         redis-server         software-properties-common         sudo         supervisor         ttf-mscorefonts-installer         xvfb         zlib1g &&     if [  $(ls -l /usr/share/fonts/truetype/msttcorefonts | wc -l) -ne 61 ];         then echo 'msttcorefonts failed to download'; exit 1; fi  &&     echo \"SERVER_ADDITIONAL_ERL_ARGS=\\\"+S 1:1\\\"\" | tee -a /etc/rabbitmq/rabbitmq-env.conf &&     sed -i \"s/bind .*/bind 127.0.0.1/g\" /etc/redis/redis.conf &&     sed 's|\\(application\\/zip.*\\)|\\1\\n    application\\/wasm wasm;|' -i /etc/nginx/mime.types &&     pg_conftool $PG_VERSION main set listen_addresses 'localhost' &&     service postgresql restart &&     sudo -u postgres psql -c \"CREATE USER $ONLYOFFICE_VALUE WITH password '$ONLYOFFICE_VALUE';\" &&     sudo -u postgres psql -c \"CREATE DATABASE $ONLYOFFICE_VALUE OWNER $ONLYOFFICE_VALUE;\" &&     service postgresql stop &&     service redis-server stop &&     service rabbitmq-server stop &&     service supervisor stop &&     service nginx stop &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I downloaded the official repo, ran docker compose up, and got this error.

**What is the expected behavior?**

It should work.

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**
Ubuntu 22.04

Tried everything, nothing works. These steps also didn't help: https://bugs.launchpad.net/ubuntu/+source/msttcorefonts/+bug/1607535.

**Comment by igwyd** [comment]
Hello @post-duif , sorry for the late reply. Not reproduced, i have the same OS Ubuntu 22.04.3. What version docker and docker compose plugin do you have? We supported only official distribution Docker https://docs.docker.com/engine/install/ubuntu/

**Comment by githust66** [comment]
> Hello @post-duif , sorry for the late reply. Not reproduced, i have the same OS Ubuntu 22.04.3. What version docker and docker compose plugin do you have? We supported only official distribution Docker https://docs.docker.com/engine/install/ubuntu/
[Hello,](javascript:void(0)) [my](javascript:void(0)) [host](javascript:void(0)) [centos](javascript:void(0)) [installed](javascript:void(0)) [docker](javascript:void(0)) [and](javascript:void(0)) [compose,](javascript:void(0)) [and](javascript:void(0)) [I](javascript:void(0)) [also](javascript:void(0)) [encountered](javascript:void(0)) [this](javascript:void(0)) [problem](javascript:void(0)) [when](javascript:void(0)) [I](javascript:void(0)) [started](javascript:void(0)) [Docker-DocumentServer.](javascript:void(0)) [Which](javascript:void(0)) [version](javascript:void(0)) [of](javascript:void(0)) [docker](javascript:void(0)) [does](javascript:void(0)) [centos](javascript:void(0)) [need](javascript:void(0)) [to](javascript:void(0)) [install](javascript:void(0)) [to](javascript:void(0)) [start](javascript:void(0)) [normally?](javascript:void(0))
