### ISSUE TITLE
Can't load document files from nextcloud server

### ISSUE THREAD

**Issue by Cavesnakes** [ONLYOFFICE/Docker-DocumentServer#65]
My server diagram is described following images
![default](https://user-images.githubusercontent.com/24396573/27882070-26b4593e-6206-11e7-9bc5-9542824b830c.png)

![default](https://user-images.githubusercontent.com/24396573/27882073-27f0eb00-6206-11e7-9226-2d16c669b967.png)

**Comment by Cavesnakes** [comment]
if i connect to coauthoring/CommandService.ashx url
"{"error":1}" is prompted what can i do?

**Comment by ShockwaveNN** [comment]
I'll close this issue, since it's pretty old and recieved no comments (sorry).
If issue still actual please create new issue at https://github.com/ONLYOFFICE/onlyoffice-nextcloud repo
