### ISSUE TITLE
Error using docker-compose `unable to prepare context: unable to evaluate symlinks in Dockerfile path`:

### ISSUE THREAD

**Issue by AlexandreBonneau** [ONLYOFFICE/Docker-DocumentServer#655]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Not able to install the document server using the provided docker-compose.yml file

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Download the `docker-compose.yml` file, edit it to change the port from `80:80` to `8050:80`
Run `docker-compose up -d`

**What is the expected behavior?**
The build should be done.
Instead you get this log:
```
~ docker-compose up -d
Creating network "onlyoffice_default" with the default driver
Creating volume "onlyoffice_postgresql_data" with default driver
Pulling onlyoffice-rabbitmq (rabbitmq:)...
latest: Pulling from library/rabbitmq
3153aa388d02: Pull complete
031f71d6525f: Pull complete
1257e88a6ee9: Pull complete
d960a9b1f657: Pull complete
a750fc1a94bc: Pull complete
a3ba7b88e9d4: Pull complete
97135c6d202a: Pull complete
29163d7678ea: Pull complete
c304a02173b9: Pull complete
2b9107b21816: Pull complete
Digest: sha256:fabdedc08208eba75a47b0610fe8e05a377261f123bdf08aae2f9dc7dedcf9d8
Status: Downloaded newer image for rabbitmq:latest
Pulling onlyoffice-postgresql (postgres:9.5)...
9.5: Pulling from library/postgres
fa1690ae9228: Pull complete
a73f6e07b158: Pull complete
973a0c44ddba: Pull complete
07e5342b01d4: Pull complete
578aad0862c9: Pull complete
a0b157088f7a: Pull complete
6c9046f06fc5: Pull complete
ae19407bdc48: Pull complete
e53b7c20aa96: Pull complete
a135edcc0831: Pull complete
fed07b1b1b94: Pull complete
18d9026fcfbd: Pull complete
4d2d5fae97d9: Pull complete
d419466e642d: Pull complete
Digest: sha256:75ebf479151a8fd77bf2fed46ef76ce8d518c23264734c48f2d1de42b4eb40ae
Status: Downloaded newer image for postgres:9.5
Building onlyoffice-documentserver
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/onlyoffice/Dockerfile: no such file or directory
ERROR: Service 'onlyoffice-documentserver' failed to build : Build failed
```

**Did this work in previous versions of DocumentServer?**
Not tried

**DocumentServer Docker tag:**
N/A

**Host Operating System:**
Linux Ubuntu 22.04.3 LTS

**Comment by igwyd** [comment]
Hello @AlexandreBonneau, not reproduced, i have the same OS Ubuntu 22.04.3. What version docker and docker compose plugin do you have? We supported only official distribution Docker https://docs.docker.com/engine/install/ubuntu/

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
