### ISSUE TITLE
How to modify the docker port number

### ISSUE THREAD

**Issue by quixote1304629** [ONLYOFFICE/Docker-DocumentServer#658]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

When using the docker image to publish the container, is it possible to modify the service port number? Instead of 80, use 8090. 

For some special reasons, I must specify the port number of expose, such as “EXPOSE 8090” instead of “EXPOSE 80”

Do I need to modify the startup port in the code？

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
