### ISSUE TITLE
Error while downloading the document file to be converted.

### ISSUE THREAD

**Issue by garysan** [ONLYOFFICE/Docker-DocumentServer#659]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

 7.4.1.36

### Expected Behavior

Cannot connect onlyoffice with  nextcloud 27.0.2

### Actual Behavior

This error on nextcloud log. 
[onlyoffice] Error: Exception: Se ha producido un error en el servicio de documentos: Error while downloading the document file to be converted. at <<closure>>

0. /usr/share/nginx/html/nextcloud/apps/onlyoffice/lib/DocumentService.php line 95
   OCA\Onlyoffice\DocumentService->ProcessConvServResponceError("-4")
1. /usr/share/nginx/html/nextcloud/apps/onlyoffice/lib/DocumentService.php line 446
   OCA\Onlyoffice\DocumentService->GetConvertedUri("https://cloud.a ... c", "docx", "docx", "check_374368489")
2. /usr/share/nginx/html/nextcloud/apps/onlyoffice/lib/Controller/SettingsController.php line 181
   OCA\Onlyoffice\DocumentService->checkDocServiceUrl(["OC\\URLGenerat ... ]], ["OCA\\Onlyoffice\\Crypt"])
3. /usr/share/nginx/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Onlyoffice\Controller\SettingsController->SaveAddress("https://10.10.10.16:8181/", "", "", true, "Secret2020", "", false)
4. /usr/share/nginx/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Onlyoffic ... "], "saveAddress")
5. /usr/share/nginx/html/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Onlyoffic ... "], "saveAddress")
6. /usr/share/nginx/html/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("SettingsController", "saveAddress", ["OC\\AppFramewo ... "], ["onlyoffice.settings.save_address"])
7. /usr/share/nginx/html/nextcloud/lib/base.php line 1071
   OC\Route\Router->match("/apps/onlyoffice/ajax/settings/address")
8. /usr/share/nginx/html/nextcloud/index.php line 36
   OC::handleRequest()

### Reproduction Steps

create docker using self signed cert:
sudo docker run --name=onlyofficedocker -i -t -d -p 8181:443 \
-v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data \
-e JWT_ENABLED='true' -e JWT_SECRET='Secret2020' -e JWT_IN_BODY='true' -e JWT_HEADER='AuthorizationJwt' -e JWT_IN_BODY=true -e USE_UNAUTHORIZED_STORAGE=true \
--restart=always onlyoffice/documentserver

Try to connect from Nextcloud using https://10.10.10.16:8181

### Additional information

My config on nextcloud config.php have

'onlyoffice' =>
  array (
    'verify_peer_off' => true,
    "jwt_secret" => "Secret2020",
    "jwt_header" => "AuthorizationJwt"
),
  'allow_local_remote_servers' => true,

and my local.json 
  "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "AuthorizationJwt",
          "inBody": true
        },
        "outbox": {
          "header": "AuthorizationJwt",
          "inBody": true
        }
      },
      "secret": {
        "inbox": {
          "string": "Secret2020"
        },
        "outbox": {
          "string": "Secret2020"
        },
        "session": {
          "string": "Secret2020"
        }
      },
      "requestDefaults": {
        "rejectUnauthorized": false
      }

**Comment by Mer0me** [comment]
I have a very similar issue and even if there are lots of threads talking about close subjects, I can't solve my problem.
Nextcloud 27.1.1
OnlyOffice App 8.2.0
Dockerized OnlyOffice 7.2.2.56

My installation is working : I can open, edit, save documents without any problems. The app config page says that all is fine. 

BUT !

Sometimes, when browsing my files and folders in the nextcloud file app, it takes ages to display the file previews of all office document. When it happens, I get this error in the nginx.error.log  :

`2023/10/05 11:19:29 [error] 6399#6399: *647 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertService.ashx", host: "localhost:88"
`

and this one in the Nextcloud log : 

`{"reqId":"ZB9Y5uId1VoP1imBdKFW","level":3,"time":"2023-10-05T11:08:19+00:00","remoteAddr":"192.168.1.99","user":"user","app":"onlyoffice","method":"GET","url":"/index.php/core/preview?fileId=622185&c=b8638803dd22ce500fabc8ab0d8b3837&x=250&y=250&forceIcon=0&a=1","message":"GetConvertedUri: from pdf to jpeg","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0","version":"27.1.1.0","exception":{"Exception":"GuzzleHttp\\Exception\\ServerException","Message":"Server error: POST https://office.merome.net/ConvertService.ashx resulted in a 504 Gateway Time-out response:\n<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><c (truncated...)\n","Code":504,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":69,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":204,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":153,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":48,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":248,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":224,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":269,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":226,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":301,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/DocumentService.php","line":372,"function":"post","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/DocumentService.php","line":177,"function":"Request","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/DocumentService.php","line":91,"function":"SendRequestToConvertService","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/onlyoffice/lib/Preview.php","line":269,"function":"GetConvertedUri","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/ProviderV1Adapter.php","line":53,"function":"getThumbnail","class":"OCA\\Onlyoffice\\Preview","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":64,"function":"getThumbnail","class":"OC\\Preview\\ProviderV1Adapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":397,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":373,"function":"generateProviderPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":166,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":116,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":192,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":144,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":113,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"message":"GetConvertedUri: from pdf to jpeg","CustomMessage":"GetConvertedUri: from pdf to jpeg"}}
`

Browsing files is extremely slow, about 60s on each folder containing office documents. Although, preview thumbnails are visible. The timeout seems to occur randomly, but very often ~9/10 times when folder contains docs (maybe if there is one missing preview ?). When the folder is displayed, clicking on the nextcloud detail  or share button can cause a new very long delay, making nextcloud file browser nearly unusable.

I've already tried to :
- (un)set internal addresses in the app config => no effect
- Both Nextcloud and OnlyOffice servers can see each other on wget test
- increase the rabbitmq time out (*100) => no effect
- restart docker => no effect
- set access-control-allow-origin: * in the apache proxy config => no effect
- set false values on purpose on internal addresses config => I get a normal error and I can't make it works at all with those false values, so I guess my normal configuration is correct

Please help !

**Comment by igwyd** [comment]
Hello @Mer0me, you have the other issue, please create a new one with describe detail your deployment and add please the reprodusion steps for the bug. We try to help.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by KlaBra16F1** [comment]
Just had the same issue and in my case the error came from a modification in my nextclouds `config.php` file:
`'htaccess.RewriteBase' => '/'` (Youtube tip for securing Nextcloud 😬)
Once I removed that line and ran `./occ maintenance:update:htaccess` everything worked just fine and connected.
