### ISSUE TITLE
docker-compose up onlyoffice with an error 

### ISSUE THREAD

**Issue by charryong** [ONLYOFFICE/Docker-DocumentServer#666]
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
Errors were encountered while processing:
 rabbitmq-server
**E: Sub-process /usr/bin/dpkg returned an error code (1)**
ERROR: Service 'onlyoffice-documentserver' failed to build: The command '/bin/sh -c echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d &&     apt-get -y update &&     apt-get -yq install wget apt-transport-https gnupg locales lsb-release &&     locale-gen en_US.UTF-8 &&     echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections &&     apt-get -yq install         adduser         apt-utils         bomstrip         certbot         curl         gconf-service         htop         libasound2         libboost-regex-dev         libcairo2         libcurl3-gnutls         libcurl4         libgtk-3-0         libnspr4         libnss3         libstdc++6         libxml2         libxss1         libxtst6         mysql-client         nano         net-tools         netcat-openbsd         nginx-extras         postgresql         postgresql-client         pwgen         rabbitmq-server         redis-server         software-properties-common         sudo         supervisor         ttf-mscorefonts-installer         xvfb         zlib1g &&     if [  $(ls -l /usr/share/fonts/truetype/msttcorefonts | wc -l) -ne 61 ];         then echo 'msttcorefonts failed to download'; exit 1; fi  &&     echo "SERVER_ADDITIONAL_ERL_ARGS=\"+S 1:1\"" | tee -a /etc/rabbitmq/rabbitmq-env.conf &&     sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf &&     sed 's|\(application\/zip.*\)|\1\n    application\/wasm wasm;|' -i /etc/nginx/mime.types &&     pg_conftool $PG_VERSION main set listen_addresses 'localhost' &&     service postgresql restart &&     sudo -u postgres psql -c "CREATE USER $ONLYOFFICE_VALUE WITH password '$ONLYOFFICE_VALUE';" &&     sudo -u postgres psql -c "CREATE DATABASE $ONLYOFFICE_VALUE OWNER $ONLYOFFICE_VALUE;" &&     service postgresql stop &&     service redis-server stop &&     service rabbitmq-server stop &&     service supervisor stop &&     service nginx stop &&     rm -rf /var/lib/apt/lists/*' **returned a non-zero code: 100**

**Comment by charryong** [comment]
**and before this error,** 
Adding system user `rabbitmq' (UID 108) ...
Adding new user `rabbitmq' (UID 108) with group `rabbitmq' ...
Not creating home directory `/var/lib/rabbitmq'.
Created symlink /etc/systemd/system/multi-user.target.wants/rabbitmq-server.service → /lib/systemd/system/rabbitmq-server.service.
invoke-rc.d: could not determine current runlevel
 * Starting RabbitMQ Messaging Server rabbitmq-server

**it took a long time to start the rabbitmq-server。**

**Comment by igwyd** [comment]
Hello @charryong, provide please your server characteristics and operating system, i will check it.

**Comment by charryong** [comment]
5.10.0-60.67.0.96.ule3.x86_64 #1 SMP Mon Mar 6 14:21:16 CST 2023 x86_64 x86_64 x86_64 GNU/Linux 
openeuler linux

**Comment by cethink** [comment]
I got this too.
Linux alma 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 12 09:28:32 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cethink** [comment]
all errors:
```
249.9 invoke-rc.d: could not determine current runlevel
249.9  * Reloading system message bus config...
249.9 Failed to open connection to "system" message bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
249.9 invoke-rc.d: initscript dbus, action "force-reload" failed.
249.9 Failed to open connection to "system" message bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```
```
257.4 Setting up rabbitmq-server (3.9.13-1ubuntu0.22.04.1) ...
257.5 Adding group `rabbitmq' (GID 110) ...
257.5 Done.
257.5 Adding system user `rabbitmq' (UID 108) ...
257.5 Adding new user `rabbitmq' (UID 108) with group `rabbitmq' ...
257.6 Not creating home directory `/var/lib/rabbitmq'.
257.8 Created symlink /etc/systemd/system/multi-user.target.wants/rabbitmq-server.service → /lib/systemd/system/rabbitmq-server.service.
257.8 invoke-rc.d: could not determine current runlevel
257.8  * Starting RabbitMQ Messaging Server rabbitmq-server
859.9  * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
859.9    ...fail!
859.9 invoke-rc.d: initscript rabbitmq-server, action "start" failed.
859.9 dpkg: error processing package rabbitmq-server (--configure):
859.9  installed rabbitmq-server package post-installation script subprocess returned error exit status 1
```

**Comment by igwyd** [comment]
Thank you for the detaled report, but this is not repitted. My stand is openEuler 22.03 (LTS-SP2) 2cpu 4ram, openEuler   5.10.0-153.29.0.106.oe2203sp2.x86_64 GNU/Linux, Docker installed from openEuler included repos - Docker version 18.09.0, build ce4ae23, docker-compose version 1.22.0, build f46880f.

**Comment by charryong** [comment]
openEuler 22.03  Linux version 5.10.0-60.67.0.96.ule3.x86_64 (mockbuild@6945811ff1b54e7688dad4dceea22c81) (gcc_old (GCC) 10.3.1, GNU ld (GNU Binutils) 2.37) #1 SMP Mon Mar 6 14:21:16 CST 2023
，2cpu,Intel Xeon Processor (Skylake, IBRS)  16G ram, Docker Version:   0.19.0,docker-compose version 1.18.0, build 8dd22a9

**Comment by igwyd** [comment]
Maybe problem is in your docker installation? Try to use docker from the repositories openEuler like me.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
