### ISSUE TITLE
HTTPS Error: Mixed Contents

### ISSUE THREAD

**Issue by ketlinapuci** [ONLYOFFICE/Docker-DocumentServer#669]
Hello, I have installed onlyoffice in one Ubuntu 22.04.2 server following the instructions as in the onlyoffice.com page 

sudo docker run -i -t -d -p 80:80 -p 443:443 --restart=always \
    -e LETS_ENCRYPT_DOMAIN=yourdomain.com -e LETS_ENCRYPT_MAIL=email@example.com -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver-de

and used this, I have changed the ports accordingly and added my domain. I have also added the config files in apache2/sites-available directory . After I enabled the site, I could access it at https://domain.com, but after I executed the example and went to create a new document or edit a created one, I am redirected to a blank page and get this in the console
```
Mixed Content: The page at 'https://onlyoffice.evolutivo.it/example/editor?fileName=new%20(1).docx' was loaded over HTTPS, but requested an insecure frame 'http://onlyoffice.evolutivo.it/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=https://onlyoffice.evolutivo.it'. This request has been blocked; the content must be served over HTTPS.
```
WHat could be wrong , can you help me with this issue?
thank you

**Comment by 15810644043** [comment]
Hello, has the problem been dealt with

**Comment by igwyd** [comment]
Hello @ketlinapuci, sorry for the late reply. I guess this is because you use apache as an additional proxy and made any misstakes, check out our examples for proxies [here](https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx).

**Comment by igwyd** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
