### ISSUE TITLE
Can not edit file in example after installing by docker.

### ISSUE THREAD

**Issue by t-anh** [ONLYOFFICE/Docker-DocumentServer#676]
Hi all,

Base on installation guide, i have installed onlyoffice Docs Deverlopment Server by docker as following steps.

> sudo docker run -i -t -d -p 9080:80 --restart=always \
    -v /Users/user1/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /Users/user1/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /Users/user1/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v /Users/user1/onlyoffice/DocumentServer/db:/var/lib/postgresql -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver-de

After that i access http://localhost:9080/welcome/ and run 2 command at "Testing before integration"
> sudo docker exec eaf7f9327611 /var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'
sudo docker exec eaf7f9327611 sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf

And go to test example at http://localhost:9080/example/ 
At example page, I can upload and download file. but when edit file it display the following messages.

<img width="630" alt="The document could not be saved" src="https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/6572989/8f05f006-6564-47ed-996a-272118af8dbf">
<img width="302" alt="Download failed" src="https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/6572989/fb8eb523-fff5-4e6e-9acc-3844fa083ac1">

Please help me fix this issue.

**Comment by igwyd** [comment]
Hi @t-anh, it's because docker inside the container resolves to the localhost container's IP address, you should use IP address instead of localhost.

**Comment by t-anh** [comment]
@igwyd 
Thank you for you quick answer.
Now i can edit file after using IP address.
