### ISSUE TITLE
Why can't a domain name be used with onlyoffice?

### ISSUE THREAD

**Issue by a506488043** [ONLYOFFICE/Docker-DocumentServer#677]
**Do you want to request a *feature* or report a *bug*?**

Why can't a domain name be used with onlyoffice?
Directly using public IP and local IP can edit documents normally？
Why does a domain name call onlyOffice's wopi and it won't work?
Onlyoffice is deployed using dockers
![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/16434125/53af1c91-828c-4660-9447-72391225310a)
![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/16434125/84b314b7-1b4e-4b0a-a4e3-71315da5b10e)
![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/16434125/9011d284-5347-4e3f-b8d8-d0c5c5b0b629)

Is it a problem with where to set it up?
`docker run -i -t -d -p 9980:80 --restart=always \
-v /mnt/256G/docker/onlyoffice/logs:/var/log/onlyoffice \
-v /mnt/256G/docker/onlyoffice/data:/var/www/onlyoffice/Data \
-v /mnt/256G/docker/onlyoffice/lib:/var/lib/onlyoffice \
-v /mnt/256G/docker/onlyoffice/db:/var/lib/postgresql \
-v /mnt/256G/docker/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq \
-e WOPI_ENABLED=true \
-e ONLYOFFICE_HTTPS_HSTS_ENABLED=true \
-e REDIS_SERVER_HOST=127.0.0.1 \
-e REDIS_SERVER_PORT=6739 \
-e REDIS_SERVER_PASS=YCw6Hh \
-e LETS_ENCRYPT_DOMAIN=cloud.saiita.cn \
--name onlyoffice --restart="always" onlyoffice/documentserver
`

**What is the current behavior?**

Onlyoffice has set up a public domain name and configured it.
The public network service calls onlyoffice and does not work.
And the public IP calls onlyoffice, which can work normally.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

The domain name of the public network service can call the Wopi of onlyOffice normally

**Did this work in previous versions of DocumentServer?**

First deployment

**DocumentServer Docker tag:**

**Host Operating System:**
Linux ITX 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by igwyd** [comment]
Hello @a506488043, i guess it may error with your DNS server, provide please onlyoffice-documentserver logs.

**Comment by igwyd** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
