### ISSUE TITLE
Run docker without iterative mode 

### ISSUE THREAD

**Issue by rafilkmp3** [ONLYOFFICE/Docker-DocumentServer#68]
The Interative shouldn't be mandatory. 
In ECS i cant setup with "-i" flag .  
`docker run -i -t -d -p 80:80 onlyoffice/documentserver`

I need a way to run this only like a normal container, if i try to run like this the service starts and exits  
`docker run  -d -p 80:80 onlyoffice/documentserver`

**Comment by agolybev** [comment]
Hello @rafilkmp3
You are right. Docker container should start in nointeractive (default) mode.

**Comment by mandusm** [comment]
Here's a quick and ugly way to get it to work without -i
tested and works on ECS and K8s

https://github.com/ONLYOFFICE/Docker-DocumentServer/compare/master...mandusm:ugly-hack-%2368

**Comment by agolybev** [comment]
Hi @mandusm , Thank you for resolution. We'll test it.

**Comment by agolybev** [comment]
Hi @ikthorn.
Are you talking about [this](https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/100/commits/6a9c67795aeb1904aa8e9101661bcf96737d9bb5)?

**Comment by ikthorn** [comment]
Yep 👍

**Comment by temparus** [comment]
It seems to be fixed in the develop branch a while ago.
When is this fix expected to be released / merged into master?

**Comment by ShockwaveNN** [comment]
@temparus at least several months
