### ISSUE TITLE
Upgrade docker compose file version to 3

### ISSUE THREAD

**Issue by anyidea** [ONLYOFFICE/Docker-DocumentServer#680]
The version of the Docker Compose file is too old. Can you consider upgrading to version 3?

**Comment by igwyd** [comment]
Hello @anyidea, the docker compose file version 2 stll in support - https://docs.docker.com/compose/compose-file/compose-file-v2/. Do you have any reason to ask for an update?

**Comment by igwyd** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
