### ISSUE TITLE
[Feature] Docker secrets _FILE

### ISSUE THREAD

**Issue by mxmeeple** [ONLYOFFICE/Docker-DocumentServer#693]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Not implemented

**What is the expected behavior?**
env args to be gathered from `_FILE: /run/secrets/secret_file`

AFAICT this has gone stale for over a year despite having a feature branch for this and previous requests and PR's [ #282, #326, #472, #519 ]

**Comment by igwyd** [comment]
Hello @mxmeeple, I will remind the developers about it.
Duplicate of #326

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
