### ISSUE TITLE
SEQUENCE function is not working

### ISSUE THREAD

**Issue by serhat-io** [ONLYOFFICE/Docker-DocumentServer#713]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
SEQUENCE function does not create sequence

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Setup Docker as usual.
2. create example as described in "Testing before integration".
3. open table sheet
4. use this: =SEQUENCE(5;1;1)

**What is the expected behavior?**
SEQUENCE should fill row by row with 1,2,3,4,5

**Did this work in previous versions of DocumentServer?**
I do not know.

**DocumentServer Docker tag:**
This is my docker-compose file:
~~~yaml
version: '3'
services:
  documentserver:
    image: onlyoffice/documentserver
    restart: always
    container_name: onlyoffice
    environment:
      - JWT_SECRET
      - JWT_ENABLED=true
      - WOPI_ENABLED=false
      - EnableIPv6=false
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.onlyoffice.entrypoints=websecure
      - traefik.http.routers.onlyoffice.tls=true
      - traefik.http.services.onlyoffice.loadbalancer.server.port=80
      - traefik.http.routers.onlyoffice.rule=Host(`example.com`)
      - traefik.http.routers.onlyoffice.middlewares=onlyoffice
      - traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Host=example.com
networks:
    frontend:
        external: true
~~~

Even if I bypass traefik and use the Port directly, I have the same Problem.

**Host Operating System:**
 ~~~
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
~~~
~~~bash
unama -a
Linux django 5.15.0-1052-oracle #58-Ubuntu SMP Tue Feb 13 19:44:34 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
~~~

**Comment by serhat-io** [comment]
@rsnegirev 
If the sequence function is intended to work like this, then I would say that it does not work like on other platforms such as Microsoft or Google Sheets. There, the sequence is automatically generated as specified in the formula. I cannot cause an automatic generation based on another cell.

**Comment by rsnegirev** [comment]
Yes that's true. But for now this is how it works in the ONLYOFFICE editor.

We're working on this and some changes will be released in a future major version.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
