### ISSUE TITLE
Comments: Not possible to mention users from different Nextcloud groups

### ISSUE THREAD

**Issue by ltschk** [ONLYOFFICE/Docker-DocumentServer#723]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
In comments I can only mention users that are member of Nextcloud group "A", but not members of Nextcloud group "B". My Nextcloud user account is member of both groups "A" and "B". In the Nextcloud sharing settings the option "Restrict users to only share with user in their group" is activated, but as said before, I am a member of both groups. Sharing wihtin nextcloud frontent works as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Create a document
- add a comment
- type "+" and see the possible users to mention only from group "A"

**What is the expected behavior?**
As a member of both Nextcloud groups "A" and "B", I would expect that I could mention users from "A" as well as from "B" or even from "C" or more group (if I am also member).

**Did this work in previous versions of DocumentServer?**
Can't say, I just installed DocumentServer the first time.

**DocumentServer Docker tag:**
latest, presumably 8.0.1

**Host Operating System:**
QNAP Container Station Version 3.0.6.833
current firmware version of QNAP NAS: QTS 5.1.5.2679
NAS Model: TS-473

**Comment by matveevms** [comment]
Hello, @ltschk 
Please tell me which version of Nextcloud you are using?

**Comment by ltschk** [comment]
Hello @matveevms,

> Hello, @ltschk Please tell me which version of Nextcloud you are using?

I'm currently using Nextcloud 27.1.7.

**Comment by matveevms** [comment]
Thank you for report.
This is a known issue, ticket #66447. 
This will be fixed in the next updates.
