### ISSUE TITLE
OnlyOffice Documents cannot be opened if it exceeds 30MB, and can be opened normally if it is less than 30MB

### ISSUE THREAD

**Issue by cfy3133** [ONLYOFFICE/Docker-DocumentServer#727]
### Similar issues have been discovered before
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/659
### Operating System of DocumentServer
Docker
![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/43978367/384488bd-7f10-4e41-a8ab-c08d3fec4df7)

### Version information
8.0.1

### Expected Behavior
Unable to view Word document files larger than 30MB

### Actual Behavior
![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/43978367/606873e8-0dfb-4565-a66b-ef04fe367808)

### Reproduction Steps
docker run --name=documentserver -i -t -d -p 9997:80 -p 9998:8000 --restart=always -e JWT_ENABLED=false onlyoffice/documentserver

**Comment by avdddd1111** [comment]
Hello @cfy3133 !

Can you attach your document to this issue if it's over 30MB?

If the file is confidential, can you please send it to: files@onlyoffice.com? (If yes, please specify the version: DocumentServer#[issue-number]).

**Comment by cfy3133** [comment]
Thank you very much for the author's patient answer
![1713234307596](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/43978367/c6d3b255-03d0-462e-8ea1-fd7690016dee)

**Comment by avdddd1111** [comment]
I'm glad you solved issue yourself!
