### ISSUE TITLE
What is the secret of connecting a community server to a document server?

### ISSUE THREAD

**Issue by bertalanimre** [ONLYOFFICE/Docker-DocumentServer#73]
Hey Folks,

I'm ripping my hair our slowly from my head, please help me a little.

- I've installed on server "A" owncloud. Works, done, everything is fine.
- I've installed on server "B" DocumentServer according to this README for this repository. (with SSL)

No matter what I do, I can't connect them to eachother. The error message in owncloud I receive always is: `Error when trying to connect (Bad request or timeout error)`

Why? No firewall, ping OK, NginX OK, what else?

**Comment by trofim24** [comment]
@LinneyS, @ShockwaveNN

**Comment by LinneyS** [comment]
What message when saving settings? What's in the logs ownCloud?

**Comment by bertalanimre** [comment]
The error message is as above: Error when trying to connect (Bad request or timeout error)

Unfortunately I can't tell you now the ownClouds error message because the VPS provider is down. :( I'll post it as soon as I can ready up with it. 

In the meanwhile: Can I install them on one server with 2 different domain names? Like: cloud.mycompany.com and docs.mycompany.com ?

**Comment by LinneyS** [comment]
Maybe you are interested in https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud?
It is not necessary for a Document Server to have a domain.

You must specify the address of the DocumentServer that will be accessible from the client. ownCloud and DocumentServer make requests among themselves. If public addresses (domains) are not available, then you need to specify internal addresses: ownCloud to DS and DS to ownCloud
https://api.onlyoffice.com/editors/owncloud#settings

**Comment by bertalanimre** [comment]
Lol, I didn't know about docker-onlyoffice-owncloud. Trying it now in VM. However even if it works the best and most preferred method would be to install everything without using docker. Even document server. But I always get lost in the installation manuals for CentOS 7. Somewhy I always have to tweak the installation to my server, donno why. It is a standard CentOS 7.1 minimal installation.

**Comment by alexanderonlyoffice** [comment]
Hello @bertalanimre, 

> No firewall, ping OK, NginX OK, what else?

Try to use **_wget_** command instead of **_ping_** command to check the accessibility of the Document Server.

If you have any questions regarding installation/use of VM version, contact us at support@onlyoffice.com

**Comment by ionics** [comment]
Info:
I had the same error message. 
I did install onlyoffice via docker on ubuntu 16.04 server.
I configured HTTPS for onlyoffice and it worked just fine.
If you do use a self signed CERT on the onlyoffice-Server than add 
this section:
  'onlyoffice' =>
   array (
      'verify_peer_off' => true,
   ),
);

to your nextcloud config file via vim, vi, nano or whatever you prefer.
vim /var/www/nextcloud/config/config.php 

I did integrate nextcloud from the onlyoffice Admin Interface (Backend) so i could browse and open and edit nextcloud files but in the onlyoffice backend.

What i wanted additionally to achieve was, to integrate onlyoffice directly in nextcloud.
I did install the App in the nextcloud Admin Interface.
I did deactivate collabora (as it should not conflict with onlyoffice) - just in case some has collabora activated.

Via nextcloud -> Admin -> "Additional Settings" under the ONLYOFFICE config section, where there is written "Document Editing Service address", here there was the fault why my setup did not work, and i did receive the "Error when trying to connect (Bad request or timeout error)" Error. 
Problem:
In all online resources, forums and blogs its written you have to fill in the domain of your onlyoffice server, which in my case is 'https://only.develissimo.com' but in fact i hat to type in the following URL with a subdirectory 'https://only.develissimo.com/ds-vpath/'

Now the ONLYOFFICE nextcloud Integrations works out just fine.

By the way, the path i got from https://onlyoffice.exampledomain.com/management.aspx?type=17 setup page where "Document Editing Service Address" is "https://only.develissimo.com/ds-vpath/web-apps/apps/api/documents/api.js"

Hope this will help you solve this issue.

Good luck,
Raphael

**Comment by ShockwaveNN** [comment]
I think this issue is related more to nextcloud (and seems resolved), so I'll close it. Feel free to comment though.
