### ISSUE TITLE
Failed to modify the document name.

### ISSUE THREAD

**Issue by githust66** [ONLYOFFICE/Docker-DocumentServer#732]
**Do you want to request a *feature* or report a *bug*?**

 report a bug

**What is the current behavior?**

Modify the file name when editing a document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Modify the document name when editing the document, and the input box will be reset to the original name after the modification. Or open the menu, rename and refresh the web page, and the name will be the same, and it will be reset.

**What is the expected behavior?**

Modification succeeded.

**Did this work in previous versions of DocumentServer?**

I don't know

**DocumentServer Docker tag:**

Docker-DocumentServer master latest

**Host Operating System:**

Linux iZuf66bzyv51fwe7hll0zfZ 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Rox-Lvmaohua** [comment]
I also encountered this problem. My current idea is that the file is stored locally, which prevents the file name modified in the front-end from being synchronized to the local, resulting in renaming failure.

**Comment by askonev** [comment]
@githust66 Are you working with a document through our test file manager? (route /example)

**Comment by githust66** [comment]
> @githust66 Are you working with a document through our test file manager? (route /example)

yes

**Comment by askonev** [comment]
Dear @githust66. On the start page of the example, it says "Get started with a demo-sample of ONLYOFFICE Document Editors..." In other words, this project is the basis for further development. You can join the development of the test case and contribute to the improvement of the product. 
https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs

Also, when changing the file name, you may have noticed logs in the browser console:

```js
onRequestRename: "test"

{"result":{"status":200,"statusCode":200,"statusMessage":"OK","headers":{"server":"nginx","date":"Fri, 07 Jun 2024 10:07:47 GMT","content-type":"application/json","content-length":"54","connection":"keep-alive","vary":"Accept-Encoding","etag":"W/\"36-2ghBtktqWX7dsEXIhhVEByiI2bI\""},"size":54,"aborted":false,"rt":5,"keepAliveSocket":false,"data":{"type":"Buffer","data":[123,34,107,101,121,34,58,34,49,57,50,46,49,54,56,46,52,46,49,51,56,110,101,119,46,100,111,99,120,49,55,49,55,55,53,50,57,53,57,54,53,50,34,44,34,101,114,114,111,114,34,58,48,125]},"requestUrls":["/coauthoring/CommandService.ashx"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":80,"socketHandledRequests":1,"socketHandledResponses":1}}
```

Which means that the event https://api.onlyoffice.com/editors/config/events#onRequestRename it works correctly

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
