### ISSUE TITLE
The installation with docker-compose was unsuccessful. The last line always shows: Installing plugins, please wait..., and CPU usage is always 100%

### ISSUE THREAD

**Issue by forqsg** [ONLYOFFICE/Docker-DocumentServer#733]
Follow the installation steps on the official website：
<img width="1241" alt="4cf0e10bfc8f9e5bc6cfaba490993dd" src="https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/46246735/fc35d803-80d7-4b71-bb8e-df15f4f76967">

<img width="1078" alt="e937b8069e6d2c1374511b8e7d08c7f" src="https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/46246735/6ce8d56a-356d-4fb0-8798-9c5a28762491">

<img width="493" alt="1715309923892" src="https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/46246735/4af8505c-e7e0-4277-9049-bb34f4180121">

By the way, the OS is centos 7.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
