### ISSUE TITLE
Conversion API add watermark

### ISSUE THREAD

**Issue by simon-sun** [ONLYOFFICE/Docker-DocumentServer#737]
我把xlsx文档转换为pdf，转换时加上如下配置，文件可以正常转换，就是水印没加上去，我用的是社区版本的，是社区版本不支持使用java代码么？
参考的连接地址：https://api.onlyoffice.com/editors/conversionapi#watermark
具体代码：
    "watermark": {
        "align": 1,
        "fill": [255, 0, 0],
        "height": 100,
        "margins": [ 10, 10, 10, 10 ],
        "paragraphs": [
            {
                "align": 2,
                "fill": [255, 0, 0],
                "linespacing": 1,
                "runs": [
                    {
                        "bold": true,
                        "italic": false,
                        "fill": [0, 0, 0],
                        "font-family": "Arial",
                        "font-size": 40,
                        "strikeout": false,
                        "text": "Watermark",
                        "underline": false
                    },
                    {
                        "text": "<%br%>"
                    }
                ]
            }
        ],
        "rotate": -45,
        "transparent": 0.3,
        "type": "rect",
        "stroke-width": 1,
        "stroke": [0, 0, 255],
        "width": 100
    }

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
