### ISSUE TITLE
arm64 start rabbitmq error

### ISSUE THREAD

**Issue by lz610756247** [ONLYOFFICE/Docker-DocumentServer#748]
I use Qemu VM to run docker version
VM OS is openEuler(Linux) arm64
The DocumentServer version is 8.0.1，and docker version is 19.03.13
The problem is rabbitmq can not start

docker container log is 
![rabbitmq_error](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/11540713/cc88a21d-d0dc-4ac0-8035-afa36976a107)

the startup_err is：Gracefully halting Erlang VM
![微信截图_20240623153550](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/11540713/46f4b722-0b2b-453f-be97-35b71e3cb9f8)

can you help me to deal with this problem，Thank you...

**Comment by igwyd** [comment]
Hello @lz610756247, this looks like a server problem with low resources, do you comply with the requirements https://helpcenter.onlyoffice.com/installation/docs-enterprise-sys-reqs-docker.aspx#:~:text=CPU%20single%20core,More%20is%20better

**Comment by lz610756247** [comment]
@igwyd Thank you a lot！ , I will use othrer device to try it agtin.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
