### ISSUE TITLE
unattended-upgrades is automatically enabled in docker

### ISSUE THREAD

**Issue by ivanmaria** [ONLYOFFICE/Docker-DocumentServer#754]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In dockerfile, 'software-properties-common' package is being installed. This library installs 'unattended-upgrades' via recommends.
This library creates a new file '/etc/apt/apt.conf.d/20auto-upgrades' and sets the following config:
> APT::Periodic::Update-Package-Lists "1";
> APT::Periodic::Unattended-Upgrade "1";

This means apt with try to update the package lists and auto upgrade the packages within the docker container at runtime at specific intervals. Through observation, we found out that this was happening every Thursday 12pm IST across all timezones.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
NA

**What is the expected behavior?**
We do not want to auto upgrade packages at runtime since unchecked updates may bring down the whole application down.

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer Docker tag:**
Docker-DocumentServer

**Host Operating System:**
NA

**Question:**
1. Can we modify the dockerfile and add '--no-install-recommends' so that the docker is not bloated with such similar packages?

**Comment by avdddd1111** [comment]
Hello @ivanmaria ! 

I can confirm - this is bug. 
Issue #69609.

**Comment by Rita-Bubnova** [comment]
This has been fixed ([ONLYOFFICE/sdkjs@12e7079](https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/7de5df8df9e2b8953e6f9958223900cd1876503e)) and will be released in the next release.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
