### ISSUE TITLE
–no-install-recommends required in dockerfile apt-get install command

### ISSUE THREAD

**Issue by paragkhachane** [ONLYOFFICE/Docker-DocumentServer#755]
Hi Team,

Current dockerfile contains command to install required dependencies of DocumentServer using apt-get install.
This leads to not only direct dependencies but also recommended packages being installed in the image.

This cause bloat and also leaves docker image vulnerable to issues present in these recommended dependencies.

Is it possible to take this up to reduce image size as well as make the image more secure

**Comment by igwyd** [comment]
Hello @paragkhachane, this is duplicate of #754, we will consider the modification. Thank you for report.
