### ISSUE TITLE
WOPI_ENABLED reset to false after restarting container

### ISSUE THREAD

**Issue by tbswork1** [ONLYOFFICE/Docker-DocumentServer#757]
**Host Operating System:**
Ubuntu 20.04

After restarting the container, WOPI_ENABLED reverted to false.

**Comment by igwyd** [comment]
Hello @tbswork1, I checked it on our latest version 8.1.1, the isssue does not recur. Please provide steps to reproduce.
I checked it like this:
```
sudo docker run -i -t -d -p 80:80 -e WOPI_ENABLED=true onlyoffice/documentserver
```
I run wopi test example `http://<documentserver>/example/wopi` and create a document. Then i restart the docker container:
```
docker restart <container_id>
```
And again created a document in wopi test example.
Result: documents are created, wopi is enabled.

**Comment by tbswork1** [comment]
I enabled it in the config. It seems it works after a while if I don't restart the container.

**Comment by igwyd** [comment]
> I enabled it in the config. It seems it works after a while if I don't restart the container.

Config reset after restart, if you want to save it then use docker variable like ```WOPI_ENABLED=true```, all variable are in [available-configuration-parameters](https://github.com/ONLYOFFICE/Docker-DocumentServer?tab=readme-ov-file#available-configuration-parameters).
