### ISSUE TITLE
editor.bin download failed

### ISSUE THREAD

**Issue by zjt148680** [ONLYOFFICE/Docker-DocumentServer#764]
**Do you want to request a *feature* or report a *bug*?**
feature

1. I have deployed OnlyOffice using Docker on the host `123.123.123.123:8889`(It's example).
2. I am using Nginx to proxy `123.123.123.123/oo` to `127.0.0.1:8889`.
![image](https://github.com/user-attachments/assets/f818f198-60f3-4c6f-ace4-456dd569eab8)
3. I found that when opening documents, there are requests like the following:
![image](https://github.com/user-attachments/assets/7b6a0726-61cb-4494-ba81-4db532a3cf74)

This causes I can't open the document.

To make the URL for this request 123.123.123.123/oo/..., how should I proceed?

**Comment by QingFengSpace** [comment]
How did you solve it? I have the same problem

**Comment by zjt148680** [comment]
> 你是怎么解决的？我也有同样的问题

https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

**Comment by guanyueyun** [comment]
Can only port 80 be used?
