### ISSUE TITLE
use dameng db , api ConvertService.ashx is error

### ISSUE THREAD

**Issue by wallyhe** [ONLYOFFICE/Docker-DocumentServer#768]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
use mysql, api ConvertService.ashx is ok
but use dameng api ConvertService.ashx is timeout
**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**

**Comment by igwyd** [comment]
Hello @wallyhe, I checked the documentserver conversion service with damengdb and found no errors, conversation was succefull. Provide please steps to repruduce and documentserver logs.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
