### ISSUE TITLE
how to make iframe JS request to skip verification of Docs server's SSL certificate

### ISSUE THREAD

**Issue by tbswork1** [ONLYOFFICE/Docker-DocumentServer#769]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
iframe for loading office doc verifies Docs server's SSL cert when it connects to it. However the Docs server is only running in internal network and configured with a self-signed SSL cert.

**Comment by tbswork1** [comment]
not possible with a stock browser.

**Comment by igwyd** [comment]
Hello @tbswork1, you can use ```USE_UNAUTHORIZED_STORAGE=true``` in docker variable to skip sertificate validation or you can create your own certificates, add your own certificate authority to your network, your PCs and servers and add it to the documentserver with variable ```NODE_EXTRA_CA_CERTS```. All docker variables in the [available-configuration-parameters](https://github.com/ONLYOFFICE/Docker-DocumentServer?tab=readme-ov-file#available-configuration-parameters).
