### ISSUE TITLE
lastest docker, not smb/cifs

### ISSUE THREAD

**Issue by pope-L** [ONLYOFFICE/Docker-DocumentServer#772]
DocumentServer Docker tag: lastest
External storage enables
no smb/cifs, notice smbclient not install

**Comment by igwyd** [comment]
Hello @pope-L, please fill out the issue template and provide steps to reproduce. If you want a feature request, then add a user scenario and discription.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
