### ISSUE TITLE
How to protect my DocumentServer from other website using it.

### ISSUE THREAD

**Issue by rkkoszewski** [ONLYOFFICE/Docker-DocumentServer#79]
Hi, 

I have just installed the Onlyoffice DocumentServer (Docker) and integrated it with my native (Non-Docker) Nextcloud setup. I'm using a domain www.mydomain.com for Nextcloud and editor.mydomain.com for the DocumentServer. Everything is running fast and smoothly now, and the integration with Nextcloud was very very easy (Just specifying the editor.mydomain.com domain in the Admin settings).

And that is exactly my concern. What prevents somebody else to find out my editor.mydomain.com domain and use it in their own Nextcloud or other setup? Is there some way to protect my server so only I can use it?

**Comment by ShockwaveNN** [comment]
You should use JWT (`JWT_ENABLED`, `JWT_SECRET` and `JWT_HEADER` env keys for `docker run` )

**Comment by rkkoszewski** [comment]
It works! Didn't knew that that was the secret key mentioned in Nextcloud configuration section. It works flawlessly now. Thank you very much.
