### ISSUE TITLE
nginx: failed (99: Cannot assign requested address ←→ Unknown error: Press "OK" to return to document list.

### ISSUE THREAD

**Issue by roboto-cloud** [ONLYOFFICE/Docker-DocumentServer#80]
Hi, I get this error and use the examples: 

https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-to-virtual-path.conf
https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud

### Unknown error: Press "OK" to return to document list.

**my nginx log:**

` [crit] 443#0: *14 connect() to [::1]:8080 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.19.0.2, server: , request: "GET /2017-10-28-08-40/spellchecker/doc/93_1510537868/c/203/bot2j4ew/websocket HTTP/1.1", upstream: "http://[::1]:8080/doc/93_1510537868/c/203/bot2j4ew/websocket", host: "drive.roboto.cloud"`

**my scenario is:**

onlyoffice←→nextcloud←→loadbalancer←→internet
nginx(80)←→nginx(80)←→traefik(443)←→internet
failed      ←→   200      ←→    200
thanks in advance,
![32689941-411b50be-c6ee-11e7-9d84-d9c2772f3ae4](https://user-images.githubusercontent.com/32390825/32706716-76a88cd8-c81f-11e7-85cb-79921a46bc79.png)

**Comment by agolybev** [comment]
Hi @roboto-cloud, I think it is proxying related issue. I'm not sure that proxying is fully supported by [our](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud) nextcloud installation. 
Could you verify whether docker-onlyoffice-owncloud work properly without proxying?

**Comment by roboto-cloud** [comment]
Hi, thanks @agolybev!
yes, it is proxying related issue and I fix it adding one line and changing other line into **_nginx.conf_** file using your [nextcloud example installation](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud).

 **_nginx.conf_** →→  

```
	location ~* ^/ds-vpath/ {
                ....
                proxy_set_header X-Forwarded-Proto https;
                proxy_read_timeout 36000s;
        }
```
Regards!

**Comment by agolybev** [comment]
Hi @roboto-cloud, good news! 
Also you could fix it by adding `X-Forwarded-Proto` header on traefik proxy server.

**Comment by mattronix** [comment]
@roboto-cloud  Hi, Where did you apply that in the nginx of the document server or the nginx of the nextcloud?

**Comment by mattronix** [comment]
@agolybev  does setting X-Forwarded-Proto work on docker backend?

**Comment by mattronix** [comment]
Ah understood thank you, makes sense.

**Comment by fredleb** [comment]
> Hi @roboto-cloud, good news!
> Also you could fix it by adding `X-Forwarded-Proto` header on traefik proxy server.

Hi !
Could you share an example of how to do that ?

Thanks for your input !
