### ISSUE TITLE
Only office document server installed can't create documents 

### ISSUE THREAD

**Issue by arunksasi** [ONLYOFFICE/Docker-DocumentServer#82]
Hi all,

I have installed document server in debain 8.9 , After installation I am getting the page says `Document server is running ` Since I have to create documents , What i have to do next? Please help me on this .

**Comment by arunksasi** [comment]
any one Please help me ...

**Comment by ShockwaveNN** [comment]
You should integrate it with file storage (like owncloud\nextcloud) or use our `onlyoffice-documentserver-ie` with our integration example

**Comment by agolybev** [comment]
Hi @arunksasi, thank you for interesting to our product. 
Onlyoffice Document Server provides documents editing only. You've seen the welcome page, it purposes to ensure that document server have installed successfully.
Please, refer to  [documentations](https://api.onlyoffice.com/editors/basic) how to integrate Document Server to your own application or service. Also see our [example](https://github.com/ONLYOFFICE/document-server-integration) how to use Onlyoffice Document Server

**Comment by arunksasi** [comment]
Hi thanks for your reply .
Since I don't have my own application services , How can I use document server ?
Can u help me ?

**Comment by agolybev** [comment]
@arunksasi, you may use it with [Onlyoffice CommunityServer](https://github.com/ONLYOFFICE/Docker-CommunityServer)

**Comment by arunksasi** [comment]
@agolybev   hi , I want to use this document server in my local net work , I don't have a valid domian. will the mail server module work properly ? Or I need to do something fore that ?

**Comment by agolybev** [comment]
Yes I've seen problem. Mail Server is unnecessary componet, try installing without it.
I'm not familar with Community Server but I think [Step 5](https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-onlyoffice-community-server-integrated-with-document-and-mail-servers) will be like this:
```
sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-community-server -p 80:80 -p 443:443 -p 5222:5222 \
 -e MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw \
 -e MYSQL_SERVER_DB_NAME=onlyoffice \
 -e MYSQL_SERVER_HOST=onlyoffice-mysql-server \
 -e MYSQL_SERVER_USER=onlyoffice_user \
 -e MYSQL_SERVER_PASS=onlyoffice_pass \
 
 -e DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server \
 
 -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
 -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
 onlyoffice/communityserver
```

**Comment by arunksasi** [comment]
@agolybev Thanks ,
I will try it .
