### ISSUE TITLE
Plugins not working in Nextcloud

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/Docker-DocumentServer#84]
I see all the Plugins but none of them are working.

Ubuntu 16.04
Apache2

All updated. Docker Image running on Port 8000.

#  Apache 2 Conf

<VirtualHost *:443>
ServerName xxxx.com

SSLEngine on
SSLCertificateFile "/etc/letsencrypt/live/xxxxx/fullchain.pem"
SSLCertificateKeyFile "/etc/letsencrypt/live/xxxxxxxx/privkey.pem"

SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
SSLProtocol All -SSLv2 -SSLv3
SSLCompression off
SSLHonorCipherOrder on

SetEnvIf Host "^(.*)$" THE_HOST=$1
RequestHeader setifempty X-Forwarded-Proto https
RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
ProxyAddHeaders Off

ProxyPassMatch (.*)(\/websocket)$ "ws://localhost:8000/$1$2"
ProxyPass / "http://localhost:8000/"
ProxyPassReverse / "http://localhost:8000/"
</virtualhost>

**Comment by agolybev** [comment]
Hi @ExaconAT, I'm trying reproduce this issue at this moment.

**Comment by K0R0L** [comment]
It will be fixed in next release (5.0.5)

**Comment by ExaconAT** [comment]
This is confirmed?

**Comment by K0R0L** [comment]
Yes
