### ISSUE TITLE
Firefox - No copy & paste 

### ISSUE THREAD

**Issue by TheMrApostel** [ONLYOFFICE/Docker-DocumentServer#88]
Within the newest version of firefox (59.0.1) it is not possibly to copy and paste anymore.
Chrome and IE are working fine.

I am using Version 5.0.7 of the CE

**Comment by ShockwaveNN** [comment]
Please duplicate your issue in https://github.com/ONLYOFFICE/DocumentServer/issues. This repo for Docker related issues.
And add more details - steps to reproduce, test environment (which OS you are using)
