### ISSUE TITLE
i upgraded to 5.1.0.115 and now I'm getting 404 errors

### ISSUE THREAD

**Issue by ccruson** [ONLYOFFICE/Docker-DocumentServer#93]
it seems some images are missing these are the errors I'm getting:

content_control_toc_2x.png:1 GET /sdkjs/common/Images/content_control_toc_2x.png 404 (Not Found)

content_control_toc_active.png:1 GET /sdkjs/common/Images/content_control_toc_active.png 404 (Not Found)

content_control_toc.png:1 GET /sdkjs/common/Images/content_control_toc.png 404 (Not Found)

content_control_toc_active_2x.png:1 GET /sdkjs/common/Images/content_control_toc_active_2x.png 404 (Not Found)

table_move.png:1 GET /sdkjs/common/Images/table_move.png 404 (Not Found)

table_move_2x.png:1 GET /sdkjs/common/Images/table_move_2x.png 404 (Not Found)

Thought you guys should know about it

**Comment by ShockwaveNN** [comment]
We released 5.1.1 and this problem should be fixed
