### ISSUE TITLE
Document Server suddenly timed out?

### ISSUE THREAD

**Issue by datvm** [ONLYOFFICE/Docker-DocumentServer#95]
Hi,

I have installed Document Server on my server successfully. Recently however we cannot use it anymore. I tried accessing http://localhost/ on the server, after a very long time, the Url is redirected to http://localhost/welcome/ with the timeout message:

504 Gateway Time-out
nginx

I have tried to restart the server. How can I troubleshoot this problem?

RAM and CPU stats are good. Nothing spike when I access them.

**Comment by ShockwaveNN** [comment]
Please add info about docker image version and you can see logs inside container in `/var/log/onlyoffice/` path and default nginx log in `/var/log/nginx`

**Comment by datvm** [comment]
Hi sorry I forgot the information, it's on a Windows server.

**Comment by ShockwaveNN** [comment]
Did you use docker on windows? This issue tracker for Docker variant, if not please close this issue and create new one in https://github.com/ONLYOFFICE/DocumentServer

**Comment by datvm** [comment]
Sorry I didn't notice.
